
function __fish_complete_diff -d 'Complete diff/colordiff' --argument-names diff
    complete -c $diff -s i -l ignore-case --description "Ignore case differences"
    complete -c $diff -l ignore-file-name-case --description "Ignore case when comparing file names"
    complete -c $diff -l no-ignore-file-name-case --description "Consider case when comparing file names"
    complete -c $diff -s E -l ignore-tab-expansion --description "Ignore changes due to tab expansion"
    complete -c $diff -s b -l ignore-space-change --description "Ignore changes in the amount of white space"
    complete -c $diff -s w -l ignore-all-space --description "Ignore all white space"
    complete -c $diff -s B -l ignore-blank-lines --description "Ignore changes whose lines are all blank"
    complete -c $diff -s I -l ignore-matching-lines -x --description "Ignore changes whose lines match the REGEX"
    complete -c $diff -s a -l text --description "Treat all files as text"
    complete -c $diff -s r -l recursive --description "Recursively compare subdirectories"
    complete -c $diff -s N -l new-file --description "Treat absent files as empty"
    complete -c $diff -s C -l context -x --description "Output NUM lines of copied context"
    complete -c $diff -s c --description "Output 3 lines of copied context"
    complete -c $diff -s U -l unified -x --description "Output NUM lines of unified context"
    complete -c $diff -s u --description "Output 3 lines of unified context"
    complete -c $diff -s q -l brief --description "Output only whether the files differ"
    complete -c $diff -l normal --description "Output a normal diff"
    complete -c $diff -s y -l side-by-side --description "Output in two columns"
    complete -c $diff -s W -l width -x --description "Output at most NUM print columns"
    complete -c $diff -s d -l minimal --description "Try to find a smaller set of changes"
    complete -c $diff -l from-file -r --description "Compare FILE1 to all operands"
    complete -c $diff -l to-file -r --description "Compare FILE2 to all operands"
    complete -c $diff -s l -l paginate --description "Pass the output through 'pr'"
    complete -c $diff -s v -l version --description "Display version and exit"
    complete -c $diff -l help --description "Display help and exit"
end
