# localization: skip(private)
function __fish_color_variables
    printf %s "\
fish_color_autosuggestion
fish_color_cancel
fish_color_command
fish_color_comment
fish_color_cwd
fish_color_end
fish_color_error
fish_color_escape
fish_color_host
fish_color_host_remote
fish_color_keyword
fish_color_normal
fish_color_operator
fish_color_option
fish_color_param
fish_color_quote
fish_color_redirection
fish_color_search_match
fish_color_selection
fish_color_user
fish_pager_color_background
fish_pager_color_completion
fish_pager_color_description
fish_pager_color_prefix
fish_pager_color_progress
fish_pager_color_secondary_background
fish_pager_color_secondary_completion
fish_pager_color_secondary_description
fish_pager_color_secondary_prefix
fish_pager_color_selected_background
fish_pager_color_selected_completion
fish_pager_color_selected_description
fish_pager_color_selected_prefix
"
end
