function __fish_graphviz__print_formats
    echo bmp \
        cgimage \
        canon \
        dot \
        gv \
        xdot \
        xdot1.2 \
        xdot1.4 \
        eps \
        exr \
        fig \
        gd \
        gd2 \
        gif \
        gtk \
        ico \
        imap \
        imap_np \
        ismap \
        cmap \
        cmapx \
        cmapx_np \
        jpg \
        jpeg \
        jpe \
        2000 \
        jp2 \
        json \
        json0 \
        dot_json \
        xdot_json \
        pdf \
        pic \
        pct \
        pict \
        plain \
        plain-ext \
        png \
        pov \
        ps \
        ps2 \
        psd \
        sgi \
        svg \
        svgz \
        tga \
        tif \
        tiff \
        tk \
        vml \
        vmlz \
        vrml \
        wbmp \
        webp \
        xlib \
        x11
end