# localization: tier3
function __fish_complete_firefox -a firefox
    # X11 options
    complete $firefox -l display -r -d "X display to use"
    complete $firefox -l sync -d "Make X calls synchronous"
    complete $firefox -l g-fatal-warnings -d "Make all warnings fatal"

    # Firefox options
    complete $firefox -s h -l help -d "Print this message"
    complete $firefox -s v -l version -d "Print Firefox version"
    complete $firefox -l full-version -d "Print Firefox version, build and platform build ids"
    complete $firefox -s P -r -d "Start this profile" -fa '(string replace -rf "^Name=(.*)" \'$1\' < ~/.mozilla/firefox/profiles.ini)'
    complete $firefox -l profile -r -d "Start with profile at <path>"
    complete $firefox -l migration -d "Start with migration wizard"
    complete $firefox -l ProfileManager -d "Start with ProfileManager"
    complete $firefox -l no-remote -d "Do not accept or send remote commands implies --new-instance"
    complete $firefox -l new-instance -d "Open new instance, not a new window in running instance"
    complete $firefox -l safe-mode -d "Disables extensions and themes for this session"
    complete $firefox -l allow-downgrade -d "Allows downgrading a profile"
    complete $firefox -l MOZ_LOG -rf -d "Treated as MOZ_LOG=<modules> environment variable, overrides it"
    complete $firefox -l MOZ_LOG_FILE -r -d "Treated as MOZ_LOG_FILE=<file> environment variable, overrides it"
    complete $firefox -l headless -d "Run without a GUI"
    complete $firefox -l jsdebugger -d "Open the Browser Toolbox"
    complete $firefox -l wait-for-jsdebugger -d "Spin event loop until JS debugger connects"
    complete $firefox -l start-debugger-server -d "Start the devtools server on a TCP port or Unix domain socket path"
    complete $firefox -l browser -d "Open a browser window"
    complete $firefox -l new-window -r -d "Open <url> in a new window"
    complete $firefox -l new-tab -r -d "Open <url> in a new tab"
    complete $firefox -l private-window -r -d "Open <url> in a new private window"
    complete $firefox -l preferences -d "Open Preferences dialog"
    complete $firefox -l screenshot -d "Save screenshot to <path> or in working directory"
    complete $firefox -rf -l window-size -d "Width and optionally height of screenshot"
    complete $firefox -l search -r -d "Search <term> with your default search engine"
    complete $firefox -l setDefaultBrowser -d "Set this app as the default browser"
    complete $firefox -l first-startup -d "Run post-install actions before opening a new window"
    complete $firefox -l kiosk -d "Start the browser in kiosk mode"
    complete $firefox -l disable-pinch -d "Disable touch-screen and touch-pad pinch gestures"
    complete $firefox -l jsconsole -d "Open the Browser Console"
    complete $firefox -l devtools -d "Open DevTools on initial load"
    complete $firefox -l marionette -d "Enable remote control server"
    complete $firefox -f -l remote-debugging-port -d "Start the Firefox Remote Agent"
    complete $firefox -f -l remote-allow-hosts -r -d "Values of the Host header to allow for incoming requests"
    complete $firefox -f -l remote-allow-origins -r -d "Values of the Origin header to allow for incoming requests"
end
