function __fish_complete_gpg2 -d "Internal function for gpg completion code deduplication" -a __fish_complete_gpg2_command
    complete -c $__fish_complete_gpg2_command -l no-keyring -d "Do not use any keyring at all"
    complete -c $__fish_complete_gpg2_command -l no-skip-hidden-recipients -d "During decryption, do not skip all anonymous recipients"
    complete -c $__fish_complete_gpg2_command -l only-sign-text-ids -d "Exclude any non-text-based user ids from selection for signing"
    complete -c $__fish_complete_gpg2_command -l override-session-key-fd -x -d "Don't use the public key but the specified session key"
    complete -c $__fish_complete_gpg2_command -l passwd -xa "(__fish_complete_gpg_user_id)" -d "Change the passphrase of the secret key belonging to the given user id"
    complete -c $__fish_complete_gpg2_command -l pinentry-mode -xa "default ask cancel error loopback" -d "Set the pinentry mode"
    complete -c $__fish_complete_gpg2_command -l quick-add-key -xa "(__fish_complete_gpg_key_id)" -d "Directly add a subkey to a key"
    complete -c $__fish_complete_gpg2_command -l quick-add-uid -xa "(__fish_complete_gpg_user_id)" -d "Adds a new user id to an existing key"
    complete -c $__fish_complete_gpg2_command -l quick-gen-key -xa "(__fish_complete_gpg_user_id)" -d "Generate a standard key without needing to answer prompts"
    complete -c $__fish_complete_gpg2_command -l quick-generate-key -xa "(__fish_complete_gpg_user_id)" -d "Generate a standard key without needing to answer prompts"
    complete -c $__fish_complete_gpg2_command -l quick-lsign-key -xa "(__fish_complete_gpg_key_id)" -d "Directly sign a key from the passphrase; marks signatures as non-exportable"
    complete -c $__fish_complete_gpg2_command -l quick-revoke-uid -xa "(__fish_complete_gpg_user_id)" -d "Revokes a user id on an existing key"
    complete -c $__fish_complete_gpg2_command -l quick-revuid -xa "(__fish_complete_gpg_user_id)" -d "Revokes a user id on an existing key"
    complete -c $__fish_complete_gpg2_command -l quick-set-expire -xa "(__fish_complete_gpg_key_id)" -d "Set the expiration time of the specified key"
    complete -c $__fish_complete_gpg2_command -l quick-set-primary-uid -xa "(__fish_complete_gpg_user_id)" -d "Sets or updates the priary uid flag for the specified key"
    complete -c $__fish_complete_gpg2_command -l quick-sign-key -xa "(__fish_complete_gpg_key_id)" -d "Directly sign a key from the passphrase"
    complete -c $__fish_complete_gpg2_command -l receive-keys -xa "(__fish_complete_gpg_key_id)" -d "Import the keys with the given key IDs from a keyserver"
    complete -c $__fish_complete_gpg2_command -s f -l recipient-file -r -d "Similar to --recipient, but encrypts to key stored in file instead"
    complete -c $__fish_complete_gpg2_command -l request-origin -r -d "Tell gpg to assume that the operation ultimately originated at a particular origin"
    complete -c $__fish_complete_gpg2_command -l sender -xa "(__fish_complete_gpg_user_id)" -d "When creating a signature, tells gpg the user id of a key; when verifying, used to restrict information printed"
    complete -c $__fish_complete_gpg2_command -l show-keys -d "Take OpenPGP keys as input and print information about them"
    complete -c $__fish_complete_gpg2_command -l skip-hidden-recipients -d "During decryption, skip all anonymous recipients"
    complete -c $__fish_complete_gpg2_command -l tofu-default-policy -xa "auto good unknown bad ask" -d "Set the default TOFU policy"
    complete -c $__fish_complete_gpg2_command -l tofu-policy -xa "auto good unknown bad ask" -d "Set the default TOFU policy for the specified keys"
    complete -c $__fish_complete_gpg2_command -l try-secret-key -xa "(__fish_complete_gpg_key_id)" -d "Specify keys to be used for trial decryption"

    complete -c $__fish_complete_gpg2_command -l with-icao-spelling -d "Print the ICAO spelling of the fingerprint in addition to the hex digits"
    complete -c $__fish_complete_gpg2_command -l with-key-origin -d "Include the locally held information on the origin and last update of a key in a key listing"
    complete -c $__fish_complete_gpg2_command -l with-keygrip -d "Include the keygrip in the key listings"
    complete -c $__fish_complete_gpg2_command -l with-secret -d "Include info about the presence of a secret key in public key listings done with --with-colons"
    complete -c $__fish_complete_gpg2_command -l no-symkey-cache -d "Disable the passphrase cache used for symmetrical en- and decryption"
    complete -c $__fish_complete_gpg2_command -l no-autostart -d "Do not start the gpg-agent or the dirmngr if it has not been started and its service is required"
    complete -c $__fish_complete_gpg2_command -l log-file -r -d "Write log output to the specified file"
    complete -c $__fish_complete_gpg2_command -l locate-keys -d "Locate the keys given as arguments"
    complete -c $__fish_complete_gpg2_command -l locate-external-keys -d "Locate they keys given as arguments; do not consider local keys"
    complete -c $__fish_complete_gpg2_command -l list-signatures -xa "(__fish_complete_gpg_user_id)" -d "Same as --list-keys, but the signatures are listed too"
    complete -c $__fish_complete_gpg2_command -l list-gcrypt-config -d "Display various internal configuration parameters of libgcrypt"
    complete -c $__fish_complete_gpg2_command -l known-notation -r -d "Tell GnuPG about a critical signature notation"
    complete -c $__fish_complete_gpg2_command -l key-origin -d "Track the origin of a key"
    complete -c $__fish_complete_gpg2_command -l input-size-hint -r -d "Specify input size in bytes"
    complete -c $__fish_complete_gpg2_command -s F -l hidden-recipient-file -r -d "Similar to --hidden-recipient, but encrypts to key stored in file instead"
    complete -c $__fish_complete_gpg2_command -l generate-revocation -xa "(__fish_complete_gpg_user_id)" -d "Generate a revocation certificate for the complete key"
    complete -c $__fish_complete_gpg2_command -l generate-key -d "Generate a new key pair"
    complete -c $__fish_complete_gpg2_command -l generate-designated-revocation -xa "(__fish_complete_gpg_user_id)" -d "Generate a designated revocation certificate for a key"
    complete -c $__fish_complete_gpg2_command -l full-gen-key -d "Generate a new key pair with dialogs for all options"
    complete -c $__fish_complete_gpg2_command -l full-generate-key -d "Generate a new key pair with dialogs for all options"
    complete -c $__fish_complete_gpg2_command -l export-filter -d "Define an import/export filter to apply to an imported/exported keyblock before it is written"
    complete -c $__fish_complete_gpg2_command -l import-filter -d "Define an import/export filter to apply to an imported/exported keyblock before it is written"
    complete -c $__fish_complete_gpg2_command -l edit-card -d "Present a menu to work with a smartcard"
    complete -c $__fish_complete_gpg2_command -l card-edit -d "Present a menu to work with a smartcard"
    complete -c $__fish_complete_gpg2_command -l disable-signer-uid -d "Don't embed the uid of the signing key in the data signature"
    complete -c $__fish_complete_gpg2_command -l disable-dirmngr -d "Entirely disable the use of the Dirmngr"
    complete -c $__fish_complete_gpg2_command -l dirmngr-program -r -d "Specify a dirmngr program to be used for keyserver access"
    complete -c $__fish_complete_gpg2_command -l default-new-key-algo -x -d "Change the default algorothms for key generation"
    complete -c $__fish_complete_gpg2_command -l compliance -xa "gnupg openpgp rfc4880 rfc4880bis rfc2440 pgp6 pgp7 pgp8" -d "Set a compliance standard for GnuPG"
    complete -c $__fish_complete_gpg2_command -l change-passphrase -xa "(__fish_complete_gpg_user_id)" -d "Change the passphrase of the secret key belonging to the given user id"
    complete -c $__fish_complete_gpg2_command -l agent-program -d "Specify an agent program to be used for secret key operations"
    complete -c $__fish_complete_gpg2_command -l clear-sign -d "Make a clear text signature"
end
