
#apt-build
complete -c apt-build -l help -d "apt-build command help"
complete -f -c apt-build -a update -d "update list of packages"
complete -f -c apt-build -a upgrade -d "upgrade packages"
complete -f -c apt-bulid -a world -d "rebuild your system"
complete -x -c apt-build -a install -d "build and install a new pkg"
complete -x -c apt-build -a source -d "download and extract a src"
complete -x -c apt-build -a info -d "info on a pkg"
complete -x -c apt-build -a remove -d "remove packages"
complete -x -c apt-build -a clean-build -d "erase built pkgs"
complete -x -c apt-build -a build-source -d "build src without install"
complete -x -c apt-build -a clean-sources -d "clean src dirs"
complete -x -c apt-build -a update-source -d "update src and rebuild them"
complete -x -c apt-build -a update-repository -d "update the repository"
complete -f -c apt-build -l nowrapper -d "do not use gcc wrapper"
complete -f -c apt-build -l remove-builddep -d "remove build-dep"
complete -f -c apt-build -l no-source -d "do not download source"
complete -f -c apt-build -l build-dir -d "specify build-dir"
complete -f -c apt-build -l rebuild -d "rebuild a package"
complete -f -c apt-build -l reinstall -d "rebuild and install an installed pkg"
complete -r -f -c apt-build -l build-command -d "use <command> to build"
complete -r -c apt-build -l patch -d "apply <file> patch"
complete -c apt-build -s p -l patch-strip -d "prefix to strip on patch"
complete -c apt-build -s y -l yes -d "assume yes"
complete -c apt-build -l purge -d "use purge instead of remove"
complete -c apt-build -l noupdate -d "do not run update"
complete -r -c apt-build -l source-list -d "specify sources.list file"
complete -f -c apt-build -s v -l version -d "show version"
