#apt-spy
complete -c apt-spy -s h -d (_ "Display help and exit")
complete -f -c apt-spy -s d -a "stable testing unstable" -d (_ "Debian distribution")
complete -f -c apt-spy -s a -a "Africa Asia Europe North-America Oceania South-America" -d (_ "Servers in the areas")
complete -c apt-spy -s c -d (_ "Conf file")
complete -f -c apt-spy -s e -d (_ "Finish after number of servers")
complete -c apt-spy -s f -d (_ "File to grab servers")
complete -c apt-spy -s i -d (_ "File as input")
complete -c apt-spy -s m -d (_ "Mirror-list file")
complete -c apt-spy -s o -d (_ "Output sources.list file")
complete -f -c apt-spy -s p -d (_ "Use proxy server")
complete -f -c apt-spy -s s -d (_ "Comma separated country list")
complete -f -c apt-spy -s t -d (_ "How long in sec to download")
complete -f -c apt-spy -s u -d (_ "Custom URL to get mirror list")
complete -c apt-spy -s w -d (_ "Write top servers to file")
complete -f -c apt-spy -s n -d (_ "Number of top servers")
complete -f -c apt-spy -a "update" -d (_ "Update mirror list")
complete -f -c apt-spy -s v -d (_ "Version number")


