
#apt-build
complete -c apt-build -l help -d (_ "Display help and exit")
complete -f -c apt-build -a update -d (_ "Update list of packages")
complete -f -c apt-build -a upgrade -d (_ "Upgrade packages")
complete -f -c apt-bulid -a world -d (_ "Rebuild your system")
complete -x -c apt-build -a install -d (_ "Build and install a new package")
complete -x -c apt-build -a source -d (_ "Download and extract a source")
complete -x -c apt-build -a info -d (_ "Info on a package")
complete -x -c apt-build -a remove -d (_ "Remove packages")
complete -x -c apt-build -a clean-build -d (_ "Erase built packages")
complete -x -c apt-build -a build-source -d (_ "Build source without install")
complete -x -c apt-build -a clean-sources -d (_ "Clean source directories")
complete -x -c apt-build -a update-source -d (_ "Update source and rebuild")
complete -x -c apt-build -a update-repository -d (_ "Update the repository")
complete -f -c apt-build -l nowrapper -d (_ "Do not use gcc wrapper")
complete -f -c apt-build -l remove-builddep -d (_ "Remove build-dep")
complete -f -c apt-build -l no-source -d (_ "Do not download source")
complete -f -c apt-build -l build-dir -d (_ "Specify build-dir")
complete -f -c apt-build -l rebuild -d (_ "Rebuild a package")
complete -f -c apt-build -l reinstall -d (_ "Rebuild and install an installed package")
complete -r -f -c apt-build -l build-command -d (_ "Use <command> to build")
complete -r -c apt-build -l patch -d (_ "Apply <file> patch")
complete -c apt-build -s p -l patch-strip -d (_ "Prefix to strip on patch")
complete -c apt-build -s y -l yes -d (_ "Assume yes to all questions")
complete -c apt-build -l purge -d (_ "Use purge instead of remove")
complete -c apt-build -l noupdate -d (_ "Do not run update")
complete -r -c apt-build -l source-list -d (_ "Specify sources.list file")
complete -f -c apt-build -s v -l version -d (_ "Display version and exit")
