#apt-cache
complete -c apt-cache -s h -l help -d (_ "Display help and exit")
complete -f -c apt-cache -a gencaches -d (_ "Build apt cache")
complete -x -c apt-cache -a showpkg -d (_ "Show package info")
complete -f -c apt-cache -a stats -d (_ "Show cache statistics")
complete -x -c apt-cache -a showsrc -d (_ "Show source package")
complete -f -c apt-cache -a dump -d (_ "Show packages in cache")
complete -f -c apt-cache -a dumpavail -d (_ "Print available list")
complete -f -c apt-cache -a unmet -d (_ "List unmet dependencies in cache")
complete -x -c apt-cache -a show -d (_ "Display package record")
complete -x -c apt-cache -a search -d (_ "Search packagename by REGEX")
complete -c apt-cache -l full -a search -d (_ "Search full package name")
complete -x -c apt-cache -l names-only -a search -d (_ "Search packagename only")
complete -x -c apt-cache -a depends -d (_ "List dependencies for the package")
complete -x -c apt-cache -a rdepends -d (_ "List reverse dependencies for the package")
complete -x -c apt-cache -a pkgnames -d (_ "Print package name by prefix")
complete -x -c apt-cache -a dotty -d (_ "Generate dotty output for packages")
complete -x -c apt-cache -a policy -d (_ "Debug preferences file")
complete -r -c apt-cache -s p -l pkg-cache -d (_ "Select file to store package cache")
complete -r -c apt-cache -s s -l src-cache -d (_ "Select file to store source cache")
complete -f -c apt-cache -s q -l quiet -d (_ "Quiet mode")
complete -f -c apt-cache -s i -l important -d (_ "Print important dependencies")
complete -f -c apt-cache -s a -l all-versions -d (_ "Print full records")
complete -f -c apt-cache -s g -l generate -d (_ "Auto-gen package cache")
complete -f -c apt-cache -l all-names -d (_ "Print all names")
complete -f -c apt-cache -l recurse -d (_ "Dep and rdep recursive")
complete -f -c apt-cache -l installed -d (_ "Limit to installed")
complete -f -c apt-cache -s v -l version -d (_ "Display version and exit")
complete -r -c apt-cache -s c -l config-file -d (_ "Specify config file")
complete -x -c apt-cache -s o -l option -d (_ "Specify options")

