#apt-file
complete -c apt-file -s h -l help -d (_ "Display help and exit")
complete -x -c apt-file -a update -d (_ "Resync package contents from source")
complete -r -c apt-file -a search -d (_ "Search package containing pattern")
complete -r -c apt-file -a list -d (_ "List contents of a package matching pattern")
complete -x -c apt-file -a purge -d (_ "Remove all gz files from cache")
complete -r -c apt-file -s c -l cache -d (_ "Set cache dir")
complete -f -c apt-file -s v -l verbose -d (_ "Verbose mode")
complete -c apt-file -s d -l cdrom-mount -d (_ "Use cdrom-mount-point")
complete -f -c apt-file -s i -l ignore-case -d (_ "Do not expand pattern")
complete -f -c apt-file -s x -l regexp -d (_ "Pattern is regexp")
complete -f -c apt-file -s V -l version -d (_ "Display version and exit")
complete -f -c apt-file -s a -l architecture -d (_ "Set arch")
complete -r -c apt-file -s s -l sources-list -a "(ls /etc/apt)" -d (_ "Set sources.list file")
complete -f -c apt-file -s l -l package-only -d (_ "Only display package name")
complete -f -c apt-file -s F -l fixed-string -d (_ "Do not expand pattern")
complete -f -c apt-file -s y -l dummy -d (_ "Run in dummy mode")
