#apt-move
complete -c apt-move -a get -d (_ "Generate master file")
complete -c apt-move -a getlocal -d (_ "Alias of get")
complete -f -c apt-move -a move -d (_ "Move pkgs to local tree")
complete -f -c apt-move -a delete -d (_ "Delete obsolete pkg files")
complete -f -c apt-move -a packages -d (_ "Build new local files")
complete -f -c apt-move -a fsck -d (_ "Rebuild index files")
complete -f -c apt-move -a update -d (_ "Move pkgs from cache to local mirror")
complete -f -c apt-move -a local -d (_ "Alias to move delete packages")
complete -f -c apt-move -a localupdate -d (_ "Alias for update")
complete -f -c apt-move -a mirror -d (_ "Download pkg missing from mirror")
complete -f -c apt-move -a sync -d (_ "Sync pkgs installed")
complete -f -c apt-move -a exclude -d 'test $LOCALDIR/.exclude file'
complete -c apt-move -a movefile -d (_ "Move file from CLI")
complete -f -c apt-move -a listbin -d (_ "Mirror|sync|repo")
complete -f -c apt-move -a mirrorbin -d (_ "Fetch pkg from STDIN")
complete -f -c apt-move -a mirrorsrc -d (_ "Fetch src pkg from STDIN")
complete -f -c apt-move -s a -d (_ "Process all pkgs")
complete -c apt-move -s c -d (_ "Use specific conffile")
complete -f -c apt-move -s d -d (_ "Use specific dist")
complete -f -c apt-move -s f -d (_ "Force deletion")
complete -f -c apt-move -s q -d (_ "Suppresses normal output")
complete -f -c apt-move -s t -d (_ "Test run")
