#apt-src
complete -c apt-src -s h -l help -d "apt-src command help"
complete -f -c apt-src -a "update" -d "update list of src pkgs"
complete -f -c apt-src -a "install" -d "install src pkgs"
complete -f -c apt-src -a "upgrade" -d "upgrade src pkgs"
complete -f -c apt-src -a "remove" -d "remove src pkgs"
complete -f -c apt-src -a "build" -d "build src pkgs"
complete -f -c apt-src -a "clean" -d "clean src pkgs"
complete -f -c apt-src -a "import" -d "detect known src tree"
complete -f -c apt-src -a "list" -d "list installed src pkg\(s\)"
complete -f -c apt-src -a "location" -d "root src tree"
complete -f -c apt-src -a "version" -d "version of src pkg"
complete -f -c apt-src -a "name" -d "name of the src pkg"
complete -f -c apt-src -s b -l build -d "build src pkgs"
complete -f -c apt-src -s i -l installdebs -d "install after build"
complete -f -c apt-src -s p -l patch -d "patch local changes"
complete -r -c apt-src -s l -l location -d "specify a dir"
complete -c apt-src -s c -l here -d "run on current dir"
complete -f -c apt-src -l upstream-version -d "omit debian version"
complete -f -c apt-src -s k -l keep-built -d "do not del built files"
complete -f -c apt-src -s n -l no-delete-source -d "do not del source files"
complete -f -c apt-src -l version -d "source tree version"
complete -f -c apt-src -s q -l quiet -d "output to /dev/null"
complete -f -c apt-src -s t -l trace -d "output trace"
