#apt-file
complete -c apt-file -s h -l help -d "apt-file command help"
complete -x -c apt-file -a update -d "resync pkg contents from source"
complete -r -c apt-file -a search -d "search pkg containing pattern"
complete -r -c apt-file -a list -d "list contents of a pkg matching pattern"
complete -x -c apt-file -a purge -d "remove all gz files from cache"
complete -r -c apt-file -s c -l cache -d "set cache dir"
complete -f -c apt-file -s v -l verbose -d "run in verbose"
complete -c apt-file -s d -l cdrom-mount -d "use cdrom-mount-point"
complete -f -c apt-file -s i -l ignore-case -d "do not expand pattern"
complete -f -c apt-file -s x -l regexp -d "pattern is regexp"
complete -f -c apt-file -s V -l version -d "show version"
complete -f -c apt-file -s a -l architecture -d "set arch"
complete -r -c apt-file -s s -l sources-list -a "(ls /etc/apt)" -d "set sources.list file"
complete -f -c apt-file -s l -l package-only -d "only display pkg name"
complete -f -c apt-file -s F -l fixed-string -d "do not expand pattern"
complete -f -c apt-file -s y -l dummy -d "run in dummy mode"
