#apt-listbugs
complete -c apt-listbugs -s h -l help -d (_ "Apt-listbugs command help")
complete -f -c apt-listbugs -s s -l severity -a "critical grave"  -d (_ "Set severity")
complete -f -c apt-listbugs -s T -l tag -d (_ "Targs you want to see")
complete -f -c apt-listbugs -s S -l stats -d (_ "Outstanding 'pending upload' resolved done open") -d "status you want to see"
complete -f -c apt-listbugs -s l -l showless -d (_ "Ignore bugs in your system")
complete -f -c apt-listbugs -s g -l showgreater -d (_ "Ignore newer bugs than upgrade pkgs")
complete -f -c apt-listbugs -s D -l show-downgrade -d (_ "Bugs for downgrade pkgs")
complete -f -c apt-listbugs -s H -l hostname -a "osdn.debian.or.jp" -d (_ "Bug Tracking system")
complete -f -c apt-listbugs -s p -l port -d (_ "Specify port for web interface")
complete -f -c apt-listbugs -s R -l release-critical -d (_ "Use daily bug report")
complete -f -c apt-listbugs -s I -l index -d (_ "Use the raw index.db")
complete -f -c apt-listbugs -s X -l indexdir -d (_ "Specify index dir")
complete -f -c apt-listbugs -s P -l pin-priority -d (_ "Specify Pin-Priority value")
complete -f -c apt-listbugs -l title -d (_ "Specify the title of rss")
complete -f -c apt-listbugs -s f -l force-download -d (_ "Retrieve fresh bugs")
complete -f -c apt-listbugs -s q -l quiet -d (_ "Do not display progress bar")
complete -f -c apt-listbugs -s c -l cache-dir -a "/var/cache/apt-listbugs/" -d (_ "Specify local cache dir")
complete -f -c apt-listbugs -s t -l timer -d (_ "Specify the expire cache timer")
complete -c apt-listbugs -s C -l aptconf -d (_ "Specify apt config file")
complete -f -c apt-listbugs -s y -l force-yes -d (_ "Assume all yes")
complete -f -c apt-listbugs -s n -l force-no -d (_ "Assume all no")
complete -c apt-listbugs -a list -d (_ "List bugs from pkgs")
complete -c apt-listbugs -a rss -d (_ "List bugs in rss format")

