complete -c cut -s b -l bytes -x -d (_ "Output byte range")
complete -c cut -s c -l characters -x -d (_ "Output character range")
complete -c cut -s d -l delimiter -x -d (_ "Select field delimiter")
complete -c cut -s d -l fields -x -d (_ "Select fields")
complete -c cut -s n -d (_ "Dont split mutibyte characters")
complete -c cut -s s -l only-delimited -d (_ "Do not print lines without delimiter")
complete -c cut -l output-delimiter -d (_ "Select output delimiter")
complete -c cut -l help -d (_ "Display help and exit")
complete -c cut -l version -d (_ "Display version and exit")

