#
# I don't use CVS, so these completions are probably not all that good.
#

complete -c cvs -x -a "add" -d "Add a new file/directory to the repository"
complete -c cvs -x -a "admin" -d "Administration front end for rcs"
complete -c cvs -x -a "annotate" -d "Show last revision where each line was modified"
complete -c cvs -x -a "checkout" -d "Checkout sources for editing"
complete -c cvs -x -a "commit" -d "Check files into the repository"
complete -c cvs -x -a "diff" -d "Show differences between revisions"
complete -c cvs -x -a "edit" -d "Get ready to edit a watched file"
complete -c cvs -x -a "editors" -d "See who is editing a watched file"
complete -c cvs -x -a "export" -d "Export sources from CVS, similar to checkout"
complete -c cvs -x -a "history" -d "Show repository access history"
complete -c cvs -x -a "import" -d "Import sources into CVS, using vendor branches"
complete -c cvs -x -a "init" -d "Create a CVS repository if it doesnt exist"
complete -c cvs -x -a "kserver" -d "Kerberos server mode"
complete -c cvs -x -a "log" -d "Print out history information for files"
complete -c cvs -x -a "login" -d "Prompt for password for authenticating server"
complete -c cvs -x -a "logout" -d "Removes entry in .cvspass for remote repository"
complete -c cvs -x -a "pserver" -d "Password server mode"
complete -c cvs -x -a "rannotate" -d "Show last revision where each line of module was modified"
complete -c cvs -x -a "rdiff" -d "Create 'patch' format diffs between releases"
complete -c cvs -x -a "release" -d "Indicate that a Module is no longer in use"
complete -c cvs -x -a "remove" -d "Remove an entry from the repository"
complete -c cvs -x -a "rlog" -d "Print out history information for a module"
complete -c cvs -x -a "rtag" -d "Add a symbolic tag to a module"
complete -c cvs -x -a "server" -d "Server mode"
complete -c cvs -x -a "status" -d "Display status information on checked out files"
complete -c cvs -x -a "tag" -d "Add a symbolic tag to checked out version of files"
complete -c cvs -x -a "unedit" -d "Undo an edit command"
complete -c cvs -x -a "update" -d "Bring work tree in sync with repository"
complete -c cvs -x -a "version" -d "Show current CVS version(s)"
complete -c cvs -x -a "watch" -d "Set watches"
complete -c cvs -x -a "watchers" -d "See who is watching a file"

complete -c cvs -x -s H -d "Displays usage information for command"
complete -c cvs -x -s Q -d "Cause CVS to be really quiet"
complete -c cvs -x -s q -d "Cause CVS to be somewhat quiet"
complete -c cvs -x -s r -d "Make checked-out files read-only"
complete -c cvs -x -s w -d "Make checked-out files read-write (default)"
complete -c cvs -x -s n -d "Do not execute anything that will change the disk"
complete -c cvs -x -s t -d "Show trace of program execution -- try with -n"
complete -c cvs -x -s v -d "CVS version and copyright"
complete -c cvs -x -s T -r -d "Use 'tmpdir' for temporary files"
complete -c cvs -x -s e -r -d "Use 'editor' for editing log information"
complete -c cvs -x -s d -r -d "Overrides $CVSROOT as the root of the CVS tree"
complete -c cvs -x -s f -d "Do not use the ~/.cvsrc file"
complete -c cvs -x -s z -d "Compression level for net traffic" -x -a "1 2 3 4 5 6 7 8 9"
complete -c cvs -x -s x -d "Encrypt all net traffic"
complete -c cvs -x -s a -d "Authenticate all net traffic"
complete -c cvs -x -s s -d "Set CVS user variable" -x

