#
# I don't use CVS, so these completions are probably not all that good.
#

complete -c cvs -x -a 'add' -d (_ "Add a new file/directory to the repository")
complete -c cvs -x -a 'admin' -d (_ "Administration front end for rcs")
complete -c cvs -x -a 'annotate' -d (_ "Show last revision where each line was modified")
complete -c cvs -x -a 'checkout' -d (_ "Checkout sources for editing")
complete -c cvs -x -a 'commit' -d (_ "Check files into the repository")
complete -c cvs -x -a 'diff' -d (_ "Show differences between revisions")
complete -c cvs -x -a 'edit' -d (_ "Get ready to edit a watched file")
complete -c cvs -x -a 'editors' -d (_ "See who is editing a watched file")
complete -c cvs -x -a 'export' -d (_ "Export sources from CVS, similar to checkout")
complete -c cvs -x -a 'history' -d (_ "Show repository access history")
complete -c cvs -x -a 'import' -d (_ "Import sources into CVS, using vendor branches")
complete -c cvs -x -a 'init' -d (_ "Create a CVS repository if it doesnt exist")
complete -c cvs -x -a 'kserver' -d (_ "Kerberos server mode")
complete -c cvs -x -a 'log' -d (_ "Print out history information for files")
complete -c cvs -x -a 'login' -d (_ "Prompt for password for authenticating server")
complete -c cvs -x -a 'logout' -d (_ "Removes entry in .cvspass for remote repository")
complete -c cvs -x -a 'pserver' -d (_ "Password server mode")
complete -c cvs -x -a 'rannotate' -d (_ "Show last revision where each line of module was modified")
complete -c cvs -x -a 'rdiff' -d (_ "Create "patch" format diffs between releases")
complete -c cvs -x -a 'release' -d (_ "Indicate that a Module is no longer in use")
complete -c cvs -x -a 'remove' -d (_ "Remove an entry from the repository")
complete -c cvs -x -a 'rlog' -d (_ "Print out history information for a module")
complete -c cvs -x -a 'rtag' -d (_ "Add a symbolic tag to a module")
complete -c cvs -x -a 'server' -d (_ "Server mode")
complete -c cvs -x -a 'status' -d (_ "Display status information on checked out files")
complete -c cvs -x -a 'tag' -d (_ "Add a symbolic tag to checked out version of files")
complete -c cvs -x -a 'unedit' -d (_ "Undo an edit command")
complete -c cvs -x -a 'update' -d (_ "Bring work tree in sync with repository")
complete -c cvs -x -a 'version' -d (_ "Display version and exit")
complete -c cvs -x -a 'watch' -d (_ "Set watches")
complete -c cvs -x -a 'watchers' -d (_ "See who is watching a file")

complete -c cvs -x -s H -d (_ "Displays usage information for command")
complete -c cvs -x -s Q -d (_ "Cause CVS to be really quiet")
complete -c cvs -x -s q -d (_ "Cause CVS to be somewhat quiet")
complete -c cvs -x -s r -d (_ "Make checked-out files read-only")
complete -c cvs -x -s w -d (_ "Make checked-out files read-write (default)")
complete -c cvs -x -s n -d (_ "Do not change any files")
complete -c cvs -x -s t -d (_ "Show trace of program execution -- try with -n")
complete -c cvs -x -s v -d (_ "Display version and exit")
complete -c cvs -x -s T -r -d (_ "Use "tmpdir" for temporary files")
complete -c cvs -x -s e -r -d (_ "Use "editor" for editing log information")
complete -c cvs -x -s d -r -d (_ "Overrides $CVSROOT as the root of the CVS tree")
complete -c cvs -x -s f -d (_ "Do not use the ~/.cvsrc file")
complete -c cvs -x -s z -d (_ "Compression level for net traffic") -x -a '1 2 3 4 5 6 7 8 9'
complete -c cvs -x -s x -d (_ "Encrypt all net traffic")
complete -c cvs -x -s a -d (_ "Authenticate all net traffic")
complete -c cvs -x -s s -d (_ "Set CVS user variable") -x

