complete -c echo -s n -d (_ "No newline")
complete -c echo -s e -d (_ "Use backslash escaped characters")
complete -c echo -s E -d (_ "Do not use backslash escaped characters")
complete -c echo -l help -d (_ "Display help and exit")
complete -c echo -l version -d (_ "Display version and exit")
