complete -c mimedb -s t -l input-file-data -d "Input is a file, use name and contents to determine mimetype"
complete -c mimedb -s f -l input-filename -d "Input is a file, use name to determine mimetype"
complete -c mimedb -s i -l input-mime -d "Input is a mimetype"
complete -c mimedb -s m -l output-mime -d "Output mimetype"
complete -c mimedb -s d -l output-description -d "Output description of mimetype"
complete -c mimedb -s a -l output-action -d "Output default action for mimetype"
complete -c mimedb -s l -l launch -d "Launch default action for each file"
complete -c mimedb -s h -l help -d "Display help and exit"
complete -c mimedb -s v -l version -d "Display version and exit"
