complete -c perl -s 0 -d 'Specify record separator'
complete -c perl -s a -d 'Feed input to split'
complete -c perl -s c -d 'Check syntax'
complete -c perl -s d -d 'Debugger'
complete -c perl -s D -x -d 'Debug option'
complete -c perl -s e -x -d 'Execute command'
complete -c perl -s F -d 'Set regexp used to split input'
complete -c perl -s i -d 'Edit files in-place'
complete -c perl -s I -d 'Include path'
complete -c perl -s l -d 'Line ending processing'
complete -c perl -s n -d 'Loop script'
complete -c perl -s p -d 'Loop script, print $_'
complete -c perl -s P -d 'Invoke CPP'
complete -c perl -s s -d 'Define custom switches'
complete -c perl -s S -d 'Search $PATH for script'
complete -c perl -s T -d 'Taint checking'
complete -c perl -s U -d 'Unsafe mode'
complete -c perl -s v -d 'Display version'
complete -c perl -s x -d 'Extract script'

