complete -c python -s c -x -d "Execute argument as command"
complete -c python -s d -d "Debug on"
complete -c python -s E -d "Ignore environment variables"
complete -c python -s h -d "Display help and exit"
complete -c python -s i -d "Interactive mode after executing commands"
complete -c python -s O -d "Enable optimizations"
complete -c python -s Q -x -a "old new" -d "Division control"
complete -c python -s S -d "Disable import of site module"
complete -c python -s t -d "Warn on mixed tabs and spaces"
complete -c python -s u -d "Unbuffered inputg and output"
complete -c python -s v -d "Verbose mode"
complete -c python -s V -d "Display version and exit"
complete -c python -s W -x -d "Warning control" -a "ignore default all module once error"
complete -c python -s x -d "Skip first line of input"
