complete -c python -s c -x -d (_ "Execute argument as command")
complete -c python -s d -d (_ "Debug on")
complete -c python -s E -d (_ "Ignore environment variables")
complete -c python -s h -d (_ "Display help and exit")
complete -c python -s i -d (_ "Interactive mode after executing commands")
complete -c python -s O -d (_ "Enable optimizations")
complete -c python -s Q -x -a "old new" -d (_ "Division control")
complete -c python -s S -d (_ "Disable import of site module")
complete -c python -s t -d (_ "Warn on mixed tabs and spaces")
complete -c python -s u -d (_ "Unbuffered input and output")
complete -c python -s v -d (_ "Verbose mode")
complete -c python -s V -d (_ "Display version and exit")
complete -c python -s W -x -d (_ "Warning control") -a "ignore default all module once error"
complete -c python -s x -d (_ "Ignore first line of input")
