complete -c sed -s n -l quiet -d "Silent mode"
complete -c sed -l silent -d "Silent mode"
complete -c sed -s e -l expression -x -d "Evaluate expression"
complete -c sed -s f -l file -r -d "Evalute file"
complete -c sed -s i -l in-place -d "Edit files in place"
complete -c sed -s l -l line-length -x -d "Specify line-length"
complete -c sed -l posix -d "Disable all GNU extensions"
complete -c sed -s r -l regexp-extended -d "Use extended regexp"
complete -c sed -s s -l separate -d "Consider files as separate"
complete -c sed -s u -l unbuffered -d "Use minimal IO buffers"
complete -c sed -l help -d "Display help and exit"
complete -c sed -s V -l version -d "Display version and exit"
