complete -c touch -s a -d "Change access time"
complete -c touch -s B -l backward -x -d "Set date back"
complete -c touch -s c -l no-create -d "Do not create file"
complete -c touch -s d -l date -x -d "Set date"
complete -c touch -s f -l forward -x -d "Set date forward"
complete -c touch -s m -d "Change modification time"
complete -c touch -s r -l reference -d "Use this files times"
complete -c touch -s t -d "Set date"
complete -c touch -l time -x -d "Set time"
complete -c touch -l help -d "Display help and exit"
complete -c touch -l version -d "Display version nd exit"
