complete -c uname -s a -l all -d (_ "Print all information")
complete -c uname -s s -l kernel-name -d (_ "Print kernel name")
complete -c uname -s n -l nodename -d (_ "Print network node hostname")
complete -c uname -s r -l kernel-release -d (_ "Print kernel release")
complete -c uname -s v -l kernel-version -d (_ "Print kernel version")
complete -c uname -s m -l machine -d (_ "Print machine name")
complete -c uname -s p -l processor -d (_ "Print processor")
complete -c uname -s i -l hardware-platform -d (_ "Print hardware platform")
complete -c uname -s o -l operating-system -d (_ "Print operating system")
complete -c uname -l help -d (_ "Display help and exit")
complete -c uname -l verion -d (_ "Display version and exit")
