pub(crate) const RESERVED_CHAR_BASE: u32 = 0xFDD0;
pub(crate) const RESERVED_CHAR_END: u32 = 0xFDF0;
pub(crate) const EXPAND_RESERVED_BASE: u32 = RESERVED_CHAR_BASE;
pub(crate) const EXPAND_RESERVED_END: u32 = EXPAND_RESERVED_BASE + 16;
pub(crate) const WILDCARD_RESERVED_BASE: u32 = EXPAND_RESERVED_END;
pub(crate) const WILDCARD_RESERVED_END: u32 = WILDCARD_RESERVED_BASE + 16;
