env:
    CIRRUS_CLONE_DEPTH: 100
    CI: 1

linux_task:
    matrix:
        - name: alpine
          container: &step
              image: ghcr.io/krobelus/fish-ci/alpine:latest
              memory: 4GB
        - name: jammy
          container:
              <<: *step
              image: ghcr.io/krobelus/fish-ci/jammy:latest
        # - name: jammy-asan
        #   container:
        #       <<: *step
        #       image: ghcr.io/krobelus/fish-ci/jammy-asan:latest
        # - name: focal-32bit
        #   container:
        #       <<: *step
        #       image: ghcr.io/krobelus/fish-ci/focal-32bit:latest
    tests_script:
        # cirrus at times gives us 32 procs and 2 GB of RAM
        # Unrestriced parallelism results in OOM
        - lscpu || true
        - (cat /proc/meminfo | grep MemTotal) || true
        - mkdir build && cd build
        - FISH_TEST_MAX_CONCURRENCY=6 cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
        - ninja -j 6 fish
        - ninja fish_run_tests
    only_if: $CIRRUS_REPO_OWNER == 'fish-shell'

linux_arm_task:
    matrix:
        - name: focal-arm64
          arm_container:
              image: ghcr.io/fish-shell/fish-ci/focal-arm64
        - name: jammy-armv7-32bit
          arm_container:
              image: ghcr.io/fish-shell/fish-ci/jammy-armv7-32bit
    tests_script:
        # cirrus at times gives us 32 procs and 2 GB of RAM
        # Unrestriced parallelism results in OOM
        - lscpu || true
        - (cat /proc/meminfo | grep MemTotal) || true
        - mkdir build && cd build
        - FISH_TEST_MAX_CONCURRENCY=6 cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
        - ninja -j 6 fish
        - file ./fish
        - ninja fish_run_tests
    # CI task disabled during RIIR transition
    only_if: false && $CIRRUS_REPO_OWNER == 'fish-shell'

freebsd_task:
    matrix:
        - name: FreeBSD 14
          freebsd_instance:
              image: freebsd-14-3-release-amd64-ufs
    tests_script:
        - pkg install -y cmake-core devel/pcre2 devel/ninja lang/rust misc/py-pexpect git-lite
        # libclang.so is a required build dependency for rust-c++ ffi bridge
        - pkg install -y llvm
        # BSDs have the following behavior: root may open or access files even if
        # the mode bits would otherwise disallow it. For example root may open()
        # a file with write privileges even if the file has mode 400. This breaks
        # our tests for e.g. cd and path. So create a new unprivileged user to run tests.
        - pw user add -n fish-user -s /bin/csh -d /home/fish-user
        - mkdir -p /home/fish-user
        - chown -R fish-user /home/fish-user
        - mkdir build && cd build
        - chown -R fish-user ..
        - sudo -u fish-user -s whoami
        - sudo -u fish-user -s FISH_TEST_MAX_CONCURRENCY=1 cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
        - sudo -u fish-user -s ninja -j 6 fish
        - sudo -u fish-user -s ninja fish_run_tests
    only_if: $CIRRUS_REPO_OWNER == 'fish-shell'
