.TH PCRE2_SET_NEWLINE 3 "22 October 2014" "PCRE2 10.00"
.SH NAME
PCRE2 - Perl-compatible regular expressions (revised API)
.SH SYNOPSIS
.rs
.sp
.B #include <pcre2.h>
.PP
.nf
.B int pcre2_set_newline(pcre2_compile_context *\fIccontext\fP,
.B "  uint32_t \fIvalue\fP);"
.fi
.
.SH DESCRIPTION
.rs
.sp
This function sets the newline convention within a compile context. This
specifies which character(s) are recognized as newlines when compiling and
matching patterns. The second argument must be one of:
.sp
  PCRE2_NEWLINE_CR        Carriage return only
  PCRE2_NEWLINE_LF        Linefeed only
  PCRE2_NEWLINE_CRLF      CR followed by LF only
  PCRE2_NEWLINE_ANYCRLF   Any of the above
  PCRE2_NEWLINE_ANY       Any Unicode newline sequence
.sp
The result is zero for success or PCRE2_ERROR_BADDATA if the second argument is
invalid.
.P
There is a complete description of the PCRE2 native API in the
.\" HREF
\fBpcre2api\fP
.\"
page and a description of the POSIX API in the
.\" HREF
\fBpcre2posix\fP
.\"
page.
