.TH PCRE2_GENERAL_CONTEXT_CREATE 3 "22 October 2014" "PCRE2 10.00"
.SH NAME
PCRE2 - Perl-compatible regular expressions (revised API)
.SH SYNOPSIS
.rs
.sp
.B #include <pcre2.h>
.PP
.nf
.B pcre2_general_context *pcre2_general_context_create(
.B "  void *(*\fIprivate_malloc\fP)(PCRE2_SIZE, void *),"
.B "  void (*\fIprivate_free\fP)(void *, void *), void *\fImemory_data\fP);"
.fi
.
.SH DESCRIPTION
.rs
.sp
This function creates and initializes a general context. The arguments define
custom memory management functions and a data value that is passed to them when
they are called. The \fBprivate_malloc()\fP function is used to get memory for
the context. If either of the first two arguments is NULL, the system memory
management function is used. The result is NULL if no memory could be obtained.
.P
There is a complete description of the PCRE2 native API in the
.\" HREF
\fBpcre2api\fP
.\"
page and a description of the POSIX API in the
.\" HREF
\fBpcre2posix\fP
.\"
page.
