argparse-exclusive-flag-invalid = exclusive flag '{ $flag }' is not valid
argparse-exclusive-flag-string-invalid = exclusive flag string '{ $flag_string }' is not valid
argparse-implicit-int-flag-already-defined = Implicit int flag '{ $flag }' already defined
argparse-invalid-option-spec = Invalid option spec '{ $option_spec }' at char '{ $bad_char }'
command-not-found = Unknown command '{ $cmd }': { $reason }
command-not-found-catchall = The file exists but cannot be executed. Error: { $err }.
eacces-modified = Missing execute permissions for the file or one of its parent directories.
eisdir = File is a directory.
eloop = Too many levels of symbolic links. Maybe a loop?
emfile = Too many open files in this process.
enametoolong = File name is too long.
enfile = Too many open files on the system.
enoexec-modified = Files of this type cannot be executed.
enomem = Out of memory.
enotdir = One of the parent files is not a directory.
enotdir-on-PATH = One of the parent files is not a directory. Check your $PATH.
eperm = No permission. Either suid/sgid is forbidden or you lack capabilities.
etxtbsy = File is currently open for writing
fish-version = { $package_name }, version { $version }
test-with-args = Two arguments: { $first }, { $second }
