argparse-exclusive-flag-invalid = exclusive flag '{ $flag }' is not valid
argparse-exclusive-flag-string-invalid = exclusive flag string '{ $flag_string }' is not valid
argparse-implicit-int-flag-already-defined = Implicit int flag '{ $flag }' already defined
argparse-invalid-option-spec = Invalid option spec '{ $option_spec }' at char '{ $bad_char }'
command-not-found-catchall = Unknown command. '{ $cmd }' exists but cannot be executed. Error: { $errno }.
command-not-found-eacces = Unknown command. Missing execute permissions for '{ $cmd }' or one of its parent directories.
command-not-found-eloop = Unknown command. '{ $cmd }': Too many levels of symbolic links.
command-not-found-enametoolong = Unknown command. '{ $cmd }': File name too long.
command-not-found-enoexec = Unknown command. '{ $cmd }' exists, but files of this type cannot be executed.
command-not-found-enotdir = Unknown command. A component of '{ $cmd }' is not a directory.
command-not-found-enotdir-on-PATH = Unknown command. A component of '{ $cmd }' is not a directory. Check your $PATH.
command-not-found-unknown-errno = Unknown command. '{ $cmd }' exists but cannot be executed. Error: unknown.
fish-version = { $package_name }, version { $version }
test-with-args = Two arguments: { $first }, { $second }
