name: Install sphinx-markdown-builder

permissions:
  contents: read

runs:
  using: "composite"
  steps:
    - run: |
        pip install git+https://github.com/krobelus/sphinx-markdown-builder@ae8cf577bfb263dcda509ad449a331b9b74664fa
      shell: bash
