name: Install sphinx-markdown-builder

permissions:
  contents: read

runs:
  using: "composite"
  steps:
    - run: |
        commit=a6dd85e7b13107172c0502937bec6b718002510d
        pip install git+https://github.com/krobelus/sphinx-markdown-builder@"$commit"
      shell: bash
