name: Install sphinx-markdown-builder

permissions:
  contents: read

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -x
        commit=b259de1dc97573a71470a1d71c3d83535934136b
        pip install git+https://github.com/krobelus/sphinx-markdown-builder@"$commit"
        python -c 'import sphinx_markdown_builder'
