name: Install sphinx-markdown-builder

permissions:
  contents: read

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -x
        commit=7c4daaf39a92f93deec948ecc1772e23bac44588
        pip install git+https://github.com/liran-funaro/sphinx-markdown-builder@"$commit"
        python -c 'import sphinx_markdown_builder'
