[package]
name = "fish-build-helper"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
rsconf.workspace = true

[lints]
workspace = true
