complete -c abbr -f -s a -l add -d 'Add abbreviation'
complete -c abbr -s e -l erase -d 'Erase abbreviation' -xa '(abbr -s | cut -d" " -f 2- | sed -e "s/ /	/")'
complete -c abbr -f -s s -l show -d 'Print all abbreviations'
complete -c abbr -f -s l -l list -d 'Print all abbreviation names'
complete -c abbr -f -s h -l help -d 'Help'
