complete -c abbr -f -s a -l add -d 'Add abbreviation'
complete -c abbr -s r -l remove -d 'Remove abbreviation' -xa '(abbr -l)'
complete -c abbr -f -s s -l show -d 'Print all abbreviations'
complete -c abbr -f -s l -l list -d 'Print all abbreviation names'
complete -c abbr -f -s h -l help -d 'Help'
