complete -c ansible-playbook -l ask-vault-pass -f -d "Ask for vault password"
complete -c ansible-playbook -s C -l check -f -d "Just check, don't make any changes"
complete -c ansible-playbook -s D -l diff -f -d "Show the differences in files and templates; works great with --check"
complete -c ansible-playbook -s e -l extra-vars -r -d "Set additional variables as key=value or YAML/JSON"
complete -c ansible-playbook -l flush-cache -d "Clear the fact cache"
complete -c ansible-playbook -l force-handlers -d "Run handlers even if a task fails"
complete -c ansible-playbook -s f -l forks -a "(seq 0 100)" -d "Number of parallel processes to use (default=5)"
complete -c ansible-playbook -s h -l help -d "Shows a help message"
complete -c ansible-playbook -s i -l inventory -r -d "Specify inventory host path (default=/etc/ansible/hosts) or comma separated host list."
complete -c ansible-playbook -s l -l limit -r -d "Further limit selected hosts to an additional pattern"
complete -c ansible-playbook -l list-hosts -d "List all matching hosts"
complete -c ansible-playbook -l list-tags -d "List all available tags"
complete -c ansible-playbook -l list-tasks -d "List all tasks that would be executed"
complete -c ansible-playbook -s M -l module-path -r -d "Specify path(s) to module library (default=None)"
complete -c ansible-playbook -l new-vault-password-file -f -d "New vault password file for rekey"
complete -c ansible-playbook -l output -f -d "Output file name for encrypt or decrypt; use - for stdout"
complete -c ansible-playbook -l skip-tags -r -d "Only run plays and tasks whose tags do not match these values"
complete -c ansible-playbook -l start-at-task -r -d "Start the playbook at the task matching this name"
complete -c ansible-playbook -l step -d "Confirm each task before running"
complete -c ansible-playbook -l syntax-check -f -d "Perform a syntax check on the playbook"
complete -c ansible-playbook -s t -l tags -r -f -d "Only run plays and tasks tagged with these values"
complete -c ansible-playbook -l vault-password-file -d "Vault password file"
complete -c ansible-playbook -s v -l verbose -f -d "Verbose mode (-vvv for more, -vvvv to enable connection debugging)"
complete -c ansible-playbook -l version -f -d "Display version and exit"
complete -c ansible-playbook -s k -l ask-pass -f -d "Ask for connection password"
complete -c ansible-playbook -l private-key -r -d "Use this file to authenticate the connection"
complete -c ansible-playbook -s u -l user -f -a "(__fish_complete_users)" -d "Connect as this user (default=None)"
complete -c ansible-playbook -s c -l connection -f -d "Connection type to use (default=smart)"
complete -c ansible-playbook -s T -l timeout -f -d "Set the connection timeout in seconds (default=10)"
complete -c ansible-playbook -l ssh-common-args -f -d "Specify common arguments to pass to sftp/scp/ssh"
complete -c ansible-playbook -l sftp-extra-args -f -d "Specify extra arguments to pass to sftp only"
complete -c ansible-playbook -l scp-extra-args -f -d "Specify extra arguments to pass to scp only"
complete -c ansible-playbook -l ssh-extra-args -f -d "Specify extra arguments to pass to ssh only"
complete -c ansible-playbook -s b -l become -f -d "Run operations with become (does not imply password prompting)"
complete -c ansible-playbook -l become-method -r -f -a "sudo su pbrun pfexec runas doas dzdo" -d "Privilege escalation method to use (default=sudo)"
complete -c ansible-playbook -l become-user -r -f -a "(__fish_complete_users)" -d "Run operations as this user (default=root)"
complete -c ansible-playbook -s K -l ask-become-pass -f -d "Ask for privilege escalation password"
