#apt-src
complete -c apt-src -s h -l help --description "Display help and exit"
complete -f -c apt-src -a "update" --description "Update list of source packages"
complete -f -c apt-src -a "install" --description "Install source packages"
complete -f -c apt-src -a "upgrade" --description "Upgrade source packages"
complete -f -c apt-src -a "remove" --description "Remove source packages"
complete -f -c apt-src -a "build" --description "Build source packages"
complete -f -c apt-src -a "clean" --description "Clean source packages"
complete -f -c apt-src -a "import" --description "Detect known source tree"
complete -f -c apt-src -a "list" --description "List installed source package\(s\)"
complete -f -c apt-src -a "location" --description "Root source tree"
complete -f -c apt-src -a "version" --description "Version of source package"
complete -f -c apt-src -a "name" --description "Name of the source package"
complete -f -c apt-src -s b -l build --description "Build source packages"
complete -f -c apt-src -s i -l installdebs --description "Install after build"
complete -f -c apt-src -s p -l patch --description "Patch local changes"
complete -r -c apt-src -s l -l location --description "Specify a dir"
complete -c apt-src -s c -l here --description "Run on current dir"
complete -f -c apt-src -l upstream-version --description "Omit debian version"
complete -f -c apt-src -s k -l keep-built --description "Do not del built files"
complete -f -c apt-src -s n -l no-delete-source --description "Do not del source files"
complete -f -c apt-src -l version --description "Source tree version"
complete -f -c apt-src -s q -l quiet --description "Output to /dev/null"
complete -f -c apt-src -s t -l trace --description "Output trace"
