#apt-listbugs
complete -c apt-listbugs -s h -l help -d (N_ "Display help and exit")
complete -f -c apt-listbugs -s s -l severity -a "critical grave"  -d (N_ "Set severity")
complete -f -c apt-listbugs -s T -l tag -d (N_ "Tags you want to see")
complete -f -c apt-listbugs -s S -l stats -a "outstanding 'pending upload' resolved done open" -d (N_ "Bug-status you want to see")
complete -f -c apt-listbugs -s l -l showless -d (N_ "Ignore bugs in your system")
complete -f -c apt-listbugs -s g -l showgreater -d (N_ "Ignore newer bugs than upgrade packages")
complete -f -c apt-listbugs -s D -l show-downgrade -d (N_ "Bugs for downgrade packages")
complete -f -c apt-listbugs -s H -l hostname -a "osdn.debian.or.jp" -d (N_ "Bug Tracking system")
complete -f -c apt-listbugs -s p -l port -d (N_ "Specify port for web interface")
complete -f -c apt-listbugs -s R -l release-critical -d (N_ "Use daily bug report")
complete -f -c apt-listbugs -s I -l index -d (N_ "Use the raw index.db")
complete -f -c apt-listbugs -s X -l indexdir -d (N_ "Specify index dir")
complete -f -c apt-listbugs -s P -l pin-priority -d (N_ "Specify Pin-Priority value")
complete -f -c apt-listbugs -l title -d (N_ "Specify the title of rss")
complete -f -c apt-listbugs -s f -l force-download -d (N_ "Retrieve fresh bugs")
complete -f -c apt-listbugs -s q -l quiet -d (N_ "Do not display progress bar")
complete -f -c apt-listbugs -s c -l cache-dir -a "/var/cache/apt-listbugs/" -d (N_ "Specify local cache dir")
complete -f -c apt-listbugs -s t -l timer -d (N_ "Specify the expire cache timer")
complete -c apt-listbugs -s C -l aptconf -d (N_ "Specify apt config file")
complete -f -c apt-listbugs -s y -l force-yes -d (N_ "Assume yes to all questions")
complete -f -c apt-listbugs -s n -l force-no -d (N_ "Assume no to all questions")
complete -c apt-listbugs -a list -d (N_ "List bugs from packages")
complete -c apt-listbugs -a rss -d (N_ "List bugs in rss format")

