#apt-cdrom
complete -c apt-cdrom -s h -l help -d (_ "Display help and exit")
complete -r -c apt-cdrom -a add -d (_ "Add new disc to source list")
complete -x -c apt-cdrom -a ident -d (_ "Report identity of disc")
complete -r -c apt-cdrom -s d -l cdrom -d (_ "Mount point")
complete -f -c apt-cdrom -s r -l rename -d (_ "Rename a disc")
complete -f -c apt-cdrom -s m -l no-mount -d (_ "No mounting")
complete -f -c apt-cdrom -s f -l fast -d (_ "Fast copy")
complete -f -c apt-cdrom -s a -l thorough -d (_ "Thorough package scan")
complete -f -c apt-cdrom -s n -l no-act -d (_ "No changes")
complete -f -c apt-cdrom -s v -l version -d (_ "Display version and exit")
complete -r -c apt-cdrom -s c -l config-file -d (_ "Specify config file")
complete -x -c apt-cdrom -s o -l option -d (_ "Specify options")
