#apt-ftparchive
complete -c apt-ftparchive -s h -l help --description "Display help and exit"
complete -f -c apt-ftparchive -a packages --description "Generate package from source"
complete -f -c apt-ftparchive -a sources --description "Generate source index file"
complete -f -c apt-ftparchive -a contents --description "Generate contents file"
complete -f -c apt-ftparchive -a release --description "Generate release file"
complete -f -c apt-ftparchive -a clean --description "Remove records"
complete -f -c apt-ftparchive -l md5 --description "Generate MD5 sums"
complete -f -c apt-ftparchive -s d -l db --description "Use a binary db"
complete -f -c apt-ftparchive -s q -l quiet --description "Quiet mode"
complete -f -c apt-ftparchive -l delink --description "Perform delinking"
complete -f -c apt-ftparchive -l contents --description "Perform contents generation"
complete -c apt-ftparchive -s s -l source-override --description "Use source override"
complete -f -c apt-ftparchive -l readonly --description "Make caching db readonly"
complete -f -c apt-ftparchive -s v -l version --description "Display version and exit"
complete -r -c apt-ftparchive -s c -l config-file --description "Use config file"
complete -r -c apt-ftparchive -s o -l option --description "Set config options"
