#apt-build
complete -c apt-build -l help -d "Display help and exit"
complete -f -c apt-build -a update -d "Update list of packages"
complete -f -c apt-build -a upgrade -d "Upgrade packages"
complete -f -c apt-build -a world -d "Rebuild your system"
complete -x -c apt-build -a install -d "Build and install a new package"
complete -x -c apt-build -a source -d "Download and extract a source"
complete -x -c apt-build -a info -d "Info on a package"
complete -x -c apt-build -a remove -d "Remove packages"
complete -x -c apt-build -a clean-build -d "Erase built packages"
complete -x -c apt-build -a build-source -d "Build source without install"
complete -x -c apt-build -a clean-sources -d "Clean source directories"
complete -x -c apt-build -a update-source -d "Update source and rebuild"
complete -x -c apt-build -a update-repository -d "Update the repository"
complete -f -c apt-build -l nowrapper -d "Do not use gcc wrapper"
complete -f -c apt-build -l remove-builddep -d "Remove build-dep"
complete -f -c apt-build -l no-source -d "Do not download source"
complete -f -c apt-build -l build-dir -d "Specify build-dir"
complete -f -c apt-build -l rebuild -d "Rebuild a package"
complete -f -c apt-build -l reinstall -d "Rebuild and install an installed package"
complete -r -f -c apt-build -l build-command -d "Use <command> to build"
complete -r -c apt-build -l patch -d "Apply <file> patch"
complete -c apt-build -s p -l patch-strip -d "Prefix to strip on patch"
complete -c apt-build -s y -l yes -d "Assume yes to all questions"
complete -c apt-build -l purge -d "Use purge instead of remove"
complete -c apt-build -l noupdate -d "Do not run update"
complete -r -c apt-build -l source-list -d "Specify sources.list file"
complete -f -c apt-build -s v -l version -d "Display version and exit"
