complete -c atom -s d -l dev -d 'Run in development mode'
complete -c atom -s f -l foreground -d 'Keep main process in foreground'
complete -c atom -s h -l help -d 'Print usage message'
complete -c atom -s l -l log-file -r -d 'Log all output to file'
complete -c atom -s n -l new-window -d 'Open a new window'
complete -c atom -l profile-startup -d 'Profile startup execution time'
complete -c atom -s r -l resource-path -r -d 'Set Atom source directory and enable dev mode'
complete -c atom -l safe -d 'Run in safe mode'
complete -c atom -l benchmark -d 'Run the specified benchmarks in a new window'
complete -c atom -l benchmark-test -d 'Run a faster version of the benchmarks in headless mode'
complete -c atom -s t -l test -d 'Run the specified specs and exit with error code on failures'
complete -c atom -s m -l main-process -d 'Run the specified specs in the main process'
complete -c atom -l timeout -r -d 'Set timeout for test mode (minutes)'
complete -c atom -s v -l version -d 'Print the version information'
complete -c atom -s w -l wait -d 'Wait for editor to be closed before returning'
complete -c atom -l clear-window-state -d 'Delete all Atom environment state'
complete -c atom -l enable-electron-logging -d 'Enable low-level logging messages from Electron'
complete -c atom -s a -l add -d 'Open path as a new project in last used window'
