complete -c black -s c -l code -d 'Format the code passed in as a string'
complete -c black -s l -l line-length -d 'How many characters per line to allow [default: 88]'
complete -c black -s t -l target-version -d 'Python versions that should be supported by Black\'s output [default: per-file auto-detection]'
complete -c black -l pyi -d 'Format all input files like typing stubs regardless of file extension'
complete -c black -s S -l skip-string-normalization -d 'Don\'t normalize string quotes or prefixes'
complete -c black -s C -l skip-magic-trailing-comma -d 'Don\'t use trailing commas as a reason to split lines'
complete -c black -l check -d 'Don\'t write the files back, just return the status'
complete -c black -l diff -d 'Don\'t write the files back, just output a diff for each file on stdout'
complete -c black -l color -d 'Show colored diff. Only applies when `--diff` is given'
complete -c black -l no-color -d 'Do not show colored diff. Only applies when `--diff` is given'
complete -c black -l fast -d 'Skip temporary sanity checks. [default: --safe]'
complete -c black -l safe -d 'Do not skip temporary sanity checks [default]'
complete -c black -l required-version -d 'Require a specific version of Black to be running'
complete -c black -l include -d 'A regular expression that matches files and directories that should be included on recursive searches [default: \.pyi?$]'
complete -c black -l exclude -d 'A regular expression that matches files and directories that should be excluded on recursive searches [default: /(\.direnv|\.eggs|\.git|\.h g|\.mypy_cache|\.nox|\.tox|\.venv|venv|\.svn |_build|buck-lut|build|dist)/]'
complete -c black -l extend-exclude -d 'Like --exclude, but adds additional files and directories on top of the excluded ones'
complete -c black -l force-exclude -d 'Like --exclude, but files and directories matching this regex will be excluded even when they are passed explicitly as arguments'
complete -c black -l stdin-filename -d 'The name of the file when passing it through stdin'
complete -c black -s q -l quiet -d 'Don\'t emit non-error messages to stderr. Errors are still emitted; silence those with 2>/dev/null'
complete -c black -s v -l verbose -d 'Also emit messages to stderr about files that were not changed or were ignored due to exclusion patterns'
complete -c black -l version -d 'Show the version and exit'
complete -c black -l config -d 'Read configuration from FILE path'
complete -c black -s h -l help -d 'Show this message and exit'
