#
# Command specific completions for the bzr command.
# These completions were generated from the commands
# man page by the make_completions.py script, but may
# have been hand edited since.
#

complete -c bzr -l dry-run --description 'Show what would be done, but don\'t actually do anything'
complete -c bzr -l file-ids-from --description 'ARG Lookup file ids from this tree'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l no-recurse --description 'Don\'t recursively add the contents of directories'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l dry-run --description 'Will show which files would be added, but not actually add them'
complete -c bzr -l file-ids-from --description 'Will try to use the file ids from the supplied path'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l remove --description 'Remove the alias'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l all --description 'Show annotations on all lines'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l long --description 'Show commit date in annotations'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l show-ids --description 'Show internal object ids'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l bind --description 'Bind new branch to from location'
complete -c bzr -l files-from --description 'ARG Get file contents from this tree'
complete -c bzr -l hardlink --description 'Hard-link working tree files where possible'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l no-tree --description 'Create a branch without a working-tree'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l stacked --description 'Create a stacked branch referring to the source branch'
complete -c bzr -l standalone --description 'Do not use a shared repository, even if available'
complete -c bzr -l switch --description 'Switch the checkout in the current directory to the new branch'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l use-existing-dir --description 'By default branch will fail if the target directory exists, but does not already have a control directory'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l recursive -s R --description 'Recursively scan for branches rather than just looking in the specified location'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l config --description 'LOCATION is the directory where the config lock is'
complete -c bzr -l force --description 'Do not ask for confirmation before breaking the lock'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l filters --description 'Apply content filters to display the convenience form'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l name-from-revision --description 'The path name in the old tree'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l branch --description 'Check the branch related to the current directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l repo --description 'Check the repository related to the current directory'
complete -c bzr -l tree --description 'Check the working tree related to the current directory'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l files-from --description 'ARG Get file contents from this tree'
complete -c bzr -l hardlink --description 'Hard-link working tree files where possible'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l lightweight --description 'Perform a lightweight checkout'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l detritus --description 'Delete conflict files, merge and revert backups, and failed selftest dirs'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l dry-run --description 'Show files to delete instead of deleting them'
complete -c bzr -l force --description 'Do not prompt before deleting'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l ignored --description 'Delete all ignored files'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l unknown --description 'Delete files unknown to bzr (default)'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l author --description 'ARG Set the author\'s name, if it\'s different from the committer'
complete -c bzr -l commit-time --description 'ARG Manually set a commit time using commit date format, e'
complete -c bzr -l exclude --description 'ARG, -x Do not consider changes made to a given path'
complete -c bzr -l file --description 'MSGFILE, -F Take commit message from this file'
complete -c bzr -l fixes --description 'ARG Mark a bug as being fixed by this revision (see "bzr help bugs")'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l local --description 'Perform a local commit in a bound branch'
complete -c bzr -l lossy --description 'When committing to a foreign version control system do not push data that can not be natively represented'
complete -c bzr -l message --description 'ARG, -m Description of the new revision'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l show-diff -s p --description 'When no message is supplied, show the diff along with the status summary in the message editor'
complete -c bzr -l strict --description 'Refuse to commit if there are unknown files in the working tree'
complete -c bzr -l unchanged --description 'Commit even if nothing has changed'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l show-diff --description 'Option'
complete -c bzr -l all --description 'Display all the defined values for the matching options'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l remove --description 'Remove the option from the configuration file'
complete -c bzr -l scope --description 'ARG Reduce the scope to the specified configuration file'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l text --description 'List paths of files with text conflicts'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l show-ids --description 'Show internal object ids'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l change --description 'ARG, -c Select changes introduced by the specified revision'
complete -c bzr -l diff-options --description 'ARG Pass these options to the external diff program'
complete -c bzr -l format --description 'ARG, -F Diff format to use'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l new --description 'ARG Branch/tree to compare to'
complete -c bzr -l old --description 'ARG Branch/tree to compare from'
complete -c bzr -l prefix --description 'ARG, -p Set prefixes added to old and new filenames, as two values separated by a colon'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l using --description 'ARG Use this command to compare files'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l directory --description 'ARG, -d Branch to push from, rather than the one containing the working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l no-rebase --description 'Do not rebase after push'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l remember --description 'Remember the specified location as a default'
complete -c bzr -l strict --description 'Refuse to push if there are uncommitted changes in the working tree, --no-strict disables the check'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l filters --description 'Apply content filters to export the convenient form'
complete -c bzr -l format --description 'ARG Type of file to export to'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l per-file-timestamps --description 'Set modification time of files to that of the last revision in which it was changed'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l root --description 'ARG Name of the root directory inside the exported file'
complete -c bzr -l uncommitted --description 'Export the working tree contents rather than that of the last revision'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l long --description 'Show help on all commands'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l default-rules --description 'Display the default ignore rules that bzr uses'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l append-revisions-only --description 'Never change revnos or the existing log'
complete -c bzr -l create-prefix --description 'Create the path leading up to the branch if it does not already exist'
complete -c bzr -l format --description 'ARG Specify a format for this branch'
complete -c bzr -l 2a --description 'Format for the bzr 2'
complete -c bzr -l default --description 'Format for the bzr 2'
complete -c bzr -l development-colo --description 'The 2a format with experimental support for colocated branches'
complete -c bzr -l pack-0.92 --description 'Pack-based format used in 1'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l no-tree --description 'Create a branch without a working tree'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l format --description 'ARG Specify a format for this repository'
complete -c bzr -l 2a --description 'Format for the bzr 2'
complete -c bzr -l default --description 'Format for the bzr 2'
complete -c bzr -l development-colo --description 'The 2a format with experimental support for colocated branches'
complete -c bzr -l pack-0.92 --description 'Pack-based format used in 1'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l no-trees --description 'Branches in the repository will default to not having a working tree'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l authors --description 'ARG What names to list as authors - first, all or committer'
complete -c bzr -l change --description 'ARG, -c Show just the specified revision'
complete -c bzr -l exclude-common-ancestry --description 'Display only the revisions that are not part of both ancestries (require -rX'
complete -c bzr -l forward --description 'Show from oldest to newest'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l include-merged --description 'Show merged revisions like --levels 0 does'
complete -c bzr -l levels --description 'N, -n Number of levels to display - 0 for all, 1 for flat'
complete -c bzr -l limit --description 'N, -l Limit the output to the first N revisions'
complete -c bzr -l log-format --description 'ARG Use specified log format'
complete -c bzr -l gnu-changelog --description 'Format used by GNU ChangeLog files'
complete -c bzr -l line --description 'Log format with one line per revision'
complete -c bzr -l long --description 'Detailed log format'
complete -c bzr -l short --description 'Moderately short log format'
complete -c bzr -l match --description 'ARG, -m Show revisions whose properties match this expression'
complete -c bzr -l match-author --description 'ARG Show revisions whose authors match this expression'
complete -c bzr -l match-bugs --description 'ARG Show revisions whose bugs match this expression'
complete -c bzr -l match-committer --description 'ARG Show revisions whose committer matches this expression'
complete -c bzr -l match-message --description 'ARG Show revisions whose message matches this expression'
complete -c bzr -l omit-merges --description 'Do not report commits with more than one parent'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l show-diff -s p --description 'Show changes made in each revision as a patch'
complete -c bzr -l show-ids --description 'Show internal object ids'
complete -c bzr -l signatures --description 'Show digital signature validity'
complete -c bzr -l timezone --description 'ARG Display timezone as local, original, or utc'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Show files changed in each revision'
complete -c bzr -s l --description 'N display a maximum of N revisions -n N display N levels of revisions (0 for all, 1 for collapsed) -v display a status summary (delta) for each revision -p display a diff (patch) for each revision --show-ids display revision-ids (and file-ids), not just revnos'
complete -c bzr -o rX --description 'Display revision X -rX'
complete -c bzr -o r..Y --description 'Display up to and including revision Y -rX'
complete -c bzr -o r-1 --description 'Show just the tip -r-10'
complete -c bzr -o rsubmit:.. --description 'Show what\'s new on this branch -rancestor:path'
complete -c bzr -o rdate:yesterday.. --description 'Show changes since yesterday'
complete -c bzr -l match-message --description 'Can be used to only match a specific field'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l from-root --description 'Print paths relative to the root of the branch'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l ignored -s i --description 'Print ignored files'
complete -c bzr -l kind --description 'ARG, -k List entries of a particular kind: file, directory, symlink'
complete -c bzr -l null -s 0 --description 'Use an ASCII NUL (\0) separator rather than a newline'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l recursive -s R --description 'Recurse into subdirectories'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l show-ids --description 'Show internal object ids'
complete -c bzr -l unknown -s u --description 'Print unknown files'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l versioned -s V --description 'Print versioned files'
complete -c bzr -l change --description 'ARG, -c Select changes introduced by the specified revision'
complete -c bzr -l directory --description 'ARG, -d Branch to merge into, rather than the one containing the working directory'
complete -c bzr -l force --description 'Merge even if the destination tree has uncommitted changes'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l interactive -s i --description 'Select changes interactively'
complete -c bzr -l merge-type --description 'ARG Select a particular merge algorithm'
complete -c bzr -l diff3 --description 'Merge using external diff3'
complete -c bzr -l lca --description 'LCA-newness merge'
complete -c bzr -l merge3 --description 'Native diff3-style merge'
complete -c bzr -l weave --description 'Weave-based merge'
complete -c bzr -l preview --description 'Instead of merging, show a diff of the merge'
complete -c bzr -l pull --description 'If the destination is already completely merged into the source, pull from the source rather than merging'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l remember --description 'Remember the specified location as a default'
complete -c bzr -l reprocess --description 'Reprocess to reduce spurious conflicts'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l show-base --description 'Show base revision text in conflicts'
complete -c bzr -l uncommitted --description 'Apply uncommitted changes from a working copy, instead of branch changes'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l include-merged --description 'Show all revisions in addition to the mainline ones'
complete -c bzr -l log-format --description 'ARG Use specified log format'
complete -c bzr -l gnu-changelog --description 'Format used by GNU ChangeLog files'
complete -c bzr -l line --description 'Log format with one line per revision'
complete -c bzr -l long --description 'Detailed log format'
complete -c bzr -l short --description 'Moderately short log format'
complete -c bzr -l mine-only --description 'Display changes in the local branch only'
complete -c bzr -l my-revision --description 'ARG Filter on local branch revisions (inclusive)'
complete -c bzr -l other --description 'Same as --theirs-only'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l reverse --description 'Reverse the order of revisions'
complete -c bzr -l revision --description 'ARG, -r Filter on other branch revisions (inclusive)'
complete -c bzr -l show-ids --description 'Show internal object ids'
complete -c bzr -l theirs-only --description 'Display changes in the remote branch only'
complete -c bzr -l this --description 'Same as --mine-only'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l parents -s p --description 'No error if existing, make parent directories as needed'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l after --description 'Move only the bzr identifier of the file, because the file has already been moved'
complete -c bzr -l auto --description 'Automatically guess renames'
complete -c bzr -l dry-run --description 'Avoid making changes when guessing renames'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l clean-obsolete-packs --description 'Delete obsolete packs to save disk space'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l verbose --description 'Shows the path where each plugin is located'
complete -c bzr -l directory --description 'ARG, -d Branch to pull into, rather than the one containing the working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l local --description 'Perform a local pull in a bound branch'
complete -c bzr -l overwrite --description 'Ignore differences between branches and overwrite unconditionally'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l remember --description 'Remember the specified location as a default'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l show-base --description 'Show base revision text in conflicts'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Show logs of pulled revisions'
complete -c bzr -l create-prefix --description 'Create the path leading up to the branch if it does not already exist'
complete -c bzr -l directory --description 'ARG, -d Branch to push from, rather than the one containing the working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l no-tree --description 'Don\'t populate the working tree, even for protocols that support it'
complete -c bzr -l overwrite --description 'Ignore differences between branches and overwrite unconditionally'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l remember --description 'Remember the specified location as a default'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l stacked --description 'Create a stacked branch that references the public location of the parent branch'
complete -c bzr -l stacked-on --description 'ARG Create a stacked branch that refers to another branch for the commit history'
complete -c bzr -l strict --description 'Refuse to push if there are uncommitted changes in the working tree, --no-strict disables the check'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l use-existing-dir --description 'By default push will fail if the target directory exists, but does not already have a control directory'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l bind-to --description 'ARG Branch to bind checkout to'
complete -c bzr -l force --description 'Perform reconfiguration even if local changes will be lost'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l repository_trees --description 'ARG Whether new branches in the repository have trees'
complete -c bzr -l with-no-trees --description 'Reconfigure repository to not create working trees on branches by default'
complete -c bzr -l with-trees --description 'Reconfigure repository to create working trees on branches by default'
complete -c bzr -l repository_type --description 'ARG Location fo the repository'
complete -c bzr -l standalone --description 'Reconfigure to be a standalone branch (i'
complete -c bzr -l use-shared --description 'Reconfigure to use a shared repository'
complete -c bzr -l stacked-on --description 'ARG Reconfigure a branch to be stacked on another branch'
complete -c bzr -l tree_type --description 'ARG The relation between branch and tree'
complete -c bzr -l branch --description 'Reconfigure to be an unbound branch with no working tree'
complete -c bzr -l checkout --description 'Reconfigure to be a bound branch with a working tree'
complete -c bzr -l lightweight-checkout --description 'Reconfigure to be a lightweight checkout (with no local history)'
complete -c bzr -l tree --description 'Reconfigure to be an unbound branch with a working tree'
complete -c bzr -l unstacked --description 'Reconfigure a branch to be unstacked'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l merge-type --description 'ARG Select a particular merge algorithm'
complete -c bzr -l diff3 --description 'Merge using external diff3'
complete -c bzr -l lca --description 'LCA-newness merge'
complete -c bzr -l merge3 --description 'Native diff3-style merge'
complete -c bzr -l weave --description 'Weave-based merge'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l reprocess --description 'Reprocess to reduce spurious conflicts'
complete -c bzr -l show-base --description 'Show base revision text in conflicts'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l file-deletion-strategy --description 'ARGThe file deletion mode to be used'
complete -c bzr -l force --description 'Delete all the specified files, even if they can not be recovered and even if they are non-empty directories'
complete -c bzr -l keep --description 'Delete from bzr but leave the working copy'
complete -c bzr -l no-backup --description 'Don\'t backup changed files'
complete -c bzr -l safe --description 'Backup changed files (default)'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l new --description 'Only remove files that have never been committed'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l force --description 'Remove branch even if it is the active branch'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l force --description 'Remove the working tree even if it has uncommitted or shelved changes'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l action --description 'ARG How to resolve the conflict'
complete -c bzr -l done --description 'Marks the conflict as resolved'
complete -c bzr -l take-other --description 'Resolve the conflict taking the merged version into account'
complete -c bzr -l take-this --description 'Resolve the conflict preserving the version in the working tree'
complete -c bzr -l all --description 'Resolve all conflicts in this tree'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l forget-merges --description 'Remove pending merge marker, without changing any files'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l no-backup --description 'Do not save backups of reverted files'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l tree --description 'Show revno of working tree'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l body --description 'ARG Body for the email'
complete -c bzr -l format --description 'ARG Use the specified output format'
complete -c bzr -l from --description 'ARG, -f Branch to generate the submission from, rather than the one containing the working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l mail-to --description 'ARG Mail the request to this address'
complete -c bzr -l message --description 'ARG, -m Message string'
complete -c bzr -l no-bundle --description 'Do not include a bundle in the merge directive'
complete -c bzr -l no-patch --description 'Do not include a preview patch in the merge directive'
complete -c bzr -l output --description 'ARG, -o Write merge directive to this file or directory; use - for stdout'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l remember --description 'Remember submit and public branch'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l strict --description 'Refuse to send if there are uncommitted changes in the working tree, --no-strict disables the check'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l allow-writes --description 'By default the server is a readonly server'
complete -c bzr -l client-timeout --description 'ARG Override the default idle client timeout (5min)'
complete -c bzr -l directory --description 'ARG, -d Serve contents of this directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l inet --description 'Serve on stdin/out for use from inetd or sshd'
complete -c bzr -l port --description 'ARG Listen for connections on nominated port of the form [hostname:]portnumber'
complete -c bzr -l protocol --description 'ARG Protocol to serve'
complete -c bzr -l bzr --description 'The Bazaar smart server protocol over TCP'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l all --description 'Shelve all changes'
complete -c bzr -l destroy --description 'Destroy removed changes instead of shelving them'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l list --description 'List shelved changes'
complete -c bzr -l message --description 'ARG, -m Message string'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l writer --description 'ARG Method to use for writing diffs'
complete -c bzr -l plain --description 'Plaintext diff output'
complete -c bzr -l dry-run --description 'Don\'t actually sign anything, just print the revisions that would be signed'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l change --description 'ARG, -c Select changes introduced by the specified revision'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l no-classify --description 'Do not mark object type using indicator'
complete -c bzr -l no-pending --description 'Don\'t show pending merges'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l short -s S --description 'Use short status indicators'
complete -c bzr -l show-ids --description 'Show internal object ids'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l versioned -s V --description 'Only show versioned files'
complete -c bzr -l create-branch -s b --description 'Create the target branch from this one before switching to it'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l force --description 'Switch even if local commits will be lost'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l delete --description 'Delete this tag rather than placing it'
complete -c bzr -l directory --description 'ARG, -d Branch in which to place the tag'
complete -c bzr -l force --description 'Replace existing tags'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l delete --description 'Oldname``'
complete -c bzr -l directory --description 'ARG, -d Branch whose tags should be displayed'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l show-ids --description 'Show internal object ids'
complete -c bzr -l sort --description 'ARG Sort tags by different criteria'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l long --description 'Produce long-format testament'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l strict --description 'Produce a strict-format testament'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l dry-run --description 'Don\'t actually make changes'
complete -c bzr -l force --description 'Say yes to all questions'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l keep-tags --description 'Keep tags that point to removed revisions'
complete -c bzr -l local --description 'Only remove the commits from the local branch when in a checkout'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l verbose --description 'Will print out what is being removed'
complete -c bzr -l dry-run --description 'Will go through all the motions, but not actually remove anything'
complete -c bzr -l action --description 'ARG The action to perform'
complete -c bzr -l apply --description 'Apply changes and remove from the shelf'
complete -c bzr -l delete-only --description 'Delete changes without applying them'
complete -c bzr -l dry-run --description 'Show changes, but do not apply or remove them'
complete -c bzr -l keep --description 'Apply changes but don\'t delete them'
complete -c bzr -l preview --description 'Instead of unshelving the changes, show the diff that would result from unshelving'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l show-base --description 'Show base revision text in conflicts'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l clean --description 'Remove the backup'
complete -c bzr -l dry-run --description 'Show what would be done, but don\'t actually do anything'
complete -c bzr -l format --description 'ARG Upgrade to a specific format'
complete -c bzr -l 2a --description 'Format for the bzr 2'
complete -c bzr -l default --description 'Format for the bzr 2'
complete -c bzr -l development-colo --description 'The 2a format with experimental support for colocated branches'
complete -c bzr -l pack-0.92 --description 'Pack-based format used in 1'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l acceptable-keys --description 'ARG, -k Comma separated list of GPG key patterns which are acceptable for verification'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l short --description 'Print just the version number'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l all --description 'Include all possible information'
complete -c bzr -l check-clean --description 'Check if tree is clean'
complete -c bzr -l format --description 'ARG Select the output format'
complete -c bzr -l custom --description 'Version info in Custom template-based format'
complete -c bzr -l python --description 'Version info in Python format'
complete -c bzr -l rio --description 'Version info in RIO (simple text) format (default)'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l include-file-revisions --description 'Include the last revision for each file'
complete -c bzr -l include-history --description 'Include the revision-history'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l revision --description 'ARG, -r See "help revisionspec" for details'
complete -c bzr -l template --description 'ARG Template for the output'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l template --description 'VERSION_INFO \"Project 1'
complete -c bzr -l all --description 'Apply list or delete action to all views'
complete -c bzr -l delete --description 'Delete the view'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l name --description 'ARG Name of the view to define, list or delete'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l switch --description 'ARG Name of the view to switch to'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
complete -c bzr -l branch --description 'Set identity for the current branch instead of globally'
complete -c bzr -l directory --description 'ARG, -d Branch to operate on, instead of working directory'
complete -c bzr -l email --description 'Display email address only'
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l quiet -s q --description 'Only display errors and warnings'
complete -c bzr -l usage --description 'Show usage message and options'
complete -c bzr -l verbose -s v --description 'Display more information'
