complete -c calligraflow -l help -d 'Show help and exit'
complete -c calligraflow -s v -l version -d 'Show version and exit'
complete -c calligraflow -l help-qt -d 'Show Qt specific options and exit'
complete -c calligraflow -l help-kde -d 'Show KDE specific options and exit'
complete -c calligraflow -l help-all -d 'Show all options and exit'
complete -c calligraflow -l author -d 'Show author information and exit'
complete -c calligraflow -l license -d 'Show license information and exit'
