complete -c calligraconverter -l help -d 'Show help and exit'
complete -c calligraconverter -s v -l version -d 'Show version and exit'
complete -c calligraconverter -l author -d 'Show author information and exit'
complete -c calligraconverter -l license -d 'Show license information and exit'
complete -c calligraconverter -l backup -d 'Create backup'
complete -c calligraconverter -l batch -d 'Hide dialogs'
complete -c calligraconverter -l interactive -d 'Show dialogs'
complete -c calligraconverter -l mimetype -d 'Mime type'
complete -c calligraconverter -x -l print-orientation -a 'Portrait Landscape' -d 'Paper orientation'
complete -c calligraconverter -x -l print-papersize -a 'A4 Legal Letter' -d 'Paper size'
complete -c calligraconverter -l print-margin -d 'Paper margin'
