# chef-shell
# Autogenerated from man page man1/chef-shell.1
# using Deroffing man parser
complete -c chef-shell -s a -l standalone --description 'Indicates that chef-shell will be run in standalone mode.'
complete -c chef-shell -s c -l config --description 'The configuration file to use.'
complete -c chef-shell -s h -l help --description 'Shows help for the command.'
complete -c chef-shell -s j -l json-attributes --description 'The path to a file that contains JSON data.'
complete -c chef-shell -s l -l log_level --description 'The level of logging that will be stored in a l… [See --help]'
complete -c chef-shell -s s -l solo --description 'Indicates that chef-shell will be run in chef-solo mode.'
complete -c chef-shell -s S -l server --description 'The URL for the server.'
complete -c chef-shell -s v -l version --description 'The version of the chef-client.'
complete -c chef-shell -s z -l client --description 'Indicates that chef-shell will be run in chef-client mode.'

