complete -c chown -s c -l changes --description "Output diagnostic for changed files"
complete -c chown -l dereference --description "Dereference symbolic links"
complete -c chown -s h -l no-dereference --description "Do not dereference symbolic links"
complete -c chown -l from --description "Change from owner/group"
complete -c chown -s f -l silent --description "Suppress errors"
complete -c chown -l reference --description "Use same owner/group as file" -r
complete -c chown -s R -l recursive --description "Operate recursively"
complete -c chown -s v -l verbose --description "Output diagnostic for every file"
complete -c chown -s h -l help --description "Display help and exit"
complete -c chown -l version --description "Display version and exit"
complete -c chown --description "Username" -a "(__fish_print_users):"
complete -c chown --description "Username" -a "(echo (commandline -ct)| __fish_sgrep -o '.*:')(cat /etc/group |cut -d : -f 1)"
