complete -c composite -o affine -d 'Affine transform matrix [matrix]'
complete -c composite -o alpha -d 'Control alpha/matte channel of an image [option]' -xa '(convert -list alpha)'
complete -c composite -o authenticate -d 'Decipher image with this password [password]'
complete -c composite -o blue-primary -d 'Chromaticity blue primary point [point]'
complete -c composite -o channel -d 'Apply option to select image channels [type]' -xa '(convert -list channel)'
complete -c composite -o colorspace -d 'Alternate image colorspace [type]' -xa '(convert -list colorspace)'
complete -c composite -o comment -d 'Annotate image with comment [string]'
complete -c composite -o compose -d 'Composite operator [operator]'
complete -c composite -o compress -d 'Type of pixel compression when writing the image [type]' -xa '(convert -list compress)'
complete -c composite -o define -d 'Define one or more image format options [format:option]'
complete -c composite -o depth -d 'Image depth [value]'
complete -c composite -o density -d 'Horizontal and vertical density of the image [geometry]'
complete -c composite -o display -d 'Get image or font from this X server [server]'
complete -c composite -o dispose -d 'Layer disposal method [method]' -xa '(convert -list dispose)'
complete -c composite -o dither -d 'Apply error diffusion to image [method]' -xa '(convert -list dither)'
complete -c composite -o encoding -d 'Encoding type [type text]' -xa '(__fish_print_encodings)'
complete -c composite -o endian -d 'Endianness (MSB or LSB) of the image [type]' -xa '(convert -list endian)'
complete -c composite -o filter -d 'Use this filter when resizing an image [type]' -xa '(convert -list filter)'
complete -c composite -o font -d 'Render text with this font [name]' -xa '(__fish_complete_convert_options font)'
complete -c composite -o format -d 'Output formatted image characteristics ["string"]'
complete -c composite -o gravity -d 'Which direction to gravitate towards [type]' -xa '(convert -list gravity)'
complete -c composite -o green-primary -d 'Chromaticity green primary point [point]'
complete -c composite -o interlace -d 'Type of image interlacing scheme [type]' -xa '(convert -list interlace)'
complete -c composite -o interpolate -d 'Pixel color interpolation method [method]' -xa '(convert -list interpolate)'
complete -c composite -o label -d 'Assign a label to an image [string]'
complete -c composite -o limit -d 'Pixel cache resource limit [type value]' -x
complete -c composite -o monitor -d 'Monitor progress'
complete -c composite -o page -d 'Size and location of an image canvas (setting) [geometry]'
complete -c composite -o pointsize -d 'Font point size [value]'
complete -c composite -o quality -d 'JPEG/MIFF/PNG compression level [value]'
complete -c composite -o quiet -d 'Suppress all warning messages'
complete -c composite -o red-primary -d 'Chromaticity red primary point [point]'
complete -c composite -o regard-warnings -d 'Pay attention to warning messages'
complete -c composite -o respect-parentheses -d 'Settings remain in effect until parenthesis boundary'
complete -c composite -o sampling-factor -d 'Horizontal and vertical sampling factor [geometry]'
complete -c composite -o scene -d 'Image scene number [value]'
complete -c composite -o seed -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c composite -o size -d 'Width and height of image [geometry]'
complete -c composite -o synchronize -d 'Synchronize image to storage device'
complete -c composite -o taint -d 'Declare the image as modified'
complete -c composite -o transparent-color -d 'Transparent color [color]' -xa '(__fish_complete_convert_options color)'
complete -c composite -o treedepth -d 'Color tree depth [value]'
complete -c composite -o tile -d 'Repeat composite operation across and down image'
complete -c composite -o units -d 'The units of image resolution [type]' -xa '(convert -list units)'
complete -c composite -o verbose -d 'Print detailed information about the image'
complete -c composite -o virtual-pixel -d 'Virtual pixel access method [method]' -xa '(convert -list virtual-pixel)'
complete -c composite -o white-point -d 'Chromaticity white point [point]'
complete -c composite -o blend -d 'Blend images [geometry]'
complete -c composite -o border -d 'Surround image with a border of color [geometry]'
complete -c composite -o bordercolor -d 'Border color [color]' -xa '(__fish_complete_convert_options color)'
complete -c composite -o colors -d 'Preferred number of colors in the image [value]'
complete -c composite -o decipher -d 'Convert cipher pixels to plain pixels [filename]' -r
complete -c composite -o displace -d 'Shift image pixels defined by a displacement map [geometry]'
complete -c composite -o dissolve -d 'Dissolve the two images a given percent [value]'
complete -c composite -o distort -d 'Shift lookup based on a absolute distortion map [geometry]'
complete -c composite -o encipher -d 'Convert plain pixels to cipher pixels [filename]' -r
complete -c composite -o extract -d 'Extract area from image [geometry]'
complete -c composite -o geometry -d 'Location of the composite image [geometry]'
complete -c composite -o identify -d 'Identify the format and characteristics of the image'
complete -c composite -o monochrome -d 'Transform image to black and white'
complete -c composite -o negate -d 'Replace every pixel with its complementary color '
complete -c composite -o profile -d 'Add ICM or IPTC information profile to image [filename]' -r
complete -c composite -o quantize -d 'Reduce colors in this colorspace [colorspace]' -xa '(convert -list colorspace)'
complete -c composite -o repage -d 'Size and location of an image canvas (operator) [geometry]'
complete -c composite -o rotate -d 'Apply Paeth rotation to the image [degrees]'
complete -c composite -o resize -d 'Resize the image [geometry]'
complete -c composite -o sharpen -d 'Sharpen the image [geometry]'
complete -c composite -o shave -d 'Shave pixels from the image edges [geometry]'
complete -c composite -o stegano -d 'Offset hide watermark within an image'
complete -c composite -o stereo -d 'Combine two image to create a stereo anaglyph [geometry]'
complete -c composite -o strip -d 'Strip image of all profiles and comments'
complete -c composite -o thumbnail -d 'Create a thumbnail of the image [geometry]'
complete -c composite -o transform -d 'Affine transform image'
complete -c composite -o type -d 'Image type [type]' -xa '(convert -list type)'
complete -c composite -o unsharp -d 'Sharpen the image [geometry]'
complete -c composite -o watermark -d 'Percent brightness and saturation of a watermark [geometry]'
complete -c composite -o write -d 'Write images to this file [filename]' -r
complete -c composite -o swap -d 'Swap two images in the image sequence [indexes]'
complete -c composite -o debug -d 'Display copious debugging information [events]' -xa '(convert -list debug)'
complete -c composite -o help -d 'Print program options'
complete -c composite -o list -d 'Print a list of supported option arguments [type]' -xa '(convert -list list)'
complete -c composite -o log -d 'Format of debugging information [format]' -xa '(__fish_complete_convert_options format)'
complete -c composite -o version -d 'Print version information'
complete -c composite -o matte -d 'Store matte channel if the image has one'
complete -c composite -o support -d 'Resize support: > 1.0 is blurry, < 1.0 is sharp [factor]'
