complete -c convert -o adjoin -d 'Join images into a single multi-image file'
complete -c convert -o affine -d 'Affine transform matrix [matrix]'
complete -c convert -o alpha -d 'Activate, deactivate, reset, or set the alpha channel [option]' -xa '(convert -list alpha)'
complete -c convert -o antialias -d 'Remove pixel-aliasing '
complete -c convert -o authenticate -d 'Decipher image with this password [password]'
complete -c convert -o attenuate -d 'Lessen (or intensify) when adding noise to an image [value]'
complete -c convert -o background -d 'Background color [color]' -xa '(__fish_complete_convert_options color)'
complete -c convert -o bias -d 'Add bias when convolving an image [value]'
complete -c convert -o black-point-compensation -d 'Use black point compensation'
complete -c convert -o blue-primary -d 'Chromaticity blue primary point [point]'
complete -c convert -o bordercolor -d 'Border color [color]' -xa '(__fish_complete_convert_options color)'
complete -c convert -o caption -d 'Assign a caption to an image [string]'
complete -c convert -o channel -d 'Apply option to select image channels [type]' -xa '(convert -list channel)'
complete -c convert -o colors -d 'Preferred number of colors in the image [value]'
complete -c convert -o colorspace -d 'Alternate image colorspace [type]' -xa '(convert -list colorspace)'
complete -c convert -o comment -d 'Annotate image with comment [string]'
complete -c convert -o compose -d 'Set image composite operator [operator]'
complete -c convert -o compress -d 'Type of pixel compression when writing the image [type]' -xa '(convert -list compress)'
complete -c convert -o define -d 'Define one or more image format options [format:option]'
complete -c convert -o delay -d 'Display the next image after pausing [value]'
complete -c convert -o density -d 'Horizontal and vertical density of the image [geometry]'
complete -c convert -o depth -d 'Image depth [value]'
complete -c convert -o direction -d 'Render text right-to-left or left-to-right [type]' -xa '(convert -list direction)'
complete -c convert -o display -d 'Get image or font from this X server [server]'
complete -c convert -o dispose -d 'Layer disposal method [method]' -xa '(convert -list dispose)'
complete -c convert -o dither -d 'Apply error diffusion to image [method]' -xa '(convert -list dither)'
complete -c convert -o encoding -d 'Encoding type [type text]' -xa '(__fish_print_encodings)'
complete -c convert -o endian -d 'Endianness (MSB or LSB) of the image [type]' -xa '(convert -list endian)'
complete -c convert -o family -d 'Render text with this font family [name]' -xa '(__fish_complete_convert_options family)'
complete -c convert -o fill -d 'Color to use when filling a graphic primitive [color]' -xa '(__fish_complete_convert_options color)'
complete -c convert -o filter -d 'Use this filter when resizing an image [type]' -xa '(convert -list filter)'
complete -c convert -o font -d 'Render text with this font [name]' -xa '(__fish_complete_convert_options font)'
complete -c convert -o format -d 'Output formatted image characteristics ["string"]'
complete -c convert -o fuzz -d 'Colors within this distance are considered equal [distance]'
complete -c convert -o gravity -d 'Horizontal and vertical text placement [type]' -xa '(convert -list gravity)'
complete -c convert -o green-primary -d 'Chromaticity green primary point [point]'
complete -c convert -o intent -d 'Type of rendering intent when managing the image color [type]' -xa '(convert -list intent)'
complete -c convert -o interlace -d 'Type of image interlacing scheme [type]' -xa '(convert -list interlace)'
complete -c convert -o interline-spacing -d 'Set the space between two text lines [value]'
complete -c convert -o interpolate -d 'Pixel color interpolation method [method]' -xa '(convert -list interpolate)'
complete -c convert -o interword-spacing -d 'Set the space between two words [value]'
complete -c convert -o kerning -d 'Set the space between two letters [value]'
complete -c convert -o label -d 'Assign a label to an image [string]'
complete -c convert -o limit -d 'Pixel cache resource limit [type value]' -x
complete -c convert -o loop -d 'Add Netscape loop extension to your GIF animation [iterations]'
complete -c convert -o mask -d 'Associate a mask with the image [filename]' -r
complete -c convert -o mattecolor -d 'Frame color [color]' -xa '(__fish_complete_convert_options color)'
complete -c convert -o monitor -d 'Monitor progress '
complete -c convert -o orient -d 'Image orientation [type]' -xa '(convert -list orientation)'
complete -c convert -o page -d 'Size and location of an image canvas (setting) [geometry]'
complete -c convert -o ping -d 'Efficiently determine image attributes'
complete -c convert -o pointsize -d 'Font point size [value]'
complete -c convert -o precision -d 'Maximum number of significant digits to print [value]'
complete -c convert -o preview -d 'Image preview type [type]' -xa '(convert -list preview)'
complete -c convert -o quality -d 'JPEG/MIFF/PNG compression level [value]'
complete -c convert -o quiet -d 'Suppress all warning messages'
complete -c convert -o red-primary -d 'Chromaticity red primary point [point]'
complete -c convert -o regard-warnings -d 'Pay attention to warning messages'
complete -c convert -o remap -d 'Transform image colors to match this set of colors [filename]' -r
complete -c convert -o respect-parentheses -d 'Settings remain in effect until parenthesis boundary'
complete -c convert -o sampling-factor -d 'Horizontal and vertical sampling factor [geometry]'
complete -c convert -o scene -d 'Image scene number [value]'
complete -c convert -o seed -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c convert -o size -d 'Width and height of image [geometry]'
complete -c convert -o stretch -d 'Render text with this font stretch [type]' -xa '(convert -list stretch)'
complete -c convert -o stroke -d 'Graphic primitive stroke color [color]' -xa '(__fish_complete_convert_options color)'
complete -c convert -o strokewidth -d 'Graphic primitive stroke width [value]'
complete -c convert -o style -d 'Render text with this font style [type]' -xa '(convert -list style)'
complete -c convert -o synchronize -d 'Synchronize image to storage device'
complete -c convert -o taint -d 'Declare the image as modified'
complete -c convert -o texture -d 'Name of texture to tile onto the image background [filename]' -r
complete -c convert -o tile-offset -d 'Tile offset [geometry]'
complete -c convert -o treedepth -d 'Color tree depth [value]'
complete -c convert -o transparent-color -d 'Transparent color [color]' -xa '(__fish_complete_convert_options color)'
complete -c convert -o undercolor -d 'Annotation bounding box color [color]' -xa '(__fish_complete_convert_options color)'
complete -c convert -o units -d 'The units of image resolution [type]' -xa '(convert -list units)'
complete -c convert -o verbose -d 'Print detailed information about the image'
complete -c convert -o view -d 'FlashPix viewing transforms'
complete -c convert -o virtual-pixel -d 'Virtual pixel access method [method]' -xa '(convert -list virtual-pixel)'
complete -c convert -o weight -d 'Render text with this font weight [type]' -x
complete -c convert -o white-point -d 'Chromaticity white point [point]'
complete -c convert -o adaptive-blur -d 'Adaptively blur pixels; decrease effect near edges [geometry]'
complete -c convert -o adaptive-resize -d 'Adaptively resize image using \'mesh\' interpolation [geometry]'
complete -c convert -o adaptive-sharpen -d 'Adaptively sharpen pixels; increase effect near edges [geometry]'
complete -c convert -o annotate -d 'Annotate the image with text [geometry text]'
complete -c convert -o auto-gamma -d 'Automagically adjust gamma level of image'
complete -c convert -o auto-level -d 'Automagically adjust color levels of image'
complete -c convert -o auto-orient -d 'Automagically orient (rotate) image'
complete -c convert -o bench -d 'Measure performance [iterations]'
complete -c convert -o black-threshold -d 'Force all pixels below the threshold into black [value]'
complete -c convert -o blue-shift -d 'Simulate a scene at nighttime in the moonlight [factor]'
complete -c convert -o blur -d 'Reduce image noise and reduce detail levels [geometry]'
complete -c convert -o border -d 'Surround image with a border of color [geometry]'
complete -c convert -o brightness-contrast -d 'Improve brightness / contrast of the image [geometry]'
complete -c convert -o cdl -d 'Color correct with a color decision list [filename]' -r
complete -c convert -o charcoal -d 'Simulate a charcoal drawing [radius]'
complete -c convert -o chop -d 'Remove pixels from the image interior [geometry]'
complete -c convert -o clamp -d 'Restrict pixel range from 0 to the quantum depth'
complete -c convert -o clip -d 'Clip along the first path from the 8BIM profile'
complete -c convert -o clip-mask -d 'Associate a clip mask with the image [filename]' -r
complete -c convert -o clip-path -d 'Clip along a named path from the 8BIM profile [id]'
complete -c convert -o colorize -d 'Colorize the image with the fill color [value]'
complete -c convert -o color-matrix -d 'Apply color correction to the image [matrix]'
complete -c convert -o contrast -d 'Enhance or reduce the image contrast'
complete -c convert -o contrast-stretch -d 'Improve contrast by `stretching\' the intensity range [geometry]'
complete -c convert -o convolve -d 'Apply a convolution kernel to the image [coefficients]'
complete -c convert -o cycle -d 'Cycle the image colormap [amount]'
complete -c convert -o decipher -d 'Convert cipher pixels to plain pixels [filename]' -r
complete -c convert -o deskew -d 'Straighten an image [threshold]'
complete -c convert -o despeckle -d 'Reduce the speckles within an image'
complete -c convert -o distort -d 'Args distort images according to given method ad args [method]' -xa '(convert -list distort)'
complete -c convert -o draw -d 'Annotate the image with a graphic primitive [string]'
complete -c convert -o edge -d 'Apply a filter to detect edges in the image [radius]'
complete -c convert -o encipher -d 'Convert plain pixels to cipher pixels [filename]' -r
complete -c convert -o emboss -d 'Emboss an image [radius]'
complete -c convert -o enhance -d 'Apply a digital filter to enhance a noisy image'
complete -c convert -o equalize -d 'Perform histogram equalization to an image'
complete -c convert -o evaluate -d 'Evaluate an arithmetic, relational, or logical expression [operator value]'
complete -c convert -o extent -d 'Set the image size [geometry]'
complete -c convert -o extract -d 'Extract area from image [geometry]'
complete -c convert -o fft -d 'Implements the discrete Fourier transform (DFT)'
complete -c convert -o flip -d 'Flip image vertically'
complete -c convert -o floodfill -d 'Color floodfill the image with color [geometry]'
complete -c convert -o flop -d 'Flop image horizontally'
complete -c convert -o frame -d 'Surround image with an ornamental border [geometry]'
complete -c convert -o function -d 'Apply function over image values [name parameters]' -xa '(convert -list function)'
complete -c convert -o gamma -d 'Level of gamma correction [value]'
complete -c convert -o gaussian-blur -d 'Reduce image noise and reduce detail levels [geometry]'
complete -c convert -o geometry -d 'Preferred size or location of the image [geometry]'
complete -c convert -o identify -d 'Identify the format and characteristics of the image'
complete -c convert -o ift -d 'Implements the inverse discrete Fourier transform (DFT)'
complete -c convert -o implode -d 'Implode image pixels about the center [amount]'
complete -c convert -o lat -d 'Local adaptive thresholding [geometry]'
complete -c convert -o layers -d 'Optimize, merge,  or compare image layers [method]' -xa '(convert -list layers)'
complete -c convert -o level -d 'Adjust the level of image contrast [value]'
complete -c convert -o level-colors -d 'Level image with the given colors [color,color]' -xa '(__fish_complete_list , "__fish_complete_convert_options color")'
complete -c convert -o linear-stretch -d 'Improve contrast by `stretching with saturation\' [geometry]'
complete -c convert -o liquid-rescale -d 'Rescale image with seam-carving [geometry]'
complete -c convert -o median -d 'Apply a median filter to the image [geometry]'
complete -c convert -o mode -d 'Make each pixel the \'predominant color\' of the neighborhood [geometry]'
complete -c convert -o modulate -d 'Vary the brightness, saturation, and hue [value]'
complete -c convert -o monochrome -d 'Transform image to black and white'
complete -c convert -o morphology -d 'Apply a morphology method to the image [method kernel]' -xa '(convert -list morphology)'
complete -c convert -o motion-blur -d 'Simulate motion blur [geometry]'
complete -c convert -o negate -d 'Replace every pixel with its complementary color '
complete -c convert -o noise -d 'Add or reduce noise in an image [geometry]'
complete -c convert -o normalize -d 'Transform image to span the full range of colors'
complete -c convert -o opaque -d 'Change this color to the fill color [color]' -xa '(__fish_complete_convert_options color)'
complete -c convert -o ordered-dither -d 'Add a noise pattern to the image with specific amplitudes  [NxN]'
complete -c convert -o paint -d 'Simulate an oil painting [radius]'
complete -c convert -o polaroid -d 'Simulate a Polaroid picture [angle]'
complete -c convert -o posterize -d 'Reduce the image to a limited number of color levels [levels]'
complete -c convert -o profile -d 'Add, delete, or apply an image profile [filename]' -r
complete -c convert -o quantize -d 'Reduce colors in this colorspace [colorspace]' -xa '(convert -list colorspace)'
complete -c convert -o radial-blur -d 'Radial blur the image [angle]'
complete -c convert -o raise -d 'Lighten/darken image edges to create a 3-D effect [value]'
complete -c convert -o random-threshold -d 'Random threshold the image [low,high]'
complete -c convert -o region -d 'Apply options to a portion of the image [geometry]'
complete -c convert -o render -d 'Render vector graphics'
complete -c convert -o repage -d 'Size and location of an image canvas [geometry]'
complete -c convert -o resample -d 'Change the resolution of an image [geometry]'
complete -c convert -o resize -d 'Resize the image [geometry]'
complete -c convert -o roll -d 'Roll an image vertically or horizontally [geometry]'
complete -c convert -o rotate -d 'Apply Paeth rotation to the image [degrees]'
complete -c convert -o sample -d 'Scale image with pixel sampling [geometry]'
complete -c convert -o scale -d 'Scale the image [geometry]'
complete -c convert -o segment -d 'Segment an image [values]'
complete -c convert -o selective-blur -d 'Selectively blur pixels within a contrast threshold [geometry]'
complete -c convert -o sepia-tone -d 'Simulate a sepia-toned photo [threshold]'
complete -c convert -o set -d 'Set an image property [property value]'
complete -c convert -o shade -d 'Shade the image using a distant light source [degrees]'
complete -c convert -o shadow -d 'Simulate an image shadow [geometry]'
complete -c convert -o sharpen -d 'Sharpen the image [geometry]'
complete -c convert -o shave -d 'Shave pixels from the image edges [geometry]'
complete -c convert -o shear -d 'Slide one edge of the image along the X or Y axis [geometry]'
complete -c convert -o sigmoidal-contrast -d 'Increase the contrast without saturating highlights or shadows [geometry]'
complete -c convert -o sketch -d 'Simulate a pencil sketch [geometry]'
complete -c convert -o solarize -d 'Negate all pixels above the threshold level [threshold]'
complete -c convert -o sparse-color -d 'Args fill in a image based on a few color points [method]' -xa '(convert -list sparse-color)'
complete -c convert -o splice -d 'Splice the background color into the image [geometry]'
complete -c convert -o spread -d 'Displace image pixels by a random amount [radius]'
complete -c convert -o statistic -d 'Replace each pixel with corresponding statistic from the neighborhood [type geometry]' -xa '(convert -list statistic)'
complete -c convert -o strip -d 'Strip image of all profiles and comments'
complete -c convert -o swirl -d 'Swirl image pixels about the center [degrees]'
complete -c convert -o threshold -d 'Threshold the image [value]'
complete -c convert -o thumbnail -d 'Create a thumbnail of the image [geometry]'
complete -c convert -o tile -d 'Tile image when filling a graphic primitive [filename]' -r
complete -c convert -o tint -d 'Tint the image with the fill color [value]'
complete -c convert -o transform -d 'Affine transform image'
complete -c convert -o transparent -d 'Make this color transparent within the image [color]' -xa '(__fish_complete_convert_options color)'
complete -c convert -o transpose -d 'Flip image vertically and rotate 90 degrees'
complete -c convert -o transverse -d 'Flop image horizontally and rotate 270 degrees'
complete -c convert -o trim -d 'Trim image edges'
complete -c convert -o type -d 'Image type [type]' -xa '(convert -list type)'
complete -c convert -o unique-colors -d 'Discard all but one of any pixel color'
complete -c convert -o unsharp -d 'Sharpen the image [geometry]'
complete -c convert -o vignette -d 'Soften the edges of the image in vignette style [geometry]'
complete -c convert -o wave -d 'Alter an image along a sine wave [geometry]'
complete -c convert -o white-threshold -d 'Force all pixels above the threshold into white [value]'
complete -c convert -o append -d 'Append an image sequence'
complete -c convert -o clut -d 'Apply a color lookup table to the image'
complete -c convert -o coalesce -d 'Merge a sequence of images'
complete -c convert -o combine -d 'Combine a sequence of images'
complete -c convert -o composite -d 'Composite image '
complete -c convert -o crop -d 'Cut out a rectangular region of the image [geometry]'
complete -c convert -o deconstruct -d 'Break down an image sequence into constituent parts'
complete -c convert -o evaluate-sequence -d 'Evaluate an arithmetic, relational, or logical expression [operator]'
complete -c convert -o flatten -d 'Flatten a sequence of images'
complete -c convert -o fx -d 'Apply mathematical expression to an image channel(s) [expression]'
complete -c convert -o hald-clut -d 'Apply a Hald color lookup table to the image'
complete -c convert -o morph -d 'Morph an image sequence [value]'
complete -c convert -o mosaic -d 'Create a mosaic from an image sequence'
complete -c convert -o print -d 'Interpret string and print to console [string]'
complete -c convert -o process -d 'Process the image with a custom image filter [arguments]' -xa '(convert -list filter)'
complete -c convert -o separate -d 'Separate an image channel into a grayscale image'
complete -c convert -o smush -d 'Smush an image sequence together [geometry]'
complete -c convert -o write -d 'Write images to this file [filename]' -r
complete -c convert -o clone -d 'Clone an image [indexes]'
complete -c convert -o delete -d 'Delete the image from the image sequence [indexes]'
complete -c convert -o duplicate -d 'Duplicate an image one or more times [count,indexes]'
complete -c convert -o insert -d 'Insert last image into the image sequence [index]'
complete -c convert -o reverse -d 'Reverse image sequence'
complete -c convert -o swap -d 'Swap two images in the image sequence [indexes]'
complete -c convert -o debug -d 'Display copious debugging information [events]' -xa '(convert -list debug)'
complete -c convert -o help -d 'Print program options'
complete -c convert -o list -d 'Print a list of supported option arguments [type]' -xa '(convert -list list)'
complete -c convert -o log -d 'Format of debugging information [format]' -xa '(__fish_complete_convert_options format)'
complete -c convert -o version -d 'Print version information'
complete -c convert -o matte -d 'Store matte channel if the image has one'
complete -c convert -o origin -d 'Image origin [geometry]'
complete -c convert -o support -d 'Resize support: > 1.0 is blurry, < 1.0 is sharp [factor]'
complete -c convert -o affinity -d 'Transform image colors to match this set of colors [filename]' -r
