complete -c csh -l help -d 'Display help and exit'
complete -c csh -l version -d 'Display version and exit'

complete -c csh -s b -d 'Stop option processing'
complete -c csh -s c -d 'Specify commands'
complete -c csh -s d -d 'Load directory stack from ~/.cshdirs'
complete -c csh -s D -d 'Specify environment variable'
complete -c csh -s e -d 'Exit when exit status is not zero'
complete -c csh -s f -d 'Do not load resource and startup files'
complete -c csh -s F -d 'Use fork instead of vfork'
complete -c csh -s i -d 'Use interactive mode'
complete -c csh -s l -d 'Use login shell'
complete -c csh -s m -d 'Load ~/.tcshrc'
complete -c csh -s n -d 'Parse commands without executing'
complete -c csh -s q -d 'Accept SIGQUIT'
complete -c csh -s s -d 'Specify commands via stdin'
complete -c csh -s t -d 'Read and execute single input line'
complete -c csh -s v -d 'Set `verbose` shell variable'
complete -c csh -s x -d 'Set `echo` shell variable'
complete -c csh -s V -d 'Set `verbose` shell variable'
complete -c csh -s X -d 'Set `echo` shell variable'
