complete -c cygstart -s a -l action -r -a 'open explore edit find print' -d 'Use specified action instead of default'
complete -c cygstart -s o -l open -d 'Short for: --action open'
complete -c cygstart -s x -l explore -d 'Short for: --action explore'
complete -c cygstart -s e -l edit -d 'Short for: --action edit'
complete -c cygstart -s f -l find -d 'Short for: --action find'
complete -c cygstart -s p -l print -d 'Short for: --action print'
complete -c cygstart -s d -l directory -r -d 'Set working directory'
complete -c cygstart -l hide -d 'Hide window and activates another window'
complete -c cygstart -l maximize -d 'Maximize the specified window'
complete -c cygstart -l minimize -d 'Minimize the specified window'
complete -c cygstart -l restore -d 'Activate and display window'
complete -c cygstart -l show -d 'Activate window and display in current size and position'
complete -c cygstart -l showmaximized -d 'Activate and maximize window'
complete -c cygstart -l showminimized -d 'Activate and minimize window'
complete -c cygstart -l showminnoactive -d 'Display window minimized'
complete -c cygstart -l showna -d 'Display window in current state'
complete -c cygstart -l shownoactivate -d 'Display a window in most recent size and position'
complete -c cygstart -l shownormal -d 'Activate and display a window'
complete -c cygstart -s w -l wait -d 'Wait until the application terminates before exiting'
complete -c cygstart -s v -l verbose -d 'Show the actual ShellExecute call made'
complete -c cygstart -s '?' -l help -d 'Show this help message'
complete -c cygstart -l usage -d 'Display brief usage message'
complete -c cygstart -l version -d 'Display version information'
complete -c cygstart -l license -d 'Display licensing information'
complete -c cygstart -l reference -d 'Open MSDN reference for ShellExecute'
