# Completions for diff
complete -c diff -s i -l ignore-case -d (N_ "Ignore case differences")
complete -c diff -l ignore-file-name-case -d (N_ "Ignore case when comparing file names")
complete -c diff -l no-ignore-file-name-case -d (N_ "Consider case when comparing file names")
complete -c diff -s E -l ignore-tab-expansion -d (N_ "Ignore changes due to tab expansion")
complete -c diff -s b -l ignore-space-change -d (N_ "Ignore changes in the amount of white space")
complete -c diff -s w -l ignore-all-space -d (N_ "Ignore all white space")
complete -c diff -s B -l ignore-blank-lines -d (N_ "Ignore changes whose lines are all blank")
complete -c diff -s I -l ignore-matching-lines -x -d (N_ "Ignore changes whose lines match the REGEX")
complete -c diff -s a -l text -d (N_ "Treat all files as text")
complete -c diff -s r -l recursive -d (N_ "Recursively compare subdirectories")
complete -c diff -s N -l new-file -d (N_ "Treat absent files as empty")
complete -c diff -s C -l context -x -d (N_ "Output NUM lines of copied context")
complete -c diff -s c -d (N_ "Output 3 lines of copied context")
complete -c diff -s U -l unified -x -d (N_ "Output NUM lines of unified context")
complete -c diff -s u -d (N_ "Output 3 lines of unified context")
complete -c diff -s q -l brief -d (N_ "Output only whether the files differ")
complete -c diff -l normal -d (N_ "Output a normal diff")
complete -c diff -s y -l side-by-side -d (N_ "Output in two columns")
complete -c diff -s W -l width -x -d (N_ "Output at most NUM print columns")
complete -c diff -s d -l minimal -d (N_ "Try to find a smaller set of changes")
complete -c diff -l from-file -r -d (N_ "Compare FILE1 to all operands")
complete -c diff -l to-file -r -d (N_ "Compare FILE2 to all operands")
complete -c diff -s l -l paginate -d (N_ "Pass the output through 'pr'")
complete -c diff -s v -l version -d (N_ "Display version and exit")
complete -c diff -l help -d (N_ "Display help and exit")
