complete -c display -o alpha -d 'Control alpha/matte channel of an image [option]' -xa '(display -list alpha)'
complete -c display -o antialias -d 'Remove pixel-aliasing'
complete -c display -o authenticate -d 'Decipher image with this password [password]'
complete -c display -o backdrop -d 'Display image centered on a backdrop'
complete -c display -o channel -d 'Apply option to select image channels [type]' -xa '(display -list channel)'
complete -c display -o colormap -d 'Shared or Private [type]' -x
complete -c display -o colorspace -d 'Alternate image colorspace [type]' -xa '(display -list colorspace)'
complete -c display -o comment -d 'Annotate image with comment [string]'
complete -c display -o compress -d 'Type of pixel compression when writing the image [type]' -xa '(display -list compress)'
complete -c display -o define -d 'Define one or more image format options [format:option]'
complete -c display -o delay -d 'Display the next image after pausing [value]'
complete -c display -o density -d 'Horizontal and vertical density of the image [geometry]'
complete -c display -o depth -d 'Image depth [value]'
complete -c display -o display -d 'Display image to this X server [server]'
complete -c display -o dispose -d 'Layer disposal method [method]' -xa '(display -list dispose)'
complete -c display -o dither -d 'Apply error diffusion to image [method]' -xa '(display -list dither)'
complete -c display -o endian -d 'Endianness (MSB or LSB) of the image [type]' -xa '(display -list endian)'
complete -c display -o filter -d 'Use this filter when resizing an image [type]' -xa '(display -list filter)'
complete -c display -o format -d 'Output formatted image characteristics [string]'
complete -c display -o geometry -d 'Preferred size and location of the Image window [geometry]'
complete -c display -o gravity -d 'Horizontal and vertical backdrop placement [type]' -xa '(display -list gravity)'
complete -c display -o identify -d 'Identify the format and characteristics of the image'
complete -c display -o immutable -d 'Displayed image cannot be modified'
complete -c display -o interlace -d 'Type of image interlacing scheme [type]' -xa '(display -list interlace)'
complete -c display -o interpolate -d 'Pixel color interpolation method [method]' -xa '(display -list interpolate)'
complete -c display -o label -d 'Assign a label to an image [string]'
complete -c display -o limit -d 'Pixel cache resource limit [type value]' -x
complete -c display -o loop -d 'Loop images then exit [iterations]'
complete -c display -o map -d 'Display image using this Standard Colormap [type]' -x
complete -c display -o monitor -d 'Monitor progress'
complete -c display -o page -d 'Size and location of an image canvas [geometry]'
complete -c display -o profile -d 'Add, delete, or apply an image profile [filename]' -r
complete -c display -o quality -d 'JPEG/MIFF/PNG compression level [value]'
complete -c display -o quantize -d 'Reduce colors in this colorspace [colorspace]' -xa '(display -list colorspace)'
complete -c display -o quiet -d 'Suppress all warning messages'
complete -c display -o regard-warnings -d 'Pay attention to warning messages'
complete -c display -o remote -d 'Command execute a command in an remote display process'
complete -c display -o repage -d 'Size and location of an image canvas (operator) [geometry]'
complete -c display -o respect-parentheses -d 'Settings remain in effect until parenthesis boundary'
complete -c display -o sampling-factor -d 'Horizontal and vertical sampling factor [geometry]'
complete -c display -o seed -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c display -o set -d 'Set an image property [property value]'
complete -c display -o size -d 'Width and height of image [geometry]'
complete -c display -o texture -d 'Texture name to tile onto the image background [filename]' -r
complete -c display -o transparent-color -d 'Transparent color [color]' -xa '(__fish_complete_convert_options color)'
complete -c display -o treedepth -d 'Color tree depth [value]'
complete -c display -o update -d 'Seconds detect when image file is modified and redisplay'
complete -c display -o verbose -d 'Print detailed information about the image'
complete -c display -o visual -d 'Display image using this visual type [type]' -x
complete -c display -o virtual-pixel -d 'Virtual pixel access method [method]' -xa '(display -list virtual-pixel)'
complete -c display -o window -d 'Display image to background of this window [id]' -xa 'root (__fish_print_xwindows)'
complete -c display -o window-group -d 'Exit program when this window id is destroyed [id]'
complete -c display -o write -d 'Write image to a file [filename]' -r
complete -c display -o auto-orient -d 'Automagically orient (rotate) image'
complete -c display -o border -d 'Surround image with a border of color [geometry]'
complete -c display -o clip -d 'Clip along the first path from the 8BIM profile'
complete -c display -o clip-path -d 'Clip along a named path from the 8BIM profile [id]'
complete -c display -o colors -d 'Preferred number of colors in the image [value]'
complete -c display -o contrast -d 'Enhance or reduce the image contrast'
complete -c display -o crop -d 'Preferred size and location of the cropped image [geometry]'
complete -c display -o decipher -d 'Convert cipher pixels to plain pixels [filename]' -r
complete -c display -o deskew -d 'Straighten an image [threshold]'
complete -c display -o despeckle -d 'Reduce the speckles within an image'
complete -c display -o edge -d 'Apply a filter to detect edges in the image [factor]'
complete -c display -o enhance -d 'Apply a digital filter to enhance a noisy image'
complete -c display -o equalize -d 'Perform histogram equalization to an image'
complete -c display -o extract -d 'Extract area from image [geometry]'
complete -c display -o flip -d 'Flip image in the vertical direction'
complete -c display -o flop -d 'Flop image in the horizontal direction'
complete -c display -o frame -d 'Surround image with an ornamental border [geometry]'
complete -c display -o fuzz -d 'Colors within this distance are considered equal [distance]'
complete -c display -o gamma -d 'Level of gamma correction [value]'
complete -c display -o monochrome -d 'Transform image to black and white'
complete -c display -o negate -d 'Replace every pixel with its complementary color'
complete -c display -o normalize -d 'Transform image to span the full range of colors'
complete -c display -o raise -d 'Lighten/darken image edges to create a 3-D effect [value]'
complete -c display -o resample -d 'Change the resolution of an image [geometry]'
complete -c display -o resize -d 'Resize the image [geometry]'
complete -c display -o roll -d 'Roll an image vertically or horizontally [geometry]'
complete -c display -o rotate -d 'Apply Paeth rotation to the image [degrees]'
complete -c display -o sample -d 'Scale image with pixel sampling [geometry]'
complete -c display -o segment -d 'Segment an image [value]'
complete -c display -o sharpen -d 'Sharpen the image [geometry]'
complete -c display -o strip -d 'Strip image of all profiles and comments'
complete -c display -o threshold -d 'Threshold the image [value]'
complete -c display -o thumbnail -d 'Create a thumbnail of the image [geometry]'
complete -c display -o trim -d 'Trim image edges'
complete -c display -o coalesce -d 'Merge a sequence of images'
complete -c display -o flatten -d 'Flatten a sequence of images'
complete -c display -o debug -d 'Display copious debugging information [events]' -xa '(display -list debug)'
complete -c display -o help -d 'Print program options'
complete -c display -o list -d 'Print a list of supported option arguments [type]' -xa '(display -list list)'
complete -c display -o log -d 'Format of debugging information [format]' -xa '(__fish_complete_convert_options format)'
complete -c display -o version -d 'Print version information'
complete -c display -o matte -d 'Store matte channel if the image has one'
complete -c display -o scenes -d 'Range image scene range'
complete -c display -o support -d 'Resize support: > 1.0 is blurry, < 1.0 is sharp [factor]'
