complete -c dolphin -l help -d 'Show help and exit'
complete -c dolphin -s v -l version -d 'Show version and exit'
complete -c dolphin -l help-qt -d 'Show Qt specific options and exit'
complete -c dolphin -l help-kde -d 'Show KDE specific options and exit'
complete -c dolphin -l help-all -d 'Show all options and exit'
complete -c dolphin -l author -d 'Show author information and exit'
complete -c dolphin -l license -d 'Show license information and exit'
