complete -c du -s a -l all -d (_ "Write size for all files")
complete -c du -l apparent-size -d (_ "Print file size, not disk usage")
complete -c du -s B -l block-size -d (_ "Block size")
complete -c du -s b -l bytes -d (_ "Use 1B block size")
complete -c du -s c -l total -d (_ "Produce grand total")
complete -c du -s D -l dereference-args -d (_ "Dereference file symlinks")
complete -c du -s h -l human-readable -d (_ "Human readable sizes")
complete -c du -s H -l si -d (_ "Human readable sizes, powers of 1000")
complete -c du -s k -d (_ "Use 1kB block size")
complete -c du -s l -l count-links -d (_ "Count hard links multiple times")
complete -c du -s L -l dereference -d (_ "Dereference all symlinks")
complete -c du -s S -l separate-dirs -d (_ "Do not include subdirectory size")
complete -c du -s s -l summarize -d (_ "Display only a total for each argument")
complete -c du -s x -l one-file-system -d (_ "Skip other filesystems")
complete -c du -s X -l exclude-from -r -d (_ "Exclude files thet match pattern in file")
complete -c du -l exclude -r -d (_ "Exclude files that match pattern")
complete -c du -l max-depth -r -d (_ "Recursion limit")
complete -c du -l help -d (_ "Display help and exit")
complete -c du -l version -d (_ "Display version and exit")

