complete -c es -s c -d 'Commands to run'
complete -c es -s s -d 'Read commands from stdin'
complete -c es -s i -d 'Use interactive'
complete -c es -s l -d 'Use login shell'
complete -c es -s e -d 'Exit on command failure'
complete -c es -s v -d 'Echo input to stderr'
complete -c es -s x -d 'Echo commands to stderr'
complete -c es -s n -d 'Do not execute commands, just parse them'
complete -c es -s p -d 'Do not initialize functions from environment'
complete -c es -s o -d 'Do not open /dev/null on 0, 1, 2 descriptors'
complete -c es -s d -d 'Do not trap SIGQUIT or SIGTERM'
