#fd 7.4.0

#flags
complete -c fd -l absolute-path  -s a -d "Show absolute instead of relative paths"
complete -c fd -l case-sensitive -s s -d "Case-sensitive search (default: smart case)"
complete -c fd -l fixed-strings  -s F -d "Treat the pattern as a literal string"
complete -c fd -l follow         -s L -d "Follow symbolic links"
complete -c fd -l full-path      -s p -d "Search full path (default: file-/dirname only)"
complete -c fd -l glob           -s g -d "Glob-based search (default: regular expression)"
complete -c fd -l help           -s h -d "Prints help information"
complete -c fd -l hidden         -s H -d "Search hidden files and directories"
complete -c fd -l ignore-case    -s i -d "Case-insensitive search (default: smart case)"
complete -c fd -l no-ignore      -s I -d "Do not respect .(git|fd)ignore files"
complete -c fd -l no-ignore-vcs       -d "Do not respect .gitignore files"
complete -c fd -l print0         -s 0 -d "Separate results by the null character"
complete -c fd -l regex               -d "Perform a regular-expression based seach (default)"
complete -c fd -l show-errors         -d "Enable the display of filesystem errors"
complete -c fd -l version        -s V -d "Prints version information"

#options
complete -c fd -l changed-before      -d "Filter by file modification time (older than)"
complete -c fd -l changed-within      -d "Filter by file modification time (newer than)"
complete -c fd -l color          -s c -d "When to use colors: never, *auto*, always"
complete -c fd -l exclude        -s E -d "Exclude entries that match the given glob pattern"
complete -c fd -l exec           -s x -d "Execute a command for each search result"
complete -c fd -l exec-batch     -s X -d "Execute a command with all search results at once"
complete -c fd -l extension      -s e -d "Filter by file extension"
complete -c fd -l ignore-file         -d "Add a custom ignore-file in '.gitignore' format"
complete -c fd -l max-depth      -s d -d "Set maximum search depth (default: none)"
complete -c fd -l path-separator      -d "Set the path separator to use when printing file paths"
complete -c fd -l search-path         -d "Provide paths to search as an alternative to the positional argument"
complete -c fd -l size           -s S -d "Limit results based on the size of files"
complete -c fd -l threads        -s j -d "Set number of threads to use for searching & executing"
complete -c fd -l type           -s t -d "Filter by type: (f)ile, (d)irectory, sym(l)ink, e(x)ecutable, (e)mpty"
