# Main options
complete -c ffplay -s L -d "Show license"
complete -x -c ffplay -s h -s "?" -o help -l help -a "
long
full
(ffplay -loglevel quiet -decoders | grep -v -e '=' -e ':\$' -e '^\s-' | sed 's/[\t ]/\t/g' | cut -f 3 | sed 's/^/decoder=/g')
(ffplay -loglevel quiet -encoders | grep -v -e '=' -e ':\$' -e '^\s-' | sed 's/[\t ]/\t/g' | cut -f 3 | sed 's/^/encoder=/g')
(ffplay -loglevel quiet -demuxers | grep -v -e '=' -e ':\$' -e '^\s-' | sed 's/[\t ]/\t/g' | cut -f 4 | sed 's/^/demuxer=/g')
(ffplay -loglevel quiet -muxers | grep -v -e '=' -e ':\$' -e '^\s-' | sed 's/[\t ]/\t/g' | cut -f 4 | sed 's/^/muxer=/g')
(ffplay -loglevel quiet -filters | grep -v -e '=' -e ':\$' -e '^\s-' | sed 's/[\t ]/\t/g' | cut -f 3 | sed 's/^/filter=/g')
" -d "Show help"
complete -c ffplay -o version -d "Show version"
complete -c ffplay -o buildconf -d "Show build configuration"
complete -c ffplay -o formats -d "Show available formats"
complete -c ffplay -o muxers -d "Show available muxers"
complete -c ffplay -o demuxers -d "Show available demuxers"
complete -c ffplay -o devices -d "Show available devices"
complete -c ffplay -o codecs -d "Show available codecs"
complete -c ffplay -o decoders -d "Show available decoders"
complete -c ffplay -o encoders -d "Show available encoders"
complete -c ffplay -o bsfs -d "Show available bit stream filters"
complete -c ffplay -o protocols -d "Show available protocols"
complete -c ffplay -o filters -d "Show available filters"
complete -c ffplay -o pix_fmts -d "Show available pixel formats"
complete -c ffplay -o layouts -d "Show standard channel layouts"
complete -c ffplay -o sample_fmts -d "Show available audio sample formats"
complete -c ffplay -o colors -d "Show available color names"
complete -x -c ffplay -o loglevel -s v -a "quiet panic fatal error warning info verbose debug trace" -d "Set logging level"
complete -c ffplay -o report -d "Generate a report"
complete -c ffplay -o max_alloc -d "Set maximum size of a single allocated block"
complete -c ffplay -o sources -d "List sources of the input device"
complete -c ffplay -o sinks -d "List sinks of the output device"
complete -c ffplay -s x -d "Force displayed width"
complete -c ffplay -s y -d "Force displayed height"
complete -c ffplay -s s -d "Set frame size"
complete -c ffplay -o fs -d "Force full screen"
complete -c ffplay -o an -d "Disable audio"
complete -c ffplay -o vn -d "Disable video"
complete -c ffplay -o sn -d "Disable subtitle"
complete -c ffplay -o ss -d "Seek to a given position in seconds"
complete -c ffplay -s t -d "Play "duration" seconds of audio/video"
complete -x -c ffplay -o bytes -a "0 1 -1" -d "Seek by bytes 0 = off, 1 = on, -1 = auto"
complete -c ffplay -o nodisp -d "Disable graphical display"
complete -c ffplay -o noborder -d "Borderless window"
complete -c ffplay -o volume -d "Set startup volume"
complete -c ffplay -s f -d "Force format"
complete -c ffplay -o window_title -d "Set window title"
complete -c ffplay -o af -d "Set audio filters"
complete -x -c ffplay -o showmode -a "0 1 2" -d "Select show mode 0 = video, 1 = waves, 2 = RDFT"
complete -c ffplay -s i -d "Read specified file"
complete -x -c ffplay -o codec -a "(ffplay -loglevel quiet -decoders | grep -v -e '=' -e ':\$' -e '^\s-' | sed 's/[\t ]/\t/g' | cut -f 3)" -d "Force decoder"
complete -c ffplay -o autorotate -d "Automatically rotate video"
