#completion for file

complete -c file -s b -l brief --description 'Do not prepend filenames to output lines'
complete -c file -s c -l checking-printout --description 'Print the parsed form of the magic file'
complete -c file -s C -l compile --description 'Write an output file containing a pre-parsed version of file'
complete -c file -s h -l no-dereference --description 'Do not follow symlinks'
complete -c file -s i -l mime --description 'Output mime type strings instead human readable strings'
complete -c file -s k -l keep-going --description 'Don\'t stop at the first match'
complete -c file -s L -l dereference --description 'Follow symlinks'
complete -c file -s n -l no-buffer --description 'Flush stdout after checking each file'
complete -c file -s N -l no-pad --description 'Don\'t pad filenames so that they align in the output'
complete -c file -s p -l preserve-date --description 'Attempt to preserve the access time of files analyzed'
complete -c file -s r -l raw --description 'Don\'t translate unprintable characters to octal'
complete -c file -s s -l special-files --description 'Read block and character device files too'
complete -c file -s v -l version --description 'Print the version of the program and exit'
complete -c file -s z -l uncompress --description 'Try to look inside compressed files'
complete -c file -l help --description 'Print a help message and exit'

complete -r -c file -s f -l files-from --description 'Read  the  names of the files to be examined from a file'
complete -r -c file -s F -l separator --description 'Use other string as result field separator instead of :'
complete -r -c file -s m -l magic-file --description 'Alternate list of files containing magic numbers'
