complete -c fish_add_path -s a -l append -d 'Add path to the end'
complete -c fish_add_path -s p -l prepend -d 'Add path to the front (default)'
complete -c fish_add_path -s g -l global -d 'Use a global $fish_user_paths'
complete -c fish_add_path -s U -l universal -d 'Use a universal $fish_user_paths (default)'
complete -c fish_add_path -s P -l path -d 'Update $PATH directly'
complete -c fish_add_path -s m -l move -d 'Move path to the front or back'
complete -c fish_add_path -s v -l verbose -d 'Print the set command used'
complete -c fish_add_path -s n -l dry-run -d 'Print the set command without executing it'
complete -c fish_add_path -s h -l help -d 'Display help and exit'
