complete -c fish_indent -s h -l help --description 'Display help and exit'
complete -c fish_indent -s v -l version --description 'Display version and exit'
complete -c fish_indent -s i -l no-indent --description 'Do not indent output, only reformat into one job per line'
complete -c fish_indent -l ansi --description 'Colorize the output using ANSI escape sequences'
complete -c fish_indent -l html --description 'Output in HTML format'
complete -c fish_indent -s w -l write --description 'Write to file'
complete -c fish_indent -s d -l debug-level -x --description 'Enable debug at specified verbosity level'
complete -c fish_indent -s D -l debug-stack-frames -x --description 'Specify how many stack frames to display in debug messages'
complete -c fish_indent -l dump-parse-tree --description 'Dump information about parsed statements to stderr'
