complete -c fish_indent -s h -l help --description 'Display help and exit'
complete -c fish_indent -s v -l version --description 'Display version and exit'
complete -c fish_indent -s i -l no-indent --description 'Do not indent output, only reformat into one job per line'
complete -c fish_indent -l ansi --description 'Colorize the output using ANSI escape sequences'
complete -c fish_indent -l html --description 'Output in HTML format'
