# grub-file - check file type

complete -c grub-file -l is-i386-xen-pae-domu -d 'Check if FILE can be booted as i386 PAE Xen unprivileged guest kernel'
complete -c grub-file -l is-x86 -d 'Check if given file can be booted as x86_64 Xen unprivileged guest kernel'
complete -c grub-file -l is-x86-xen-dom0 -d 'Check if given file can be used as Xen x86 privileged guest kernel'
complete -c grub-file -l is-x86-multiboot -d 'Check if given file can be used as x86 multiboot kernel'
complete -c grub-file -l is-x86-multiboot2 -d 'Check if given file can be used as x86 multiboot2 kernel'
complete -c grub-file -l is-arm-linux -d 'Check if given file is ARM Linux'
complete -c grub-file -l is-arm64-linux -d 'Check if given file is ARM64 Linux'
complete -c grub-file -l is-ia64-linux -d 'Check if given file is IA64 Linux'
complete -c grub-file -l is-mips-linux -d 'Check if given file is MIPS Linux'
complete -c grub-file -l is-mipsel-linux -d 'Check if given file is MIPSEL Linux'
complete -c grub-file -l is-sparc64-linux -d 'Check if given file is SPARC64 Linux'
complete -c grub-file -l is-powerpc-linux -d 'Check if given file is POWERPC Linux'
complete -c grub-file -l is-x86-linux -d 'Check if given file is x86 Linux'
complete -c grub-file -l is-x86-linux32 -d 'Check if given file is x86 Linux supporting 32-bit protocol'
complete -c grub-file -l is-x86-kfreebsd -d 'Check if given file is x86 kFreeBSD'
complete -c grub-file -l is-i386-kfreebsd -d 'Check if given file is i386 kFreeBSD'
complete -c grub-file -l is-x86 -d 'Check if given file is x86_64 kFreeBSD'
complete -c grub-file -l is-x86-knetbsd -d 'Check if given file is x86 kNetBSD'
complete -c grub-file -l is-i386-knetbsd -d 'Check if given file is i386 kNetBSD'
complete -c grub-file -l is-x86 -d 'Check if given file is x86_64 kNetBSD'
complete -c grub-file -l is-i386-efi -d 'Check if given file is i386 EFI file'
complete -c grub-file -l is-x86 -d 'Check if given file is x86_64 EFI file'
complete -c grub-file -l is-ia64-efi -d 'Check if given file is IA64 EFI file'
complete -c grub-file -l is-arm64-efi -d 'Check if given file is ARM64 EFI file'
complete -c grub-file -l is-arm-efi -d 'Check if given file is ARM EFI file'
complete -c grub-file -l is-hibernated-hiberfil -d 'Check if given file is hiberfil.sys in hibernated state'
complete -c grub-file -l is-x86 -d 'Check if given file is x86_64 XNU (Mac OS X kernel)'
complete -c grub-file -l is-i386-xnu -d 'Check if given file is i386 XNU (Mac OS X kernel)'
complete -c grub-file -l is-xnu-hibr -d 'Check if given file is XNU (Mac OS X kernel) hibernated image'
complete -c grub-file -l is-x86-bios-bootsector -d 'Check if given file is BIOS bootsector'
complete -c grub-file -l help -s h -d 'Display help and exit'
complete -c grub-file -l usage -s u -d 'Display usage and exit'
