# Completions for icdiff
complete -c icdiff -l version -d "Display version and exit"
complete -c icdiff -s h -l help -d "Display help and exit"
complete -c icdiff -l cols -d "Specify the width of the screen"
complete -c icdiff -l encoding -d "Specify file encoding"
complete -c icdiff -s E -l exclude-lines -d "Ignore lines that match this regex"
complete -c icdiff -l head -d "Consider only the first N lines of each file"
complete -c icdiff -s H -l highlight -d "Use the background instead of foreground color for diff"
complete -c icdiff -s L -l label -d "Override file label. Use twice for both files"
complete -c icdiff -s N -l line-numbers -d "Show line numbers"
complete -c icdiff -l no-bold -d "Use non-bold colors"
complete -c icdiff -l no-headers -d "Don't show file labels"
complete -c icdiff -l output-encoding -d "Specify output encoding"
complete -c icdiff -s r -l recursive -d "Recursive search"
complete -c icdiff -s s -l report-identical-files -d "Report when two files are same"
complete -c icdiff -l show-all-spaces -d "Color non-matchining whitespace changes"
complete -c icdiff -l tabsize -d "Tab stop spacing"
complete -c icdiff -s U -l unified -l numlines -d "Print N lines of sourrounding context"
complete -c icdiff -s W -l whole-file -d "Show the whole file instead of just changings"
complete -c icdiff -l strip-trailing-cr -d "Strip trailing carriage return at the end of an input line"
complete -c icdiff -l color-map -d "Specify color map"
