complete -c identify -o antialias -d 'Remove pixel-aliasing'
complete -c identify -o authenticate -d 'Decrypt image with this password [value]'
complete -c identify -o channel -d 'Apply option to select image channels [type]' -xa '(identify -list channel)'
complete -c identify -o crop -d 'Cut out a rectangular region of the image [geometry]'
complete -c identify -o define -d 'Define one or more image format options [format:option]'
complete -c identify -o density -d 'Horizontal and vertical density of the image [geometry]'
complete -c identify -o depth -d 'Image depth [value]'
complete -c identify -o extract -d 'Extract area from image [geometry]'
complete -c identify -o features -d 'Display image features [distance]'
complete -c identify -o format -d 'Output formatted image characteristics ["string"]'
complete -c identify -o fuzz -d 'Colors within this distance are considered equal [distance]'
complete -c identify -o interlace -d 'Type of image interlacing scheme [type]' -xa '(identify -list interlace)'
complete -c identify -o interpolate -d 'Pixel color interpolation method [method]' -xa '(identify -list interpolate)'
complete -c identify -o limit -d 'Pixel cache resource limit [type value]' -x
complete -c identify -o list -d 'Print a list of supported option arguments [type]' -xa '(identify -list list)'
complete -c identify -o matte -d 'Store matte channel if the image has one'
complete -c identify -o monitor -d 'Monitor progress'
complete -c identify -o ping -d 'Efficiently determine image attributes'
complete -c identify -o quiet -d 'Suppress all warning messages'
complete -c identify -o regard-warnings -d 'Pay attention to warning messages'
complete -c identify -o sampling-factor -d 'Horizontal and vertical sampling factor [geometry]'
complete -c identify -o seed -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c identify -o set -d 'Attribute set an image attribute [value]'
complete -c identify -o size -d 'Width and height of image [geometry]'
complete -c identify -o strip -d 'Strip image of all profiles and comments'
complete -c identify -o unique -d 'Display the number of unique colors in the image'
complete -c identify -o units -d 'The units of image resolution [type]' -xa '(identify -list units)'
complete -c identify -o verbose -d 'Print detailed information about the image'
complete -c identify -o virtual-pixel -d 'Virtual pixel access method [method]' -xa '(identify -list virtual-pixel)'
complete -c identify -o negate -d 'Replace each pixel with its complementary color'
complete -c identify -o debug -d 'Display copious debugging information [events]' -xa '(identify -list debug)'
complete -c identify -o help -d 'Print program options'
complete -c identify -o log -d 'Format of debugging information [format]' -xa '(__fish_complete_convert_options format)'
