complete -c ifdata -xa '(__fish_print_interfaces)'
complete -c ifdata -o e -d 'Reports interface existence via return code'
complete -c ifdata -o p -d 'Print out the whole config of iface'
complete -c ifdata -o pe -d 'Print out yes or no according to existence'
complete -c ifdata -o pa -d 'Print out the address'
complete -c ifdata -o pn -d 'Print netmask'
complete -c ifdata -o pN -d 'Print network address'
complete -c ifdata -o pb -d 'Print broadcast'
complete -c ifdata -o pm -d 'Print mtu'
complete -c ifdata -o ph -d 'Print out the hardware address'
complete -c ifdata -o pf -d 'Print flags'
complete -c ifdata -o si -d 'Print all statistics on input'
complete -c ifdata -o sip -d 'Print # of in packets'
complete -c ifdata -o sib -d 'Print # of in bytes'
complete -c ifdata -o sie -d 'Print # of in errors'
complete -c ifdata -o sid -d 'Print # of in drops'
complete -c ifdata -o sif -d 'Print # of in fifo overruns'
complete -c ifdata -o sic -d 'Print # of in compress'
complete -c ifdata -o sim -d 'Print # of in multicast'
complete -c ifdata -o so -d 'Print all statistics on output'
complete -c ifdata -o sop -d 'Print # of out packets'
complete -c ifdata -o sob -d 'Print # of out bytes'
complete -c ifdata -o soe -d 'Print # of out errors'
complete -c ifdata -o sod -d 'Print # of out drops'
complete -c ifdata -o sof -d 'Print # of out fifo overruns'
complete -c ifdata -o sox -d 'Print # of out collisions'
complete -c ifdata -o soc -d 'Print # of out carrier loss'
complete -c ifdata -o som -d 'Print # of out multicast'
complete -c ifdata -o bips -d 'Print # of incoming bytes per second'
complete -c ifdata -o bops -d 'Print # of outgoing bytes per second'
