function __fish_installer_has_pkg
    contains -- -pkg (commandline -xpc)
    or contains -- -package (commandline -xpc)
end

function __fish_installer_has_target
    contains -- -target (commandline -xpc)
    or contains -- -tgt (commandline -xpc)
end

function __fish_installer_volumes
    set -l volumes / /Volumes/*
    printf '%s\n' $volumes
end

complete -c installer -o pkg -d 'Package to install (.pkg or .mpkg)' -r
complete -c installer -o package -d 'Package to install (synonym for -pkg)' -r
complete -c installer -o target -d 'Target volume, device, or domain' -xa '(__fish_installer_volumes)'
complete -c installer -o tgt -d 'Target volume, device, or domain (synonym for -target)' -xa '(__fish_installer_volumes)'
complete -c installer -o dominfo -d 'List domains where the package can be installed'
complete -c installer -o volinfo -d 'List volumes where the package can be installed'
complete -c installer -o pkginfo -d 'List packages inside the package (subpackages for metapkg)'
complete -c installer -d 'Print install choices in hierarchical XML (for System Image Utility)' -o showChoicesXML
complete -c installer -d 'Print install choices in choiceChanges XML format' -o showChoiceChangesXML
complete -c installer -d 'Apply choiceChanges XML and print resulting choices; requires -target' -o showChoicesAfterApplyingChangesXML -r
complete -c installer -d 'Apply install choice changes from an XML file before installation' -o applyChoiceChangesXML -r
complete -c installer -d 'Query package metadata (e.g. RestartAction)' -o query -f -xa RestartAction
complete -c installer -o verbose -d 'Display more descriptive output'
complete -c installer -o verboseR -d 'Verbose output formatted for easy parsing'
complete -c installer -o plist -d 'Format output as XML plist (use with -dominfo/-volinfo/-pkginfo)'
complete -c installer -o dumplog -d 'Write install log to stderr in addition to syslog'
complete -c installer -o config -d 'Format current arguments as a config plist (no install performed)'
complete -c installer -o file -r -d 'Path to XML config file (generated by -config)'
complete -c installer -o lang -d 'Default language for OS installs (ISO language code, e.g. en)'
complete -c installer -o listiso -d 'List valid ISO language codes'
complete -c installer -o store -d 'Install product archive as the Mac App Store would'
complete -c installer -o allowUntrusted -d 'Allow install of package signed by untrusted or expired cert'
complete -c installer -o vers -d 'Display the version of the installer tool'
complete -c installer -o help -d 'Display help screen'
