# installer - system software and package installer tool (man 8 installer)
#
# installer uses single-dash flags; -pkg and -target are required for
# installation.  -tgt is an accepted synonym for -target; -package for -pkg.
# Most flags are mutually independent; a few take a path argument.

# ── command-line introspection ───────────────────────────────────────
# True when -pkg has already been given on the command line.
function __fish_installer_has_pkg
    contains -- -pkg (commandline -opc)
    or contains -- -package (commandline -opc)
end

# True when -target has already been given on the command line.
function __fish_installer_has_target
    contains -- -target (commandline -opc)
    or contains -- -tgt (commandline -opc)
end

# ── live enumerators ─────────────────────────────────────────────────
# List mounted volumes: /Volumes/* plus the root mount point /.
function __fish_installer_volumes
    echo /
    ls /Volumes 2>/dev/null | while read -l v
        echo /Volumes/$v
    end
end

# ── flags (no verb gating — all flags are top-level) ─────────────────

# Required: package path (.pkg / .mpkg)
complete -c installer -o pkg -d 'Package to install (.pkg or .mpkg)' -r
complete -c installer -o package -d 'Package to install (synonym for -pkg)' -r

# Required: target volume / device / domain
complete -c installer -o target -d 'Target volume, device, or domain' \
    -xa '(__fish_installer_volumes)'
complete -c installer -o tgt -d 'Target volume, device, or domain (synonym for -target)' \
    -xa '(__fish_installer_volumes)'

# Informational flags (typically combined with -pkg)
complete -c installer -o dominfo -f -d 'List domains where the package can be installed'
complete -c installer -o volinfo -f -d 'List volumes where the package can be installed'
complete -c installer -o pkginfo -f -d 'List packages inside the package (subpackages for metapkg)'
complete -c installer -o showChoicesXML -f \
    -d 'Print install choices in hierarchical XML (for System Image Utility)'
complete -c installer -o showChoiceChangesXML -f \
    -d 'Print install choices in choiceChanges XML format'
complete -c installer -o showChoicesAfterApplyingChangesXML -r \
    -d 'Apply choiceChanges XML and print resulting choices; requires -target'
complete -c installer -o applyChoiceChangesXML -r \
    -d 'Apply install choice changes from an XML file before installation'

# Query
complete -c installer -o query -f \
    -xa RestartAction \
    -d 'Query package metadata (e.g. RestartAction)'

# Output modifiers
complete -c installer -o verbose -f -d 'Display more descriptive output'
complete -c installer -o verboseR -f -d 'Verbose output formatted for easy parsing'
complete -c installer -o plist -f -d 'Format output as XML plist (use with -dominfo/-volinfo/-pkginfo)'
complete -c installer -o dumplog -f -d 'Write install log to stderr in addition to syslog'
complete -c installer -o config -f -d 'Format current arguments as a config plist (no install performed)'

# Input from a pre-built config file
complete -c installer -o file -r -d 'Path to XML config file (generated by -config)'

# Language
complete -c installer -o lang -f \
    -d 'Default language for OS installs (ISO language code, e.g. en)'
complete -c installer -o listiso -f -d 'List valid ISO language codes'

# App Store / trust
complete -c installer -o store -f -d 'Install product archive as the Mac App Store would'
complete -c installer -o allowUntrusted -f -d 'Allow install of package signed by untrusted or expired cert'

# Informational
complete -c installer -o vers -f -d 'Display the version of the installer tool'
complete -c installer -o help -f -d 'Display help screen'
