# irb (interactive ruby)

complete -c irb -s f -d "Suppresses read of ~/.irbrc"
complete -c irb -s d -d "Set \$DEBUG to true"
complete -c irb -s r -f -d "Load LIB using require"
complete -c irb -s I -xa "(__fish_complete_directories)" -d "Specify \$LOAD_PATH directory"
complete -c irb -s U -d "Same as 'ruby -U'"
complete -c irb -s E -l encoding -d "Specify default text encoding"
complete -c irb -s w -d "Turn on warnings'"
complete -c irb -s W -xa '0 1 2' -d "Set warning level"
complete -c irb -l context-mode -xa '0 1 2 3' -d "Create Binding Object"
complete -c irb -l echo -d "Show result"
complete -c irb -l noecho -d "Don't show result"
complete -c irb -l inspect -d "Use 'inspect' for output"
complete -c irb -l noinspect -d "Don't use 'inspect' for output"
complete -c irb -l readline -d "Use Readline extension module"
complete -c irb -l noreadline -d "Don't use Readline extension module"
complete -c irb -l prompt -xa "default simple xmp inf-ruby" -d "Switch prompt mode"
complete -c irb -l prompt-mode -xa "default simple xmp inf-ruby" -d "Switch prompt mode"
complete -c irb -l inf-ruby-mode -d "Use prompt for emacs inf-ruby-mode"
complete -c irb -l sample-book-mode -d "Simple prompt mode"
complete -c irb -l simple-prompt -d "Simple prompt mode"
complete -c irb -l noprompt -d "No prompt mode"
complete -c irb -l single-irb -d "Share self with sub-irb"
complete -c irb -l tracer -d "Displays trace for each execution of commands"
complete -c irb -l back-trace-limit -x -d "Displays backtrace, top N and tail N"
complete -c irb -l irb_debug -x -d "Sets internal debug level to N"
complete -c irb -l verbose -d "Show details"
complete -c irb -l noverbose -d "Don't show details"
complete -c irb -s v -l version -d "Print the version of irb"
complete -c irb -s h -l help -d "Print a summary of options"
