complete --command launchctl -n __fish_use_subcommand -xa "bootstrap\tBootstraps a domain or a service into a domain"
complete --command launchctl -n __fish_use_subcommand -xa "bootout\tTears down a domain or removes a service from a domain"
complete --command launchctl -n __fish_use_subcommand -xa "enable\tEnables an existing service"
complete --command launchctl -n __fish_use_subcommand -xa "disable\tDisables an existing service"
complete --command launchctl -n __fish_use_subcommand -xa "uncache\tRemoves the specified service name from the service cache"
complete --command launchctl -n __fish_use_subcommand -xa "kickstart\tForces an existing service to start"
complete --command launchctl -n __fish_use_subcommand -xa "attach\tAttach the system's debugger to a service"
complete --command launchctl -n __fish_use_subcommand -xa "debug\tConfigures the next invocation of a service for debugging"
complete --command launchctl -n __fish_use_subcommand -xa "kill\tSends a signal to the service instance"
complete --command launchctl -n __fish_use_subcommand -xa "blame\tPrints the reason a service is running"
complete --command launchctl -n __fish_use_subcommand -xa "print\tPrints a description of a domain or service"
complete --command launchctl -n __fish_use_subcommand -xa "print-cache\tPrints information about the service cache"
complete --command launchctl -n __fish_use_subcommand -xa "print-disabled\tPrints which services are disabled"
complete --command launchctl -n __fish_use_subcommand -xa "plist\tPrints a property list embedded in a binary (targets the Info.plist by default)"
complete --command launchctl -n __fish_use_subcommand -xa "procinfo\tPrints port information about a process"
complete --command launchctl -n __fish_use_subcommand -xa "hostinfo\tPrints port information about the host"
complete --command launchctl -n __fish_use_subcommand -xa "resolveport\tResolves a port name from a process to an endpoint in launchd"
complete --command launchctl -n __fish_use_subcommand -xa "limit\tReads or modifies launchd's resource limits"
complete --command launchctl -n __fish_use_subcommand -xa "runstats\tPrints performance statistics for a service"
complete --command launchctl -n __fish_use_subcommand -xa "examine\tRuns the specified analysis tool against launchd in a non-reentrant manner"
complete --command launchctl -n __fish_use_subcommand -xa "config\tModifies persistent configuration parameters for launchd domains"
complete --command launchctl -n __fish_use_subcommand -xa "dumpstate\tDumps launchd state to stdout"
complete --command launchctl -n __fish_use_subcommand -xa "dumpjpcategory\tDumps the jetsam properties category for all services"
complete --command launchctl -n __fish_use_subcommand -xa "reboot\tInitiates a system reboot of the specified type"
complete --command launchctl -n __fish_use_subcommand -xa "bootshell\tBrings the system up from single-user mode with a console shell"
complete --command launchctl -n __fish_use_subcommand -xa "load\tBootstraps a service or directory of services"
complete --command launchctl -n __fish_use_subcommand -xa "unload\tUnloads a service or directory of services"
complete --command launchctl -n __fish_use_subcommand -xa "remove\tUnloads the specified service name"
complete --command launchctl -n __fish_use_subcommand -xa "list\tLists information about services"
complete --command launchctl -n __fish_use_subcommand -xa "start\tStarts the specified service"
complete --command launchctl -n __fish_use_subcommand -xa "stop\tStops the specified service if it is running"
complete --command launchctl -n __fish_use_subcommand -xa "setenv\tSets the specified environment variables for all services within the domain"
complete --command launchctl -n __fish_use_subcommand -xa "unsetenv\tUnsets the specified environment variables for all services within the domain"
complete --command launchctl -n __fish_use_subcommand -xa "getenv\tGets the value of an environment variable from within launchd"
complete --command launchctl -n __fish_use_subcommand -xa "bsexec\tExecute a program in another process' bootstrap context"
complete --command launchctl -n __fish_use_subcommand -xa "asuser\tExecute a program in the bootstrap context of a given user"
complete --command launchctl -n __fish_use_subcommand -xa "submit\tSubmit a basic job from the command line"
complete --command launchctl -n __fish_use_subcommand -xa "managerpid\tPrints the PID of the launchd controlling the session"
complete --command launchctl -n __fish_use_subcommand -xa "manageruid\tPrints the UID of the current launchd session"
complete --command launchctl -n __fish_use_subcommand -xa "managername\tPrints the name of the current launchd session"
complete --command launchctl -n __fish_use_subcommand -xa "error\tPrints a description of an error"
complete --command launchctl -n __fish_use_subcommand -xa "variant\tPrints the launchd variant"
complete --command launchctl -n __fish_use_subcommand -xa "version\tPrints the launchd version"
complete --command launchctl -n __fish_use_subcommand -xa "help\tPrints the usage for a given subcommand"
