complete --command launchctl -n __fish_use_subcommand -xa bootstrap -d "Bootstraps a domain or a service into a domain"
complete --command launchctl -n __fish_use_subcommand -xa bootout -d "Tears down a domain or removes a service from a domain"
complete --command launchctl -n __fish_use_subcommand -xa enable -d "Enables an existing service"
complete --command launchctl -n __fish_use_subcommand -xa disable -d "Disables an existing service"
complete --command launchctl -n __fish_use_subcommand -xa uncache -d "Removes the specified service name from the service cache"
complete --command launchctl -n __fish_use_subcommand -xa kickstart -d "Forces an existing service to start"
complete --command launchctl -n __fish_use_subcommand -xa attach -d "Attach the system's debugger to a service"
complete --command launchctl -n __fish_use_subcommand -xa debug -d "Configures the next invocation of a service for debugging"
complete --command launchctl -n __fish_use_subcommand -xa kill -d "Sends a signal to the service instance"
complete --command launchctl -n __fish_use_subcommand -xa blame -d "Prints the reason a service is running"
complete --command launchctl -n __fish_use_subcommand -xa print -d "Prints a description of a domain or service"
complete --command launchctl -n __fish_use_subcommand -xa print-cache -d "Prints information about the service cache"
complete --command launchctl -n __fish_use_subcommand -xa print-disabled -d "Prints which services are disabled"
complete --command launchctl -n __fish_use_subcommand -xa plist -d "Prints a property list embedded in a binary (targets the Info.plist by default)"
complete --command launchctl -n __fish_use_subcommand -xa procinfo -d "Prints port information about a process"
complete --command launchctl -n __fish_use_subcommand -xa hostinfo -d "Prints port information about the host"
complete --command launchctl -n __fish_use_subcommand -xa resolveport -d "Resolves a port name from a process to an endpoint in launchd"
complete --command launchctl -n __fish_use_subcommand -xa limit -d "Reads or modifies launchd's resource limits"
complete --command launchctl -n __fish_use_subcommand -xa runstats -d "Prints performance statistics for a service"
complete --command launchctl -n __fish_use_subcommand -xa examine -d "Runs the specified analysis tool against launchd in a non-reentrant manner"
complete --command launchctl -n __fish_use_subcommand -xa config -d "Modifies persistent configuration parameters for launchd domains"
complete --command launchctl -n __fish_use_subcommand -xa dumpstate -d "Dumps launchd state to stdout"
complete --command launchctl -n __fish_use_subcommand -xa dumpjpcategory -d "Dumps the jetsam properties category for all services"
complete --command launchctl -n __fish_use_subcommand -xa reboot -d "Initiates a system reboot of the specified type"
complete --command launchctl -n __fish_use_subcommand -xa bootshell -d "Brings the system up from single-user mode with a console shell"
complete --command launchctl -n __fish_use_subcommand -xa load -d "Bootstraps a service or directory of services"
complete --command launchctl -n __fish_use_subcommand -xa unload -d "Unloads a service or directory of services"
complete --command launchctl -n __fish_use_subcommand -xa remove -d "Unloads the specified service name"
complete --command launchctl -n __fish_use_subcommand -xa list -d "Lists information about services"
complete --command launchctl -n __fish_use_subcommand -xa start -d "Starts the specified service"
complete --command launchctl -n __fish_use_subcommand -xa stop -d "Stops the specified service if it is running"
complete --command launchctl -n __fish_use_subcommand -xa setenv -d "Sets the specified environment variables for all services within the domain"
complete --command launchctl -n __fish_use_subcommand -xa unsetenv -d "Unsets the specified environment variables for all services within the domain"
complete --command launchctl -n __fish_use_subcommand -xa getenv -d "Gets the value of an environment variable from within launchd"
complete --command launchctl -n __fish_use_subcommand -xa bsexec -d "Execute a program in another process' bootstrap context"
complete --command launchctl -n __fish_use_subcommand -xa asuser -d "Execute a program in the bootstrap context of a given user"
complete --command launchctl -n __fish_use_subcommand -xa submit -d "Submit a basic job from the command line"
complete --command launchctl -n __fish_use_subcommand -xa managerpid -d "Prints the PID of the launchd controlling the session"
complete --command launchctl -n __fish_use_subcommand -xa manageruid -d "Prints the UID of the current launchd session"
complete --command launchctl -n __fish_use_subcommand -xa managername -d "Prints the name of the current launchd session"
complete --command launchctl -n __fish_use_subcommand -xa error -d "Prints a description of an error"
complete --command launchctl -n __fish_use_subcommand -xa variant -d "Prints the launchd variant"
complete --command launchctl -n __fish_use_subcommand -xa version -d "Prints the launchd version"
complete --command launchctl -n __fish_use_subcommand -xa help -d "Prints the usage for a given subcommand"
