complete --command launchctl -n '__fish_use_subcommand' -xa 'bootstrap\t"'(_ "Bootstraps a domain or a service into a domain")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'bootout\t"'(_ "Tears down a domain or removes a service from a domain")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'enable\t"'(_ "Enables an existing service")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'disable\t"'(_ "Disables an existing service")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'uncache\t"'(_ "Removes the specified service name from the service cache")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'kickstart\t"'(_ "Forces an existing service to start")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'attach\t"'(_ "Attach the system's debugger to a service")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'debug\t"'(_ "Configures the next invocation of a service for debugging")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'kill\t"'(_ "Sends a signal to the service instance")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'blame\t"'(_ "Prints the reason a service is running")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'print\t"'(_ "Prints a description of a domain or service")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'print-cache\t"'(_ "Prints information about the service cache")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'print-disabled\t"'(_ "Prints which services are disabled")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'plist\t"'(_ "Prints a property list embedded in a binary (targets the Info.plist by default)")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'procinfo\t"'(_ "Prints port information about a process")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'hostinfo\t"'(_ "Prints port information about the host")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'resolveport\t"'(_ "Resolves a port name from a process to an endpoint in launchd")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'limit\t"'(_ "Reads or modifies launchd's resource limits")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'runstats\t"'(_ "Prints performance statistics for a service")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'examine\t"'(_ "Runs the specified analysis tool against launchd in a non-reentrant manner")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'config\t"'(_ "Modifies persistent configuration parameters for launchd domains")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'dumpstate\t"'(_ "Dumps launchd state to stdout")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'dumpjpcategory\t"'(_ "Dumps the jetsam properties category for all services")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'reboot\t"'(_ "Initiates a system reboot of the specified type")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'bootshell\t"'(_ "Brings the system up from single-user mode with a console shell")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'load\t"'(_ "Bootstraps a service or directory of services")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'unload\t"'(_ "Unloads a service or directory of services")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'remove\t"'(_ "Unloads the specified service name")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'list\t"'(_ "Lists information about services")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'start\t"'(_ "Starts the specified service")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'stop\t"'(_ "Stops the specified service if it is running")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'setenv\t"'(_ "Sets the specified environment variables for all services within the domain")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'unsetenv\t"'(_ "Unsets the specified environment variables for all services within the domain")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'getenv\t"'(_ "Gets the value of an environment variable from within launchd")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'bsexec\t"'(_ "Execute a program in another process' bootstrap context")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'asuser\t"'(_ "Execute a program in the bootstrap context of a given user")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'submit\t"'(_ "Submit a basic job from the command line")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'managerpid\t"'(_ "Prints the PID of the launchd controlling the session")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'manageruid\t"'(_ "Prints the UID of the current launchd session")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'managername\t"'(_ "Prints the name of the current launchd session")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'error\t"'(_ "Prints a description of an error")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'variant\t"'(_ "Prints the launchd variant")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'version\t"'(_ "Prints the launchd version")'"'
complete --command launchctl -n '__fish_use_subcommand' -xa 'help\t"'(_ "Prints the usage for a given subcommand")'"'

