# Fish completions for lsd <https://github.com/Peltoche/lsd/>

# Flags
complete -c lsd -s a -l all -d "Do not ignore entries starting with ."
complete -c lsd -s A -l allmost-all -d "Do not list implied . and .."
complete -c lsd -l classic -d "Enable classic mode (display output similar to ls)"
complete -c lsd -s Z -l context -d "Print security context (label) of each file"
complete -c lsd -s L -l dereference -d "Show information for the file a link references rather than for the link itself"
complete -c lsd -s d -l directory-only -d "Display directories themselves, and not their contents"
complete -c lsd -s X -l extensionsort -d "Sort by file extension"
complete -c lsd -l group-directories-first -d "Groups the directories at the top before the files"
complete -c lsd -l help -d "Prints help information"
complete -c lsd -l header -d "Display block headers"
complete -c lsd -l ignore-config -d "Ignore the configuration file"
complete -c lsd -s F -l classify -d "Append indicator (one of */=>@|) at the end of the file names"
complete -c lsd -s i -l inode -d "Display the index number of each file"
complete -c lsd -s l -l long -d "Display extended file metadata as a table"
complete -c lsd -s U -l no-sort -d "Do not sort. List entries in directory order"
complete -c lsd -l no-symlink -d "Do not display symlink target"
complete -c lsd -s 1 -l oneline -d "Display one entry per line"
complete -c lsd -s R -l recursice -d "Recurse into directories"
complete -c lsd -s r -l reverse -d "Reverse the order of the sort"
complete -c lsd -s S -l sizesort -d "Sort by size"
complete -c lsd -s t -l timesort -d "Sort by time modified"
complete -c lsd -l total-size -d "Display the total size of directories"
complete -c lsd -l tree -d "Recurse into directories and present the result as a tree"
complete -c lsd -s V -l version -d "Prints version information"
complete -c lsd -s v -l versionsort -d "Natural sort of (version) numbers within text"

# Options
complete -c lsd -l blocks -xa "permission user group context size date name inode links" -d "Specify the blocks that will be displayed and in what order"
complete -c lsd -l color -xa "always auto never" -d "When to use terminal colours"
complete -c lsd -l config-file -rF -d "Provide a custom lsd configuration file"
complete -c lsd -l date -xa "date relative" -d "How to display date"
complete -c lsd -l depth -x -d "Stop recursing into directories after reaching specified depth"
complete -c lsd -l group-dirs -xa "none first last" -d "Sort the directories then the files"
complete -c lsd -l hyperlink -xa "always auto never" -d "Attach hyperlink to filenames"
complete -c lsd -l icon -xa "always auto never" -d "When to print the icons"
complete -c lsd -l icon-theme -xa "fancy unicode" -d "Whether to use fancy or unicode icons"
complete -c lsd -s I -l ignore-glob -r -d "Do not display files/directories with names matching the glob pattern"
complete -c lsd -l permission -xa "rwx octal" -d "How to display permissions"
complete -c lsd -l size -xa "default short bytes" -d "How to display size"
complete -c lsd -l sort -xa "size time version extension none" -d "sort by"
