complete -c makedepend -s D -r -d Define
complete -c makedepend -s I -r -d "Include directory"
complete -c makedepend -s Y -r -d "Replace include directories"
complete -c makedepend -s a -d "Append dependencies to makefile"
complete -c makedepend -s f -r -d "Specify makefile"
complete -c makedepend -o include -r -d "Prepend file to input"
complete -c makedepend -s o -r -d "Object file suffix"
complete -c makedepend -s p -r -d "Object file prefix"
complete -c makedepend -s s -r -d "Starting string delimiter"
complete -c makedepend -s w -r -d "Line width"
complete -c makedepend -s v -d "Verbose mode"
complete -c makedepend -s m -d "Warn about multiple inclusion"
