complete -c makedepend -s D -r -d (_ "Define")
complete -c makedepend -s I -r -d (_ "Include directory")
complete -c makedepend -s Y -r -d (_ "Replace include directories")
complete -c makedepend -s a -d (_ "Append dependencies to makefile")
complete -c makedepend -s f -r -d (_ "Specify makefile")
complete -c makedepend -o include -r -d (_ "Prepend file to input")
complete -c makedepend -s o -r -d (_ "Object file suffix")
complete -c makedepend -s p -r -d (_ "Object file prefix")
complete -c makedepend -s s -r -d (_ "Starting string delimiter")
complete -c makedepend -s w -r -d (_ "Line width")
complete -c makedepend -s v -d (_ "Verbose mode")
complete -c makedepend -s m -d (_ "Warn about multiple inclusion")

