complete -c mc -s a -l stickchars -d 'No graphic chars for line drawing'
complete -c mc -s b -l nocolor -d 'Force black and white display'
complete -c mc -s c -l color -d 'Force color mode'
complete -c mc -s C -l colors -d 'Specify a different color set'
complete -c mc -s S -d 'Specify a name of skin'
complete -c mc -s d -l nomouse -d 'Disable mouse support'
complete -c mc -s e -l edit -d 'Start the internal editor with FILE'
complete -c mc -s f -l datadir -d 'Display the compiled-in search paths'
complete -c mc -s F -l datadir-info -d 'Display extended info about compiled-in paths'
complete -c mc -l configure-options -d 'Display configure options'
complete -c mc -s k -l resetsoft -d 'Reset softkeys to their default'
complete -c mc -s K -d 'Specify a keymap FILE'
complete -c mc -l nokeymap -d 'Use default hardcoded keys'
complete -c mc -s l -l ftplog -d 'Save the ftpfs dialog with the server in FILE'
complete -c mc -s P -l printwd -d 'Print the last working directory to FILE'
complete -c mc -s s -d 'Set alternative mode drawing of frameworks'
complete -c mc -s t -l termcap -d 'Use the TERMCAP variable for terminal info'
complete -c mc -s u -l nosubshell -d 'Disable use of the concurrent shell'
complete -c mc -s U -l subshell -d 'Enable use of the concurrent shell'
complete -c mc -s v -l view -d 'Start the internal viewer with FILE'
complete -c mc -s V -l version -d 'Display the version of the program'
complete -c mc -s x -l xterm -d 'Force xterm mode'
complete -c mc -s g -l oldmouse -d 'Force a "normal tracking" mouse mode'
