complete -c mimedb -s t -l input-file-data -d (_ "Input is a file, use name and contents to determine mimetype")
complete -c mimedb -s f -l input-filename -d (_ "Input is a file, use name to determine mimetype")
complete -c mimedb -s i -l input-mime -d (_ "Input is a mimetype")
complete -c mimedb -s m -l output-mime -d (_ "Output mimetype")
complete -c mimedb -s d -l output-description -d (_ "Output description of mimetype")
complete -c mimedb -s a -l output-action -d (_ "Output default action for mimetype")
complete -c mimedb -s l -l launch -d (_ "Launch default action for each file")
complete -c mimedb -s h -l help -d (_ "Display help and exit")
complete -c mimedb -s v -l version -d (_ "Display version and exit")
