complete -c mocha -l help -o help -s h -d "Show help"
complete -c mocha -s V -l version -d "output the version number"
complete -c mocha -s A -l async-only -d "force all tests to take a callback (async) or return a promise"
complete -c mocha -s c -l colors -d "force enabling of colors"
complete -c mocha -s C -l no-colors -d "force disabling of colors"
complete -c mocha -s G -l growl -d "enable growl notification support"
complete -c mocha -s O -l reporter-options -d "<k=v,k2=v2,...>  reporter-specific options"
complete -c mocha -s R -l reporter -x -d "specify the reporter to use"
complete -c mocha -s S -l sort -d "sort test files"
complete -c mocha -s b -l bail -d "bail after first test failure"
complete -c mocha -s d -l debug -d "enable node's debugger, synonym for node --debug"
complete -c mocha -s g -l grep -x -d "only run tests matching <pattern>"
complete -c mocha -s f -l fgrep -x -d "only run tests containing <string>"
complete -c mocha -s g -l expose-gc -d "expose gc extension"
complete -c mocha -s i -l invert -d "inverts --grep and --fgrep matches"
complete -c mocha -s r -l require -r -d "require the given module"
complete -c mocha -s s -l slow -x -d "\"slow\" test threshold in milliseconds [75]"
complete -c mocha -s t -l timeout -x -d "set test-case timeout in milliseconds [2000]"
complete -c mocha -s u -l ui -x -d "specify user-interface (bdd|tdd|qunit|exports)"
complete -c mocha -s w -l watch -d "watch files for changes"
complete -c mocha -l check-leaks -d "check for global variable leaks"
complete -c mocha -l full-trace -d "display the full stack trace"
complete -c mocha -l compilers -x -d "use the given module(s) to compile files"
complete -c mocha -l debug-brk -d "enable node's debugger breaking on thefirst line"
complete -c mocha -l globals -x -d "allow the given comma-delimited global[names]"
complete -c mocha -l es_staging -d "enable all staged features"
complete -c mocha -l harmony -d "all node --harmony* flags are available"
complete -c mocha -l preserve-symlinks -d "Preserve symbolic links when loading modules"
complete -c mocha -l icu-data-dir -d "include ICU data"
complete -c mocha -l inline-diffs -d "display actual/expected differences inline within each string"
complete -c mocha -l interfaces -d "display available interfaces"
complete -c mocha -l no-deprecation -d "silence deprecation warnings"
complete -c mocha -l no-exit -d "require a clean shutdown of the event loop: mocha will not call process.exit"
complete -c mocha -l no-timeouts -d "disables timeouts, given implicitly with --debug"
complete -c mocha -l opts -d "specify opts path"
complete -c mocha -l perf-basic-prof -d "enable perf linux profiler (basic support)"
complete -c mocha -l prof -d "log statistical profiling information"
complete -c mocha -l log-timer-events -d "Time events including external callbacks"
complete -c mocha -l recursive -d "include sub directories"
complete -c mocha -l reporters -d "display available reporters"
complete -c mocha -l retries -d "set numbers of time to retry a failed test case"
complete -c mocha -l throw-deprecation -d "throw an exception anytime a deprecated function is used"
complete -c mocha -l trace -d "trace function calls"
complete -c mocha -l trace-deprecation -d "show stack traces on deprecations"
complete -c mocha -l use_strict -d "enforce strict mode"
complete -c mocha -l watch-extensions -d "additional extensions to monitor with --watch"
complete -c mocha -l delay -d "wait for async suite definition"
