complete --command monodis --short-option h --long-option help --description 'Show help'

# Options
complete --command monodis --long-option output --description 'Redirect stdout to file'
complete --command monodis --long-option mscorlib --description 'Use \'mscorlib\' as the assembly name for non-corlib assemblies'
complete --command monodis --long-option show-method-tokens --description 'Show tokens for disassembled methods'
complete --command monodis --long-option show-tokens --description 'Show tokens for strings, types, methods, fields, ...'

# Options to display metadata tables
complete --command monodis --long-option assembly --description 'Include Assembly table contents'
complete --command monodis --long-option assemblyref --description 'Include AssemblyRef table contents'
complete --command monodis --long-option classlayout --description 'Include ClassLayout table contents'
complete --command monodis --long-option constant --description 'Include Constant table contents'
complete --command monodis --long-option customattr --description 'Include CustomAttribute table contents'
complete --command monodis --long-option declsec --description 'Include DeclSec table contents'
complete --command monodis --long-option event --description 'Include Event table contents'
complete --command monodis --long-option exported --description 'Include ExportedType table contents'
complete --command monodis --long-option fields --description 'Include Field table contents'
complete --command monodis --long-option file --description 'Include File table contents'
complete --command monodis --long-option forward-decls --description 'Include forward declarations for classes'
complete --command monodis --long-option genericpar --description 'Include GenericParam table contents'
complete --command monodis --long-option implmap --description 'Include ImplMap table contents'
complete --command monodis --long-option interface --description 'Include InterfaceImpl table contents'
complete --command monodis --long-option manifest --description 'Include ManifestResource table contents'
complete --command monodis --long-option marshal --description 'Include FieldMarshal table contents'
complete --command monodis --long-option numberref --description 'Include MemberRef table contents'
complete --command monodis --long-option method --description 'Include MethodRef table contents'
complete --command monodis --long-option methodimpl --description 'Include MethodImpl table contents'
complete --command monodis --long-option methodspec --description 'Include MethodSpec table contents'
complete --command monodis --long-option methodsem --description 'Include MethodSemantics table contents'
complete --command monodis --long-option module --description 'Include Module table contents'
complete --command monodis --long-option moduleref --description 'Include ModuleRef table contents'
complete --command monodis --long-option mresources --description 'Save all the managed resources embedded in the assembly into the current directory'
complete --command monodis --long-option presources --description 'Show offsets and names of manifest resources embedded in the assembly'
complete --command monodis --long-option nested --description 'Include NestedClass table contents'
complete --command monodis --long-option param --description 'Include Param table contents'
complete --command monodis --long-option parconst --description 'Include GenericParameterConstraint table contents'
complete --command monodis --long-option property --description 'Include Property table contents'
complete --command monodis --long-option propertymap --description 'Include PropertyMap table contents'
complete --command monodis --long-option standalonesig --description 'Include StandAloneSig table contents'
complete --command monodis --long-option typedef --description 'Include TypeDef table contents'
complete --command monodis --long-option typespec --description 'Include TypeRef table contents'
complete --command monodis --long-option blob --description 'Use hex for entire contents of the blob stream'
complete --command monodis --long-option strings --description 'Include Strings table contents'
complete --command monodis --long-option userstrings --description 'Include User-Strings heap contents'
