# Options
complete -c monodis -s h -l help -d 'Show help'

complete -c monodis -l output -r -d 'Redirect stdout to file'
complete -c monodis -l mscorlib -d 'Use \'mscorlib\' as the assembly name for non-corlib assemblies'
complete -c monodis -l show-method-tokens -d 'Show tokens for disassembled methods'
complete -c monodis -l show-tokens -d 'Show tokens for strings, types, methods, fields, ...'

# Options to display metadata tables
complete -c monodis -l assembly -d 'Include Assembly table contents'
complete -c monodis -l assemblyref -d 'Include AssemblyRef table contents'
complete -c monodis -l classlayout -d 'Include ClassLayout table contents'
complete -c monodis -l constant -d 'Include Constant table contents'
complete -c monodis -l customattr -d 'Include CustomAttribute table contents'
complete -c monodis -l declsec -d 'Include DeclSec table contents'
complete -c monodis -l event -d 'Include Event table contents'
complete -c monodis -l exported -d 'Include ExportedType table contents'
complete -c monodis -l fields -d 'Include Field table contents'
complete -c monodis -l file -d 'Include File table contents'
complete -c monodis -l forward-decls -d 'Include forward declarations for classes'
complete -c monodis -l genericpar -d 'Include GenericParam table contents'
complete -c monodis -l implmap -d 'Include ImplMap table contents'
complete -c monodis -l interface -d 'Include InterfaceImpl table contents'
complete -c monodis -l manifest -d 'Include ManifestResource table contents'
complete -c monodis -l marshal -d 'Include FieldMarshal table contents'
complete -c monodis -l numberref -d 'Include MemberRef table contents'
complete -c monodis -l method -d 'Include MethodRef table contents'
complete -c monodis -l methodimpl -d 'Include MethodImpl table contents'
complete -c monodis -l methodspec -d 'Include MethodSpec table contents'
complete -c monodis -l methodsem -d 'Include MethodSemantics table contents'
complete -c monodis -l module -d 'Include Module table contents'
complete -c monodis -l moduleref -d 'Include ModuleRef table contents'
complete -c monodis -l mresources -d 'Save all the managed resources embedded in the assembly into the current directory'
complete -c monodis -l presources -d 'Show offsets and names of manifest resources embedded in the assembly'
complete -c monodis -l nested -d 'Include NestedClass table contents'
complete -c monodis -l param -d 'Include Param table contents'
complete -c monodis -l parconst -d 'Include GenericParameterConstraint table contents'
complete -c monodis -l property -d 'Include Property table contents'
complete -c monodis -l propertymap -d 'Include PropertyMap table contents'
complete -c monodis -l standalonesig -d 'Include StandAloneSig table contents'
complete -c monodis -l typedef -d 'Include TypeDef table contents'
complete -c monodis -l typespec -d 'Include TypeRef table contents'
complete -c monodis -l blob -d 'Use hex for entire contents of the blob stream'
complete -c monodis -l strings -d 'Include Strings table contents'
complete -c monodis -l userstrings -d 'Include User-Strings heap contents'
