complete --command monop --short-option r --description 'Specifies the assembly to use for looking up the type'
complete --command monop --short-option a --description 'Renders all of the types in the specified assembly'
complete --command monop --short-option s --short-option k  --long-option search --description 'Searches through all known assemblies for types containing \'class\''
complete --command monop --long-option refs --description 'Print a list of the referenced assemblies for an assembly.'
complete --command monop --short-option f --long-option filter-obsolete --description 'Do not show obsolete types and members'
complete --command monop --short-option d --long-option declared-only --description 'Only show members declared in the type'
complete --command monop --short-option p --long-option private --description 'Show private members'
complete --command monop --long-option runtime-version --description 'Print runtime version'
complete --command monop --old-option xa --description 'Set the lookup path to the Xamarin.Android directory'
complete --command monop --old-option xi --description 'Set the lookup path to the Xamarin.iOS directory'
