complete -c nc.traditional -s c -r -d "specify shell commands to exec after connect"
complete -c nc.traditional -s e -r -d "specify filename to exec after connect"
complete -c nc.traditional -s g -x -d "source-routing hop point[s], up to 8"
complete -c nc.traditional -s G -x -d "source-routing pointer: 4, 8, 12, ..."
complete -c nc.traditional -s h -d "display help"
complete -c nc.traditional -s i -x -d "delay interval for lines sent, ports scanned"
complete -c nc.traditional -s l -d "listen mode, for inbound connects"
complete -c nc.traditional -s n -d "numeric-only IP addresses, no DNS"
complete -c nc.traditional -s o -r -d "hex dump of traffic"
complete -c nc.traditional -s p -x -d "local port number (port numbers can be individual or ranges: lo-hi [inclusive])"
complete -c nc.traditional -s q -x -d "after EOF on stdin, wait the specified number of seconds and then quit"
complete -c nc.traditional -s b -d "allow UDP broadcasts"
complete -c nc.traditional -s r -d "randomize local and remote ports"
complete -c nc.traditional -s s -x -d "local source address"
complete -c nc.traditional -s t -d "enable telnet negotiation"
complete -c nc.traditional -s u -d "UDP mode"
complete -c nc.traditional -s v -d "verbose [use twice to be more verbose]"
complete -c nc.traditional -s w -x -d "timeout for connects and final net reads"
complete -c nc.traditional -s C -d "Send CRLF as line-ending"
complete -c nc.traditional -s z -d "zero-I/O mode [used for scanning]"
complete -c nc.traditional -s T -x -a "Minimize-Delay Maximize-Throughput Maximize-Reliability Minimize-Cost" -x -d "set TOS flag"
