complete -c ng -f -d "The Angular CLI"

complete -c ng -n __fish_use_subcommand -a "add" -d "Adds support for an external library to your project."
complete -c ng -n __fish_use_subcommand -a "analytics" -d "Configures the gathering of Angular CLI usage metrics. See https://angular.io/cli/usage-analytics-gathering."
complete -c ng -n __fish_use_subcommand -a "build" -d "Compiles an Angular app into an output directory named dist/ at the given output path. Must be executed from within a workspace directory."
complete -c ng -n __fish_use_subcommand -a "config" -d "Retrieves or sets Angular configuration values in the angular.json file for the workspace."
complete -c ng -n __fish_use_subcommand -a "deploy" -d "Invokes the deploy builder for a specified project or for the default project in the workspace."
complete -c ng -n __fish_use_subcommand -a "doc" -d "Opens the official Angular documentation (angular.io) in a browser, and searches for a given keyword."
complete -c ng -n __fish_use_subcommand -a "e2e" -d "Builds and serves an Angular app, then runs end-to-end tests."
complete -c ng -n __fish_use_subcommand -a "extract-i18n" -d "Extracts i18n messages from source code."
complete -c ng -n __fish_use_subcommand -a "make-this-awesome" -d ""
complete -c ng -n __fish_use_subcommand -a "generate" -d "Generates and/or modifies files based on a schematic."
complete -c ng -n __fish_use_subcommand -a "help" -d "Lists available commands and their short descriptions."
complete -c ng -n __fish_use_subcommand -a "lint" -d "Runs linting tools on Angular app code in a given project folder."
complete -c ng -n __fish_use_subcommand -a "new" -d "Creates a new workspace and an initial Angular application."
complete -c ng -n __fish_use_subcommand -a "run" -d "Runs an Architect target with an optional custom builder configuration defined in your project."
complete -c ng -n __fish_use_subcommand -a "serve" -d "Builds and serves your app, rebuilding on file changes."
complete -c ng -n __fish_use_subcommand -a "test" -d "Runs unit tests in a project."
complete -c ng -n __fish_use_subcommand -a "update" -d "Updates your application and its dependencies. See https://update.angular.io/"
complete -c ng -n __fish_use_subcommand -a "version" -d "Outputs Angular CLI version."
