complete -c nu -s h -l help -d 'Display help and exit'
complete -c nu -s v -l version -d 'Display version and exit'

complete -c nu -l stdin -d 'Redirect stdin'
complete -c nu -s l -l login -d 'Use login shell'
complete -c nu -s i -l interactive -d 'Use interactive mode'
complete -c nu -l testbin -d 'Run internal test binary and exit'
complete -c nu -s c -l commands -d 'Run commands and exit'
complete -c nu -l config -d 'Specify config'
complete -c nu -l env-config -d 'Specify environment config'
complete -c nu -x -l log-level -a 'error warn info debug trace' -d 'Specify log level'
complete -c nu -x -l log-target -a 'stdout stderr' -d 'Specify log output target'
complete -c nu -s e -l execute -d 'Run commands and exit and fall in interactive mode'
complete -c nu -s t -l threads -d 'Thread count for multithreading'
complete -c nu -s m -l table-mode -d 'Use table mode'
complete -c nu -l plugin-config -d 'Specify plugin signature file'
