complete -c pacman-key -s a -l add -d 'Add or update keys from <file>'
complete -c pacman-key -l config -d 'Use an alternate config <file>'
complete -c pacman-key -s d -l delete -d 'Remove the <keys> from the keyring'
complete -c pacman-key -s e -l export -d 'Export <keys> to stdout'
complete -c pacman-key -l edit-key -d 'Present a menu on specified <keys>'
complete -c pacman-key -s f -l finger -d 'List a fingerprint for each specified <key>'
complete -c pacman-key -l gpgdir -d 'Alternate home <dir> for GnuPG'
complete -c pacman-key -s h -l help -d 'Output syntax and command line options'
complete -c pacman-key -l import -d 'Imports keys from <dir>/pubring.gpg'
complete -c pacman-key -l import-trustdb -d 'Imports ownertrust values from <dir>/trustdb.gpg'
complete -c pacman-key -l init -d 'Initialize the keyring'
complete -c pacman-key -l keyserver -d 'Use the specified <keyserver>'
complete -c pacman-key -s l -l list-keys -d 'Lists all or specified <keys> from the keyring'
complete -c pacman-key -l list-sigs -d 'Same as --list-keys, but with signatures'
complete -c pacman-key -l lsign-key -d 'Locally sign the given <key>'
complete -c pacman-key -s r -l recv-keys -d 'Equivalent to --recv-keys in GnuPG'
complete -c pacman-key -l refresh-keys -d 'Equivalent to --refresh-keys in GnuPG'
complete -c pacman-key -l populate -d 'Reload the default keys'
complete -c pacman-key -s u -l updatedb -d 'Equivalent to --check-trustdb in GnuPG'
complete -c pacman-key -s v -l verify -d 'Verify the given <signature> file'
complete -c pacman-key -s V -l version -d 'Displays the program version'
