complete -c pbget -l abs -d 'Use the ABS tree'
complete -c pbget -l arch -d 'Set the desired package architecture'
complete -c pbget -l aur -d 'Search the AUR'
complete -c pbget -l aur-only -d 'Only search the AUR'
complete -c pbget -l dir -d 'Set the output directory'
complete -c pbget -l help -d 'Display this message'
complete -c pbget -l upgradable -d 'Search for upgradable packages'
complete -c pbget -l testing -d 'Search the ABS testing branches'
