# General options:
complete -c pg_restore -s d -l dbname -x -a '(__fish_complete_pg_database)' -d "connect to database name"
complete -c pg_restore -s f -l file -a '-' -r -d "output file name (- for stdout)"
complete -c pg_restore -s F -l format -x -a "c d t" -d "backup file format (should be automatic)"
complete -c pg_restore -s l -l list -d "print summarized TOC of the archive"
complete -c pg_restore -s v -l verbose -d "verbose mode"
complete -c pg_restore -s V -l version -d "output version information, then exit"
complete -c pg_restore -s '?' -l help -d "show help, then exit"

# Options controlling the restore:
complete -c pg_restore -s a -l data-only -d "restore only the data, no schema"
complete -c pg_restore -s c -l clean -d "clean (drop) database objects before recreating"
complete -c pg_restore -s C -l create -d "create the target database"
complete -c pg_restore -s e -l exit-on-error -d "exit on error, default is to continue"
complete -c pg_restore -s I -l index -x -d "restore named index"
complete -c pg_restore -s j -l jobs -x -d "use this many parallel jobs to restore"
complete -c pg_restore -s L -l use-list -r -d "use table of contents from this file for selecting/ordering output"
complete -c pg_restore -s n -l schema -x -d "restore only objects in this schema"
complete -c pg_restore -s N -l exclude-schema -x -d "do not restore objects in this schema"
complete -c pg_restore -s O -l no-owner -d "skip restoration of object ownership"
complete -c pg_restore -s P -l function -x -d "restore named function"
complete -c pg_restore -s s -l schema-only -d "restore only the schema, no data"
complete -c pg_restore -s S -l superuser -x -a '(__fish_complete_pg_user)' -d "superuser user name to use for disabling triggers"
complete -c pg_restore -s t -l table -x -d "restore named relation (table, view, etc.)"
complete -c pg_restore -s T -l trigger -x -d "restore named trigger"
complete -c pg_restore -s x -l no-privileges -d "skip restoration of access privileges (grant/revoke)"
complete -c pg_restore -s 1 -l single-transaction -d "restore as a single transaction"
complete -c pg_restore -l disable-triggers -d "disable triggers during data-only restore"
complete -c pg_restore -l enable-row-security -d "enable row security"
complete -c pg_restore -l if-exists -d "use IF EXISTS when dropping objects"
complete -c pg_restore -l no-comments -d "do not restore comments"
complete -c pg_restore -l no-data-for-failed-tables -d "do not restore data of tables that could not be created"
complete -c pg_restore -l no-publications -d "do not restore publications"
complete -c pg_restore -l no-security-labels -d "do not restore security labels"
complete -c pg_restore -l no-subscriptions -d "do not restore subscriptions"
complete -c pg_restore -l no-tablespaces -d "do not restore tablespace assignments"
complete -c pg_restore -l section -x -d "restore named section (pre-data, data, or post-data)"
complete -c pg_restore -l strict-names -d "require table and/or schema include patterns to match at least one entity each"
complete -c pg_restore -l use-set-session-authorization -d "use SET SESSION AUTHORIZATION commands instead of ALTER OWNER commands to set ownership"

# Connection options:
complete -c pg_restore -s h -l host -x -a '(__fish_print_hostnames)' -d "database server host or socket directory"
complete -c pg_restore -s p -l port -x -d "database server port number"
complete -c pg_restore -s U -l username -x -a '(__fish_complete_pg_user)' -d "connect as specified database user"
complete -c pg_restore -s w -l no-password -d "never prompt for password"
complete -c pg_restore -s W -l password -d "force password prompt (should happen automatically)"
complete -c pg_restore -l role -x -d "do SET ROLE before restore"
