complete -c python -s c -x --description "Execute argument as command"
complete -c python -s d --description "Debug on"
complete -c python -s E --description "Ignore environment variables"
complete -c python -s h --description "Display help and exit"
complete -c python -s i --description "Interactive mode after executing commands"
complete -c python -s O --description "Enable optimizations"
complete -c python -s Q -x -a "old new" --description "Division control"
complete -c python -s S --description "Disable import of site module"
complete -c python -s t --description "Warn on mixed tabs and spaces"
complete -c python -s u --description "Unbuffered input and output"
complete -c python -s v --description "Verbose mode"
complete -c python -s V --description "Display version and exit"
complete -c python -s W -x --description "Warning control" -a "ignore default all module once error"
complete -c python -s x --description "Ignore first line of input"
