# Define the completions for the qjsc command

complete -c qjsc -s c -d 'Only output bytecode in a C file'
complete -c qjsc -s e -d 'Output main() and bytecode in a C file (default = executable output)'
complete -c qjsc -s o -r -d 'Set the output filename'
complete -c qjsc -s N -r -d 'Set the C name of the generated data'
complete -c qjsc -s m -d 'Compile as Javascript module (default=autodetect)'
complete -c qjsc -s D -r -d 'Compile a dynamically loaded module or worker'
complete -c qjsc -s M -r -d 'Add initialization code for an external C module'
complete -c qjsc -s x -d 'Byte swapped output'
complete -c qjsc -s p -r -d 'Set the prefix of the generated C names'
complete -c qjsc -s S -r -d 'Set the maximum stack size to 'n' bytes (default=262144)'
complete -c qjsc -o -flto -d 'Use link time optimization'
complete -c qjsc -o -fbignum -d 'Enable bignum extensions'
complete -c qjsc -o -fno-date -d 'Disable the date extension'
complete -c qjsc -o -fno-eval -d 'Disable the eval extension'
complete -c qjsc -o -fno-string-normalize -d 'Disable the string normalize extension'
complete -c qjsc -o -fno-regexp -d 'Disable the regexp extension'
complete -c qjsc -o -fno-json -d 'Disable the JSON extension'
complete -c qjsc -o -fno-proxy -d 'Disable the proxy extension'
complete -c qjsc -o -fno-map -d 'Disable the Map extension'
complete -c qjsc -o -fno-typedarray -d 'Disable the Typed Array extension'
complete -c qjsc -o -fno-promise -d 'Disable the Promise extension'
complete -c qjsc -o -fno-module-loader -d 'Disable the module loader extension'
complete -c qjsc -o -fno-bigint -d 'Disable the BigInt extension'
