# completions for quilt version 0.46 or similar
complete -c quilt -s h -d 'Show help'
complete -c quilt -l version -d 'Show version'
complete -c quilt -l quiltrc -r --no-file -d 'Config file to use'
complete -c quilt -l trace -r --no-file -d 'Trace internal shell commands (bash -x)'

complete -c quilt -a add -r -d 'Add files to patch'
complete -c quilt -a annotate -r -d 'Show which patches modify which lines in file'
complete -c quilt -a applied -r -d 'List applied patches in the stack'
complete -c quilt -a delete -r -d 'Remove patch from the series'
complete -c quilt -a diff -r -d 'Diff files in patch'
complete -c quilt -a edit -r -d 'Edit files in $EDITOR'
complete -c quilt -a files -r -d 'Lists files changed by patch'
complete -c quilt -a fold -r -d 'Integrate patch from stdin into the topmost patch'
complete -c quilt -a fork -r --no-file -d 'Fork the topmost patch'
complete -c quilt -a graph -r --no-file -d 'Visualize patch dependencies using dot'
complete -c quilt -a grep -r --no-file -d 'Search through source files'
complete -c quilt -a header -r --no-file -d 'Print/change the header of patch'
complete -c quilt -a import -r -d 'Import external patches'
complete -c quilt -a mail -r -d 'Create or send mail messages from patches'
complete -c quilt -a new -r -d 'Start a new topmost patch'
complete -c quilt -a next -r -d 'Name of patch after the topmost/given patch'
complete -c quilt -a patches -r -d 'List patches that modify the file(s)'
complete -c quilt -a pop -r -d 'Unapply patches from the stack'
complete -c quilt -a previous -r -d 'Name of patch before the topmost/given patch'
complete -c quilt -a push -r -d 'Apply patches from the series'
complete -c quilt -a refresh -r -d 'Update patch with changes from source'
complete -c quilt -a remove -r -d 'Remove files from the patch'
complete -c quilt -a rename -r -d 'Rename the topmost/given patch'
complete -c quilt -a series -r --no-file -d 'List all patches in the series'
complete -c quilt -a setup -r -d 'Initializes a source tree from an rpm spec or a quilt series'
complete -c quilt -a snapshot -r --no-file -d 'Take a snapshot of the working state'
complete -c quilt -a top -d 'Name of topmost patch in the stack'
complete -c quilt -a unapplied -r -d 'List unapplied patches in the series'
complete -c quilt -a upgrade -d 'Upgrade meta-data from older version of quilt'
