# completions for quilt version 0.46 or similar
complete -c quilt -s h -d "show help"
complete -c quilt -l version -d "show version"
complete -c quilt -l quiltrc -r --no-file -d "specify the file to Run Control file to use"
complete -c quilt -l trace -r --no-file -d "Runs the command in bash trace mode (-x). For internal debugging"

complete -c quilt -a add -r -d "Add one or more files to the topmost or named patch"
complete -c quilt -a annotate -r -d "Print an annotated listing of the specified file"
complete -c quilt -a applied -r -d "Print a list of applied patches"
complete -c quilt -a delete -r -d "Remove the specified or topmost patch from the series file"
complete -c quilt -a diff -r -d "Produces a diff of the specified file(s) in the topmost  or  specified patch"
complete -c quilt -a edit -r -d "Edit the specified file(s) in $EDITOR"
complete -c quilt -a files -r -d "Print the list of files that the topmost or specified patch changes"
complete -c quilt -a fold -r -d "Integrate the patch read  from  standard  input  into  the  topmost patch"
complete -c quilt -a fork -r --no-file -d " Fork the topmost patch"
complete -c quilt -a graph -r --no-file -d "Generate  a  dot(1) directed graph showing the dependencies between applied patches"
complete -c quilt -a grep -r --no-file -d "Grep through the source files, recursively, skipping patches and quilt meta-information"
complete -c quilt -a header -r --no-file -d " Print or change the header of the topmost or specified patch"
complete -c quilt -a import -r -d "Import external patches"
complete -c quilt -a mail -r -d "Create  mail  messages  from all patches in the series file, and either store or send them"
complete -c quilt -a new -r -d "Create a new patch with the specified file name, and  insert  it after the topmost patch"
complete -c quilt -a next -r -d "Print  the  name  of  the next patch after the specified or topmost patch in the series file"
complete -c quilt -a patches -r -d "Print the list of patches that modify the specified file"
complete -c quilt -a pop -r -d "Remove  patch(es) from the stack of applied  patches"
complete -c quilt -a previous -r -d "Print the name of the previous patch before the specified or topmost patch in the series file"
complete -c quilt -a push -r -d "Apply patch(es) from the series file"
complete -c quilt -a refresh -r -d "Refreshes the specified patch, or the topmost patch by default"
complete -c quilt -a remove -r -d "Remove one or more files from the topmost or named patch"
complete -c quilt -a rename -r -d "Rename the topmost or named patch"
complete -c quilt -a series -r --no-file -d "Print the names of all patches in the series file"
complete -c quilt -a setup -r -d " Initializes a source tree from an rpm spec file or a quilt series file"
complete -c quilt -a snapshot -r --no-file -d " Take a snapshot of the current working state"
complete -c quilt -a top -d "Print the name of the topmost patch on the current stack of applied patches"
complete -c quilt -a unapplied -r -d "Print a list of patches that are not applied, or all patches that follow the specified patch in the series file"
complete -c quilt -a upgrade -d "Upgrade the meta-data in a working tree from an old version of quilt to the current version"
