complete -c rc -s c -d "Commands to execute"
complete -c rc -s d -d "Do not ignore SIGQUIT or SIGTERM"
complete -c rc -s e -d "Exit on command failure"
complete -c rc -s i -d "Use interactive mode"
complete -c rc -s I -d "Do not interactive mode"
complete -c rc -s l -d "Use login shell"
complete -c rc -s n -d "Do not execute commands, just parse them"
complete -c rc -s o -d "Do not allow open /dev/null on 0, 1, 2 descriptors"
complete -c rc -s p -d "Do not initialize from environment"
complete -c rc -s s -d "Read from stdin"
complete -c rc -s v -d "Echo input to stderr"
complete -c rc -s x -d "Echo command to stderr"
