complete -c rename -s h -l help -d 'See a synopsis'
complete -c rename -l man -d 'Browse the manpage'
complete -c rename -s 0 -l null -d 'Split on NUL bytes'
complete -c rename -s f -l force -d 'Rename over existing files'
complete -c rename -s g -l glob -d 'Glob filename arguments'
complete -c rename -s i -l interactive -d 'Confirm every action'
complete -c rename -s k -l backwards -l reverse-order -d 'Process last file first'
complete -c rename -s l -l symlink -d 'Symlink instead of renaming'
complete -c rename -s L -l hardlink -d 'Hardlink instead of renaming'
complete -c rename -s M -l use -d 'Like perl -M'
complete -c rename -s n -l dry-run -l just-print -d 'Only show what would be renamed'
complete -c rename -o N/--counter-format -d 'Format and set $N per template'
complete -c rename -s p -l mkpath -l make-dirs -d 'Create non-existent dirs'
complete -c rename -l stdin -l no-stdin -d 'Always/never read list of files from STDIN'
complete -c rename -s T -l transcode -d 'Transcode filenames'
complete -c rename -s v -l verbose -d 'Print more information'
complete -c rename -s a -l append -d 'Append STRING to each filename'
complete -c rename -s A -l prepend -d 'Prepend STRING to each filename'
complete -c rename -s c -l lower-case -d 'Convert to all lowercase'
complete -c rename -s C -l upper-case -d 'Convert to all uppercase'
complete -c rename -s e -l expr -d 'Perl expression'
complete -c rename -s P -l pipe -d 'Pass filenames to external command'
complete -c rename -s s -l subst -d 'Simple text substitution'
complete -c rename -s S -l subst-all -d 'Like -s, but substitutes all matches'
complete -c rename -s x -l remove-extension -d 'Remove extension'
complete -c rename -s X -l keep-extension -d 'Save and remove extension'
complete -c rename -s z -l sanitize -d 'Shortcut for --nows --noctrl --nometa --trim'
complete -c rename -l camelcase -d 'Capitalise each word in the filename'
complete -c rename -l urlesc -d 'Decode URL-escaped filenames'
complete -c rename -l nows -d 'Replace all whitespace with underscores'
complete -c rename -l rews -d 'Replace all underscores with whitespace'
complete -c rename -l noctrl -d 'Replace all control chars with underscores'
complete -c rename -l nometa -d 'Replace all shell meta-chars with underscores'
