complete -c rmob -n "__fish_use_subcommand" -l git-copirates-file
complete -c rmob -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c rmob -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c rmob -n "__fish_use_subcommand" -f -a "embark" -d 'Embark on rmob fer this git repo, call this once t\' use rmob in yer git repo'
complete -c rmob -n "__fish_use_subcommand" -f -a "sail" -d 'Start pairin\' or mobbin\' by passin\' a list of yer co-pirates te sail wit\''
complete -c rmob -n "__fish_use_subcommand" -f -a "solo" -d 'Sail solo (short fer `rmob sail solo`)'
complete -c rmob -n "__fish_use_subcommand" -f -a "copirate" -d 'Edit copirates list'
complete -c rmob -n "__fish_use_subcommand" -f -a "generate-shell-completions" -d 'Generates autocompletion config for shell'
complete -c rmob -n "__fish_use_subcommand" -f -a "prepare-commit-msg" -d 'Called from the git hook only'
complete -c rmob -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c rmob -n "__fish_seen_subcommand_from embark" -s h -l help -d 'Prints help information'
complete -c rmob -n "__fish_seen_subcommand_from embark" -s V -l version -d 'Prints version information'
complete -c rmob -n "__fish_seen_subcommand_from sail" -s h -l help -d 'Prints help information'
complete -c rmob -n "__fish_seen_subcommand_from sail" -s V -l version -d 'Prints version information'
complete -c rmob -n "__fish_seen_subcommand_from solo" -s h -l help -d 'Prints help information'
complete -c rmob -n "__fish_seen_subcommand_from solo" -s V -l version -d 'Prints version information'
complete -c rmob -n "__fish_seen_subcommand_from copirate" -s h -l help -d 'Prints help information'
complete -c rmob -n "__fish_seen_subcommand_from copirate" -s V -l version -d 'Prints version information'
complete -c rmob -n "__fish_seen_subcommand_from copirate" -f -a "enlist" -d 'Adds a co-pirate to the list'
complete -c rmob -n "__fish_seen_subcommand_from copirate" -f -a "keelhaul" -d 'Removes co-pirate from the list'
complete -c rmob -n "__fish_seen_subcommand_from copirate" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c rmob -n "__fish_seen_subcommand_from enlist" -s h -l help -d 'Prints help information'
complete -c rmob -n "__fish_seen_subcommand_from enlist" -s V -l version -d 'Prints version information'
complete -c rmob -n "__fish_seen_subcommand_from keelhaul" -s h -l help -d 'Prints help information'
complete -c rmob -n "__fish_seen_subcommand_from keelhaul" -s V -l version -d 'Prints version information'
complete -c rmob -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c rmob -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c rmob -n "__fish_seen_subcommand_from generate-shell-completions" -s h -l help -d 'Prints help information'
complete -c rmob -n "__fish_seen_subcommand_from generate-shell-completions" -s V -l version -d 'Prints version information'
complete -c rmob -n "__fish_seen_subcommand_from prepare-commit-msg" -s h -l help -d 'Prints help information'
complete -c rmob -n "__fish_seen_subcommand_from prepare-commit-msg" -s V -l version -d 'Prints version information'
complete -c rmob -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c rmob -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
