#Completions for ruby
complete -c ruby -s 0 -d 'Specify record separator'
complete -c ruby -s a -d 'Turn on autosplit mode'
complete -c ruby -s c -d 'Check syntax'
complete -c ruby -s K -d 'Kanji code-set'
complete -c ruby -s d -l debug -d Debugger
complete -c ruby -s e -x -d 'Execute command'
complete -c ruby -s h -l help -d 'Display help and exit'
complete -c ruby -s F -d 'Set regexp used to split input'
complete -c ruby -s i -d 'Edit files in-place'
complete -c ruby -s I -d 'Include path'
complete -c ruby -s l -d 'Automatic line ending processing'
complete -c ruby -s n -d 'Loop script'
complete -c ruby -s p -d 'Loop script, print $_'
complete -c ruby -s r -r -d 'Require file'
complete -c ruby -s s -d 'Define custom switches'
complete -c ruby -s S -d 'Search $PATH for script'
complete -c ruby -s T -d 'Taint checking'
complete -c ruby -s v -l verbose -d 'Verbose mode'
complete -c ruby -s w -d 'Verbose mode without message'
complete -c ruby -l version -d 'Display version and exit'
complete -c ruby -s x -d 'Extract script'
complete -c ruby -s X -x -a '(__fish_complete_directories (commandline -ct))' -d Directory
complete -c ruby -s y -l yydebug -d 'Compiler debug mode'
