complete -c sbcl -l help -d "Print this message and exit."
complete -c sbcl -l version -d "Print version information and exit."
complete -c sbcl -l core -d "Use the specified core file instead of the default."
complete -c sbcl -l dynamic-space-size -d "Size of reserved dynamic space in megabytes."
complete -c sbcl -l control-stack-size -d "Size of reserved control stack in megabytes."
complete -c sbcl -l tls-limit -d "Maximum number of thread-local symbols."
complete -c sbcl -l sysinit -d "System-wide init-file to use instead of default."
complete -c sbcl -l userinit -d "Per-user init-file to use instead of default."
complete -c sbcl -l no-sysinit -d "Inhibit processing of any system-wide init-file."
complete -c sbcl -l no-userinit -d "Inhibit processing of any per-user init-file."
complete -c sbcl -l disable-debugger -d "Invoke sb-ext:disable-debugger."
complete -c sbcl -l noprint -d "Run a Read-Eval Loop without printing results."
complete -c sbcl -l script -d "Skip #! line, disable debugger, avoid verbosity."
complete -c sbcl -l quit -d "Exit with code 0 after option processing."
complete -c sbcl -l non-interactive -d "Sets both --quit and --disable-debugger."
complete -c sbcl -l eval -d "Form to eval when processing this option."
complete -c sbcl -l load -d "File to load when processing this option."
