# screencapture – capture images from the screen and save them to a file (man 1 screencapture)

# ── flags ─────────────────────────────────────────────────────────────────────
complete -c screencapture -s c -d 'Force screen capture to go to the clipboard'
complete -c screencapture -s b -d 'Capture Touch Bar (non-interactive modes only)'
complete -c screencapture -s C -d 'Capture the cursor as well as the screen (non-interactive only)'
complete -c screencapture -s d -d 'Display errors to the user graphically'
complete -c screencapture -s i -d 'Capture screen interactively, by selection or window'
complete -c screencapture -s m -d 'Only capture the main monitor (undefined if -i is set)'
complete -c screencapture -s D -x -d 'Capture from the specified display number (1=main, 2=secondary, …)'
complete -c screencapture -s o -d 'In window capture mode, do not capture the shadow of the window'
complete -c screencapture -s p -d 'Use default settings; the files argument will be ignored'
complete -c screencapture -s M -d 'Open the taken picture in a new Mail message'
complete -c screencapture -s P -d 'Open the taken picture in Preview or QuickTime Player (video)'
complete -c screencapture -s B -x -d 'Open in the app matching the given bundle ID'
complete -c screencapture -s s -d 'Only allow mouse selection mode'
complete -c screencapture -s S -d 'In window capture mode, capture the screen instead of the window'
complete -c screencapture -s w -d 'Only allow window selection mode'
complete -c screencapture -s W -d 'Start interaction in window selection mode'
complete -c screencapture -s x -d 'Do not play sounds'
complete -c screencapture -s a -d 'Do not capture attached windows'
complete -c screencapture -s r -d 'Do not add screen DPI metadata to the captured file'
complete -c screencapture -s l -x -d 'Capture the window with the given window ID'
complete -c screencapture -s R -x -d 'Capture rectangle specified as x,y,width,height'
complete -c screencapture -s v -d 'Capture a video recording of the screen'
complete -c screencapture -s V -x -d 'Capture a video recording of the screen for the given number of seconds'
complete -c screencapture -s G -x -d 'Capture audio during video using the audio source with the given ID'
complete -c screencapture -s g -d 'Capture audio during video using the default input'
complete -c screencapture -s k -d 'Show clicks in video recordings'
complete -c screencapture -s U -d 'Show interactive toolbar in interactive mode'
complete -c screencapture -s u -d 'Present UI after screencapture is complete (files argument ignored)'
complete -c screencapture -s T -x -d 'Take the picture after a delay of the given number of seconds (default 5)'

# -t <format>: image format values
complete -c screencapture -s t -x -d 'Image format to create (default: png)'
complete -c screencapture -n '__fish_seen_argument -s t' -f -a png -d 'PNG image'
complete -c screencapture -n '__fish_seen_argument -s t' -f -a jpg -d 'JPEG image'
complete -c screencapture -n '__fish_seen_argument -s t' -f -a jpeg -d 'JPEG image'
complete -c screencapture -n '__fish_seen_argument -s t' -f -a pdf -d 'PDF document'
complete -c screencapture -n '__fish_seen_argument -s t' -f -a tiff -d 'TIFF image'
complete -c screencapture -n '__fish_seen_argument -s t' -f -a bmp -d 'BMP image'
complete -c screencapture -n '__fish_seen_argument -s t' -f -a gif -d 'GIF image'

# -J <style>: interactive capture style
complete -c screencapture -s J -x -d 'Set the starting style of interactive capture'
complete -c screencapture -n '__fish_seen_argument -s J' -f -a selection -d 'Start in mouse-selection mode'
complete -c screencapture -n '__fish_seen_argument -s J' -f -a window -d 'Start in window-selection mode'
complete -c screencapture -n '__fish_seen_argument -s J' -f -a video -d 'Start in video-recording mode'
