complete -c scrot -s h -l help -d 'Display help and exit'
complete -c scrot -s v -l version -d 'Display version information and exit'
complete -c scrot -s b -l border -d 'When selecting a window, grab wm border too'
complete -c scrot -s c -l count -d 'Display a countdown when used with delay'
complete -c scrot -s d -l delay -d 'Wait NUMBER of seconds before taking a shot'
complete -c scrot -s e -l exec -d 'Execute APPLICATION on the saved image'
complete -c scrot -s q -l quality -d 'Image quality [1-100]'
complete -c scrot -s m -l multidisp -d 'Grab shot from multiple heads'
complete -c scrot -s s -l select -d 'Select a window or rectangle with the mouse'
complete -c scrot -s t -l thumb -d 'Generate thumbnail PERCENT of original'
