complete -c stat -s L -l dereference     -d 'follow links'
complete -c stat -s f -l file-system     -d 'display file system status instead of file status'
complete -c stat -s c -l format -x       -d 'use the specified FORMAT instead of the default; output a newline after each use of FORMAT'
complete -c stat -l printf -x            -d 'like --format, but interpret backslash escapes, and do not output a mandatory trailing newline.  If you want a newline, include \n in FORMAT'
complete -c stat -s t -l terse           -d 'print the information in terse form'
complete -c stat -l help     -d 'display this help and exit'
complete -c stat -l version  -d 'output version information and exit'
