
#
# Completions for the svn command
# This file was autogenerated by the file make_mercurial_completions.fish
# which is shipped with the fish source code
#

#
# Completions from commandline
#


#
# subcommands
#

complete -c svn -n '__fish_use_subcommand' -x -a add --description 'Put files and directories under version control, scheduling'
complete -c svn -n '__fish_use_subcommand' -x -a blame --description 'Output the content of specified files or'
complete -c svn -n '__fish_use_subcommand' -x -a praise --description 'Output the content of specified files or'
complete -c svn -n '__fish_use_subcommand' -x -a annotate --description 'Output the content of specified files or'
complete -c svn -n '__fish_use_subcommand' -x -a ann --description 'Output the content of specified files or'
complete -c svn -n '__fish_use_subcommand' -x -a cat --description 'Output the content of specified files or URLs'
complete -c svn -n '__fish_use_subcommand' -x -a checkout --description 'Check out a working copy from a repository'
complete -c svn -n '__fish_use_subcommand' -x -a co --description 'Check out a working copy from a repository'
complete -c svn -n '__fish_use_subcommand' -x -a cleanup --description 'Recursively clean up the working copy, removing locks, resuming'
complete -c svn -n '__fish_use_subcommand' -x -a commit --description 'Send changes from your working copy to the repository'
complete -c svn -n '__fish_use_subcommand' -x -a ci --description 'Send changes from your working copy to the repository'
complete -c svn -n '__fish_use_subcommand' -x -a copy --description 'Duplicate something in working copy or repository, remembering history'
complete -c svn -n '__fish_use_subcommand' -x -a cp --description 'Duplicate something in working copy or repository, remembering history'
complete -c svn -n '__fish_use_subcommand' -x -a delete --description 'Remove files and directories from version control'
complete -c svn -n '__fish_use_subcommand' -x -a del --description 'Remove files and directories from version control'
complete -c svn -n '__fish_use_subcommand' -x -a remove --description 'Remove files and directories from version control'
complete -c svn -n '__fish_use_subcommand' -x -a rm --description 'Remove files and directories from version control'
complete -c svn -n '__fish_use_subcommand' -x -a diff --description 'Display the differences between two paths'
complete -c svn -n '__fish_use_subcommand' -x -a di --description 'Display the differences between two paths'
complete -c svn -n '__fish_use_subcommand' -x -a export --description 'Create an unversioned copy of a tree'
complete -c svn -n '__fish_use_subcommand' -x -a help --description 'Describe the usage of this program or its subcommands'
complete -c svn -n '__fish_use_subcommand' -x -a ? --description 'Describe the usage of this program or its subcommands'
complete -c svn -n '__fish_use_subcommand' -x -a h --description 'Describe the usage of this program or its subcommands'
complete -c svn -n '__fish_use_subcommand' -x -a import --description 'Commit an unversioned file or tree into the repository'
complete -c svn -n '__fish_use_subcommand' -x -a info --description 'Display information about a local or remote item'
complete -c svn -n '__fish_use_subcommand' -x -a list --description 'List directory entries in the repository'
complete -c svn -n '__fish_use_subcommand' -x -a ls --description 'List directory entries in the repository'
complete -c svn -n '__fish_use_subcommand' -x -a lock --description 'Lock working copy paths or URLs in the repository, so that'
complete -c svn -n '__fish_use_subcommand' -x -a log --description 'Show the log messages for a set of revision(s) and/or file(s)'
complete -c svn -n '__fish_use_subcommand' -x -a merge --description 'Apply the differences between two sources to a working copy path'
complete -c svn -n '__fish_use_subcommand' -x -a mkdir --description 'Create a new directory under version control'
complete -c svn -n '__fish_use_subcommand' -x -a move --description 'Move and/or rename something in working copy or repository'
complete -c svn -n '__fish_use_subcommand' -x -a mv --description 'Move and/or rename something in working copy or repository'
complete -c svn -n '__fish_use_subcommand' -x -a rename --description 'Move and/or rename something in working copy or repository'
complete -c svn -n '__fish_use_subcommand' -x -a ren --description 'Move and/or rename something in working copy or repository'
complete -c svn -n '__fish_use_subcommand' -x -a propdel --description 'Remove a property from files, dirs, or revisions'
complete -c svn -n '__fish_use_subcommand' -x -a pdel --description 'Remove a property from files, dirs, or revisions'
complete -c svn -n '__fish_use_subcommand' -x -a pd --description 'Remove a property from files, dirs, or revisions'
complete -c svn -n '__fish_use_subcommand' -x -a propedit --description 'Edit a property with an external editor'
complete -c svn -n '__fish_use_subcommand' -x -a pedit --description 'Edit a property with an external editor'
complete -c svn -n '__fish_use_subcommand' -x -a pe --description 'Edit a property with an external editor'
complete -c svn -n '__fish_use_subcommand' -x -a propget --description 'Print the value of a property on files, dirs, or revisions'
complete -c svn -n '__fish_use_subcommand' -x -a pget --description 'Print the value of a property on files, dirs, or revisions'
complete -c svn -n '__fish_use_subcommand' -x -a pg --description 'Print the value of a property on files, dirs, or revisions'
complete -c svn -n '__fish_use_subcommand' -x -a proplist --description 'List all properties on files, dirs, or revisions'
complete -c svn -n '__fish_use_subcommand' -x -a plist --description 'List all properties on files, dirs, or revisions'
complete -c svn -n '__fish_use_subcommand' -x -a pl --description 'List all properties on files, dirs, or revisions'
complete -c svn -n '__fish_use_subcommand' -x -a propset --description 'Set the value of a property on files, dirs, or revisions'
complete -c svn -n '__fish_use_subcommand' -x -a pset --description 'Set the value of a property on files, dirs, or revisions'
complete -c svn -n '__fish_use_subcommand' -x -a ps --description 'Set the value of a property on files, dirs, or revisions'
complete -c svn -n '__fish_use_subcommand' -x -a resolved --description 'Remove \'conflicted\' state on working copy files or directories'
complete -c svn -n '__fish_use_subcommand' -x -a revert --description 'Restore pristine working copy file (undo most local edits)'
complete -c svn -n '__fish_use_subcommand' -x -a status --description 'Print the status of working copy files and directories'
complete -c svn -n '__fish_use_subcommand' -x -a stat --description 'Print the status of working copy files and directories'
complete -c svn -n '__fish_use_subcommand' -x -a st --description 'Print the status of working copy files and directories'
complete -c svn -n '__fish_use_subcommand' -x -a switch --description 'Update the working copy to a different URL'
complete -c svn -n '__fish_use_subcommand' -x -a sw --description 'Update the working copy to a different URL'
complete -c svn -n '__fish_use_subcommand' -x -a unlock --description 'Unlock working copy paths or URLs'
complete -c svn -n '__fish_use_subcommand' -x -a update --description 'Bring changes from the repository into the working copy'
complete -c svn -n '__fish_use_subcommand' -x -a up --description 'Bring changes from the repository into the working copy'


#
# Completions for the 'add' subcommand
#

complete -c svn -n 'contains \'add\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'add\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'
complete -c svn -n 'contains \'add\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'add\' (commandline -poc)' -l no-ignore --description 'Disregard default and svn:ignore property ignores'
complete -c svn -n 'contains \'add\' (commandline -poc)' -l auto-props --description 'Enable automatic properties'
complete -c svn -n 'contains \'add\' (commandline -poc)' -l no-auto-props --description 'Disable automatic properties'


#
# Completions for the 'blame' subcommand
#

complete -c svn -n 'contains \'blame\' (commandline -poc)' -l incremental --description 'Give output suitable for concatenation'
complete -c svn -n 'contains \'blame\' (commandline -poc)' -l xml --description 'Output in XML'
complete -c svn -n 'contains \'blame\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'blame\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'blame\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'blame\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'blame\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'praise' subcommand
#

complete -c svn -n 'contains \'praise\' (commandline -poc)' -l incremental --description 'Give output suitable for concatenation'
complete -c svn -n 'contains \'praise\' (commandline -poc)' -l xml --description 'Output in XML'
complete -c svn -n 'contains \'praise\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'praise\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'praise\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'praise\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'praise\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'annotate' subcommand
#

complete -c svn -n 'contains \'annotate\' (commandline -poc)' -l incremental --description 'Give output suitable for concatenation'
complete -c svn -n 'contains \'annotate\' (commandline -poc)' -l xml --description 'Output in XML'
complete -c svn -n 'contains \'annotate\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'annotate\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'annotate\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'annotate\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'annotate\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'ann' subcommand
#

complete -c svn -n 'contains \'ann\' (commandline -poc)' -l incremental --description 'Give output suitable for concatenation'
complete -c svn -n 'contains \'ann\' (commandline -poc)' -l xml --description 'Output in XML'
complete -c svn -n 'contains \'ann\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'ann\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'ann\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'ann\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'ann\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'cat' subcommand
#

complete -c svn -n 'contains \'cat\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'cat\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'cat\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'cat\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'cat\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'checkout' subcommand
#

complete -c svn -n 'contains \'checkout\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'checkout\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'checkout\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'checkout\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'checkout\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'
complete -c svn -n 'contains \'checkout\' (commandline -poc)' -l ignore-externals --description 'Ignore externals definitions'


#
# Completions for the 'co' subcommand
#

complete -c svn -n 'contains \'co\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'co\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'co\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'co\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'co\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'
complete -c svn -n 'contains \'co\' (commandline -poc)' -l ignore-externals --description 'Ignore externals definitions'


#
# Completions for the 'cleanup' subcommand
#

complete -c svn -n 'contains \'cleanup\' (commandline -poc)' -l diff3-cmd -x --description 'Use ARG as merge command'
complete -c svn -n 'contains \'cleanup\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'commit' subcommand
#

complete -c svn -n 'contains \'commit\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'commit\' (commandline -poc)' -l no-unlock --description 'Don\'t unlock the targets'
complete -c svn -n 'contains \'commit\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'commit\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'commit\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'commit\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'commit\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'commit\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'commit\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'commit\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'ci' subcommand
#

complete -c svn -n 'contains \'ci\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'ci\' (commandline -poc)' -l no-unlock --description 'Don\'t unlock the targets'
complete -c svn -n 'contains \'ci\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'ci\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'ci\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'ci\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'ci\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'ci\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'ci\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'ci\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'copy' subcommand
#

complete -c svn -n 'contains \'copy\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'copy\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'copy\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'copy\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'copy\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'copy\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'copy\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'copy\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'cp' subcommand
#

complete -c svn -n 'contains \'cp\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'cp\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'cp\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'cp\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'cp\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'cp\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'cp\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'cp\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'delete' subcommand
#

complete -c svn -n 'contains \'delete\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'delete\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'delete\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'delete\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'delete\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'delete\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'delete\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'delete\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'delete\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'delete\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'del' subcommand
#

complete -c svn -n 'contains \'del\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'del\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'del\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'del\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'del\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'del\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'del\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'del\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'del\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'del\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'remove' subcommand
#

complete -c svn -n 'contains \'remove\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'remove\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'remove\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'remove\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'remove\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'remove\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'remove\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'remove\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'remove\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'remove\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'rm' subcommand
#

complete -c svn -n 'contains \'rm\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'rm\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'rm\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'rm\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'rm\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'rm\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'rm\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'rm\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'rm\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'rm\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'diff' subcommand
#

complete -c svn -n 'contains \'diff\' (commandline -poc)' -l old -x --description 'Use ARG as the older target'
complete -c svn -n 'contains \'diff\' (commandline -poc)' -l new -x --description 'Use ARG as the newer target'
complete -c svn -n 'contains \'diff\' (commandline -poc)' -l diff-cmd -x --description 'Use ARG as diff command'
complete -c svn -n 'contains \'diff\' (commandline -poc)' -l no-diff-deleted --description 'Do not print differences for deleted files'
complete -c svn -n 'contains \'diff\' (commandline -poc)' -l notice-ancestry --description 'Notice ancestry when calculating differences'
complete -c svn -n 'contains \'diff\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'diff\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'diff\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'diff\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'diff\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'diff\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'di' subcommand
#

complete -c svn -n 'contains \'di\' (commandline -poc)' -l old -x --description 'Use ARG as the older target'
complete -c svn -n 'contains \'di\' (commandline -poc)' -l new -x --description 'Use ARG as the newer target'
complete -c svn -n 'contains \'di\' (commandline -poc)' -l diff-cmd -x --description 'Use ARG as diff command'
complete -c svn -n 'contains \'di\' (commandline -poc)' -l no-diff-deleted --description 'Do not print differences for deleted files'
complete -c svn -n 'contains \'di\' (commandline -poc)' -l notice-ancestry --description 'Notice ancestry when calculating differences'
complete -c svn -n 'contains \'di\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'di\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'di\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'di\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'di\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'di\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'export' subcommand
#

complete -c svn -n 'contains \'export\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'export\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'export\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'export\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'export\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'export\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'
complete -c svn -n 'contains \'export\' (commandline -poc)' -l native-eol -x --description 'Use a different EOL marker than the standard'
complete -c svn -n 'contains \'export\' (commandline -poc)' -l ignore-externals --description 'Ignore externals definitions'


#
# Completions for the 'help' subcommand
#

complete -c svn -n 'contains \'help\' (commandline -poc)' -l version --description 'Print client version info'
complete -c svn -n 'contains \'help\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the '?' subcommand
#

complete -c svn -n 'contains \'?\' (commandline -poc)' -l version --description 'Print client version info'
complete -c svn -n 'contains \'?\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'h' subcommand
#

complete -c svn -n 'contains \'h\' (commandline -poc)' -l version --description 'Print client version info'
complete -c svn -n 'contains \'h\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'import' subcommand
#

complete -c svn -n 'contains \'import\' (commandline -poc)' -l auto-props --description 'Enable automatic properties'
complete -c svn -n 'contains \'import\' (commandline -poc)' -l no-auto-props --description 'Disable automatic properties'
complete -c svn -n 'contains \'import\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'import\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'import\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'import\' (commandline -poc)' -l no-ignore --description 'Disregard default and svn:ignore property ignores'
complete -c svn -n 'contains \'import\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'import\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'import\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'import\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'import\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'info' subcommand
#

complete -c svn -n 'contains \'info\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'info\' (commandline -poc)' -l incremental --description 'Give output suitable for concatenation'
complete -c svn -n 'contains \'info\' (commandline -poc)' -l xml --description 'Output in XML'
complete -c svn -n 'contains \'info\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'info\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'info\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'info\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'info\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'list' subcommand
#

complete -c svn -n 'contains \'list\' (commandline -poc)' -l incremental --description 'Give output suitable for concatenation'
complete -c svn -n 'contains \'list\' (commandline -poc)' -l xml --description 'Output in XML'
complete -c svn -n 'contains \'list\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'list\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'list\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'list\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'list\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'ls' subcommand
#

complete -c svn -n 'contains \'ls\' (commandline -poc)' -l incremental --description 'Give output suitable for concatenation'
complete -c svn -n 'contains \'ls\' (commandline -poc)' -l xml --description 'Output in XML'
complete -c svn -n 'contains \'ls\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'ls\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'ls\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'ls\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'ls\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'lock' subcommand
#

complete -c svn -n 'contains \'lock\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'lock\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'lock\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'lock\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'lock\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'lock\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'lock\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'lock\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'
complete -c svn -n 'contains \'lock\' (commandline -poc)' -l force --description 'Force operation to run'


#
# Completions for the 'log' subcommand
#

complete -c svn -n 'contains \'log\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'log\' (commandline -poc)' -l stop-on-copy --description 'Do not cross copies while traversing history'
complete -c svn -n 'contains \'log\' (commandline -poc)' -l incremental --description 'Give output suitable for concatenation'
complete -c svn -n 'contains \'log\' (commandline -poc)' -l xml --description 'Output in XML'
complete -c svn -n 'contains \'log\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'log\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'log\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'log\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'log\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'
complete -c svn -n 'contains \'log\' (commandline -poc)' -l limit -x --description 'Maximum number of log entries'


#
# Completions for the 'merge' subcommand
#

complete -c svn -n 'contains \'merge\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'merge\' (commandline -poc)' -l dry-run --description 'Try operation but make no changes'
complete -c svn -n 'contains \'merge\' (commandline -poc)' -l diff3-cmd -x --description 'Use ARG as merge command'
complete -c svn -n 'contains \'merge\' (commandline -poc)' -l ignore-ancestry --description 'Ignore ancestry when calculating merges'
complete -c svn -n 'contains \'merge\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'merge\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'merge\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'merge\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'merge\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'mkdir' subcommand
#

complete -c svn -n 'contains \'mkdir\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'mkdir\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'mkdir\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'mkdir\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'mkdir\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'mkdir\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'mkdir\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'mkdir\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'move' subcommand
#

complete -c svn -n 'contains \'move\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'move\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'move\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'move\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'move\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'move\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'move\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'move\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'move\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'mv' subcommand
#

complete -c svn -n 'contains \'mv\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'mv\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'mv\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'mv\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'mv\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'mv\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'mv\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'mv\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'mv\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'rename' subcommand
#

complete -c svn -n 'contains \'rename\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'rename\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'rename\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'rename\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'rename\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'rename\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'rename\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'rename\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'rename\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'ren' subcommand
#

complete -c svn -n 'contains \'ren\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'ren\' (commandline -poc)' -l force-log --description 'Force validity of log message source'
complete -c svn -n 'contains \'ren\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'ren\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'ren\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'ren\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'ren\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'ren\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'ren\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'propdel' subcommand
#

complete -c svn -n 'contains \'propdel\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'propdel\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'propdel\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'propdel\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'propdel\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'propdel\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'pdel' subcommand
#

complete -c svn -n 'contains \'pdel\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'pdel\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'pdel\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'pdel\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'pdel\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'pdel\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'pd' subcommand
#

complete -c svn -n 'contains \'pd\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'pd\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'pd\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'pd\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'pd\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'pd\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'propedit' subcommand
#

complete -c svn -n 'contains \'propedit\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'propedit\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'propedit\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'propedit\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'propedit\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'propedit\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'propedit\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'propedit\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'propedit\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'pedit' subcommand
#

complete -c svn -n 'contains \'pedit\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'pedit\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'pedit\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'pedit\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'pedit\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'pedit\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'pedit\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'pedit\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'pedit\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'pe' subcommand
#

complete -c svn -n 'contains \'pe\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'pe\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'pe\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'pe\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'pe\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'pe\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'pe\' (commandline -poc)' -l editor-cmd -x --description 'Use ARG as external editor'
complete -c svn -n 'contains \'pe\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'pe\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'propget' subcommand
#

complete -c svn -n 'contains \'propget\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'propget\' (commandline -poc)' -l strict --description 'Use strict semantics'
complete -c svn -n 'contains \'propget\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'propget\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'propget\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'propget\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'propget\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'pget' subcommand
#

complete -c svn -n 'contains \'pget\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'pget\' (commandline -poc)' -l strict --description 'Use strict semantics'
complete -c svn -n 'contains \'pget\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'pget\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'pget\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'pget\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'pget\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'pg' subcommand
#

complete -c svn -n 'contains \'pg\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'pg\' (commandline -poc)' -l strict --description 'Use strict semantics'
complete -c svn -n 'contains \'pg\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'pg\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'pg\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'pg\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'pg\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'proplist' subcommand
#

complete -c svn -n 'contains \'proplist\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'proplist\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'proplist\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'proplist\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'proplist\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'proplist\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'plist' subcommand
#

complete -c svn -n 'contains \'plist\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'plist\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'plist\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'plist\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'plist\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'plist\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'pl' subcommand
#

complete -c svn -n 'contains \'pl\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'pl\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'pl\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'pl\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'pl\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'pl\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'propset' subcommand
#

complete -c svn -n 'contains \'propset\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'propset\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'propset\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'propset\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'propset\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'propset\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'propset\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'propset\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'propset\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'pset' subcommand
#

complete -c svn -n 'contains \'pset\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'pset\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'pset\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'pset\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'pset\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'pset\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'pset\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'pset\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'pset\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'ps' subcommand
#

complete -c svn -n 'contains \'ps\' (commandline -poc)' -l encoding -x --description 'Treat value as being in charset encoding ARG'
complete -c svn -n 'contains \'ps\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'ps\' (commandline -poc)' -l revprop --description 'Operate on a revision property (use with -r)'
complete -c svn -n 'contains \'ps\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'ps\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'ps\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'ps\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'ps\' (commandline -poc)' -l force --description 'Force operation to run'
complete -c svn -n 'contains \'ps\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'resolved' subcommand
#

complete -c svn -n 'contains \'resolved\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'resolved\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'revert' subcommand
#

complete -c svn -n 'contains \'revert\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'revert\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'status' subcommand
#

complete -c svn -n 'contains \'status\' (commandline -poc)' -l no-ignore --description 'Disregard default and svn:ignore property ignores'
complete -c svn -n 'contains \'status\' (commandline -poc)' -l incremental --description 'Give output suitable for concatenation'
complete -c svn -n 'contains \'status\' (commandline -poc)' -l xml --description 'Output in XML'
complete -c svn -n 'contains \'status\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'status\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'status\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'status\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'status\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'
complete -c svn -n 'contains \'status\' (commandline -poc)' -l ignore-externals --description 'Ignore externals definitions'


#
# Completions for the 'stat' subcommand
#

complete -c svn -n 'contains \'stat\' (commandline -poc)' -l no-ignore --description 'Disregard default and svn:ignore property ignores'
complete -c svn -n 'contains \'stat\' (commandline -poc)' -l incremental --description 'Give output suitable for concatenation'
complete -c svn -n 'contains \'stat\' (commandline -poc)' -l xml --description 'Output in XML'
complete -c svn -n 'contains \'stat\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'stat\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'stat\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'stat\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'stat\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'
complete -c svn -n 'contains \'stat\' (commandline -poc)' -l ignore-externals --description 'Ignore externals definitions'


#
# Completions for the 'st' subcommand
#

complete -c svn -n 'contains \'st\' (commandline -poc)' -l no-ignore --description 'Disregard default and svn:ignore property ignores'
complete -c svn -n 'contains \'st\' (commandline -poc)' -l incremental --description 'Give output suitable for concatenation'
complete -c svn -n 'contains \'st\' (commandline -poc)' -l xml --description 'Output in XML'
complete -c svn -n 'contains \'st\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'st\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'st\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'st\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'st\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'
complete -c svn -n 'contains \'st\' (commandline -poc)' -l ignore-externals --description 'Ignore externals definitions'


#
# Completions for the 'switch' subcommand
#

complete -c svn -n 'contains \'switch\' (commandline -poc)' -l diff3-cmd -x --description 'Use ARG as merge command'
complete -c svn -n 'contains \'switch\' (commandline -poc)' -l relocate --description 'Relocate via URL-rewriting'
complete -c svn -n 'contains \'switch\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'switch\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'switch\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'switch\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'switch\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'sw' subcommand
#

complete -c svn -n 'contains \'sw\' (commandline -poc)' -l diff3-cmd -x --description 'Use ARG as merge command'
complete -c svn -n 'contains \'sw\' (commandline -poc)' -l relocate --description 'Relocate via URL-rewriting'
complete -c svn -n 'contains \'sw\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'sw\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'sw\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'sw\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'sw\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'


#
# Completions for the 'unlock' subcommand
#

complete -c svn -n 'contains \'unlock\' (commandline -poc)' -l targets -x --description 'Pass contents of file ARG as additional args'
complete -c svn -n 'contains \'unlock\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'unlock\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'unlock\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'unlock\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'unlock\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'
complete -c svn -n 'contains \'unlock\' (commandline -poc)' -l force --description 'Force operation to run'


#
# Completions for the 'update' subcommand
#

complete -c svn -n 'contains \'update\' (commandline -poc)' -l diff3-cmd -x --description 'Use ARG as merge command'
complete -c svn -n 'contains \'update\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'update\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'update\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'update\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'update\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'
complete -c svn -n 'contains \'update\' (commandline -poc)' -l ignore-externals --description 'Ignore externals definitions'


#
# Completions for the 'up' subcommand
#

complete -c svn -n 'contains \'up\' (commandline -poc)' -l diff3-cmd -x --description 'Use ARG as merge command'
complete -c svn -n 'contains \'up\' (commandline -poc)' -l username -x --description 'Specify a username ARG'
complete -c svn -n 'contains \'up\' (commandline -poc)' -l password -x --description 'Specify a password ARG'
complete -c svn -n 'contains \'up\' (commandline -poc)' -l no-auth-cache --description 'Do not cache authentication tokens'
complete -c svn -n 'contains \'up\' (commandline -poc)' -l non-interactive --description 'Do no interactive prompting'
complete -c svn -n 'contains \'up\' (commandline -poc)' -l config-dir -x --description 'Read user configuration files from directory ARG'
complete -c svn -n 'contains \'up\' (commandline -poc)' -l ignore-externals --description 'Ignore externals definitions'



