function __fish_systemsetup_timezones
    systemsetup -listtimezones | tail -n +2 | string trim | string match -rv 'administrator access|exiting'
end

function __fish_systemsetup_startupdisks
    systemsetup -liststartupdisks | string match -rv 'administrator access|exiting'
end

complete -c systemsetup -f
complete -c systemsetup -n 'test (count (commandline -xpc)) -eq 1' -s f -d 'Skip confirmation prompts'
complete -c systemsetup -o getdate -d 'Display the current date'
complete -c systemsetup -o setdate -x -d 'Set the current date (mm:dd:yy)'
complete -c systemsetup -o gettime -d 'Display the current time in 24-hour format'
complete -c systemsetup -o settime -x -d 'Set the current time (hh:mm:ss)'
complete -c systemsetup -o gettimezone -d 'Display the current time zone'
complete -c systemsetup -o listtimezones -d 'List all time zones supported by this machine'
complete -c systemsetup -o settimezone -x -a '(__fish_systemsetup_timezones)' -d 'Set the local time zone'
complete -c systemsetup -o getusingnetworktime -d 'Display whether network time is on or off'
complete -c systemsetup -o setusingnetworktime -x -a 'on off' -d 'Set network time to on or off'
complete -c systemsetup -o getnetworktimeserver -d 'Display the currently set network time server'
complete -c systemsetup -o setnetworktimeserver -x -d 'Set the network time server (IP or DNS name)'
complete -c systemsetup -o getsleep -d 'Display idle time until machine sleeps'
complete -c systemsetup -o setsleep -x -a 'Never Off' -d 'Set idle minutes until computer sleeps (or Never/Off)'
complete -c systemsetup -o getcomputersleep -d 'Display idle time until computer sleeps'
complete -c systemsetup -o setcomputersleep -x -a 'Never Off' -d 'Set idle minutes until computer sleeps (or Never/Off)'
complete -c systemsetup -o getdisplaysleep -d 'Display idle time until display sleeps'
complete -c systemsetup -o setdisplaysleep -x -a 'Never Off' -d 'Set idle minutes until display sleeps (or Never/Off)'
complete -c systemsetup -o getharddisksleep -d 'Display idle time until hard disk sleeps'
complete -c systemsetup -o setharddisksleep -x -a 'Never Off' -d 'Set idle minutes until hard disk sleeps (or Never/Off)'
complete -c systemsetup -o getwakeonmodem -d 'Display whether wake on modem is on or off'
complete -c systemsetup -o setwakeonmodem -x -a 'on off' -d 'Set whether the server wakes from sleep on modem activity'
complete -c systemsetup -o getwakeonnetworkaccess -d 'Display whether wake on network access is on or off'
complete -c systemsetup -o setwakeonnetworkaccess -x -a 'on off' -d 'Set whether server wakes from sleep on network admin packet'
complete -c systemsetup -o getrestartpowerfailure -d 'Display whether restart on power failure is on or off'
complete -c systemsetup -o setrestartpowerfailure -x -a 'on off' -d 'Set whether server auto-restarts after a power failure'
complete -c systemsetup -o getrestartfreeze -d 'Display whether restart on freeze is on or off'
complete -c systemsetup -o setrestartfreeze -x -a 'on off' -d 'Set whether server restarts automatically after a system freeze'
complete -c systemsetup -o getallowpowerbuttontosleepcomputer -d 'Display whether power button can sleep the computer'
complete -c systemsetup -o setallowpowerbuttontosleepcomputer -x -a 'on off' -d 'Enable or disable the power button sleeping the computer'
complete -c systemsetup -o getremotelogin -d 'Display whether remote login (SSH) is on or off'
complete -c systemsetup -o setremotelogin -x -a 'on off' -d 'Set remote login (SSH) on or off (requires Full Disk Access)'
complete -c systemsetup -o getremoteappleevents -d 'Display whether remote Apple Events are on or off'
complete -c systemsetup -o setremoteappleevents -x -a 'on off' -d 'Set whether server responds to remote Apple Events'
complete -c systemsetup -o getcomputername -d 'Display the computer name'
complete -c systemsetup -o setcomputername -x -d 'Set the computer name (used by AFP)'
complete -c systemsetup -o getlocalsubnetname -d 'Display the local subnet name'
complete -c systemsetup -o setlocalsubnetname -x -d 'Set the local subnet name'
complete -c systemsetup -o getstartupdisk -d 'Display the current startup disk'
complete -c systemsetup -o liststartupdisks -d 'List all valid startup disks on this computer'
complete -c systemsetup -o setstartupdisk -x -a '(__fish_systemsetup_startupdisks)' -d 'Set the current startup disk to the indicated path'
complete -c systemsetup -o getwaitforstartupafterpowerfailure -d 'Get seconds before computer starts up after a power failure'
complete -c systemsetup -o setwaitforstartupafterpowerfailure -x -d 'Set seconds before startup after power failure (multiple of 30)'
complete -c systemsetup -o getdisablekeyboardwhenenclosurelockisengaged -d 'Get whether keyboard is disabled when enclosure lock is engaged'
complete -c systemsetup -o setdisablekeyboardwhenenclosurelockisengaged -x -a 'yes no' -d 'Set whether keyboard is disabled when enclosure lock is engaged'
complete -c systemsetup -o getkernelbootarchitecturesetting -d 'Get the kernel boot architecture setting from com.apple.Boot.plist'
complete -c systemsetup -o setkernelbootarchitecture -x -a 'i386 x86_64 default' -d 'Set kernel boot architecture for next boot'
complete -c systemsetup -o version -d 'Display version of systemsetup tool'
complete -c systemsetup -o help -d 'Display all commands with explanatory information'
complete -c systemsetup -o printCommands -d 'Display a list of commands with no detail'
