
# Peek inside of archives and list all files
complete -c tar -a "(__fish_complete_tar)"

complete -c tar -s A -l catenate --description "Append archive to archive"
complete -c tar -l concatenate --description "Append archive to archive"
complete -c tar -s c -l create --description "Create archive"
complete -c tar -s d -l diff --description "Compare archive and filesystem"
complete -c tar -l compare --description "Compare archive and filesystem"
complete -c tar -l delete --description "Delete from archive"
complete -c tar -s r -l append --description "Append files to archive"
complete -c tar -s t -l list --description "List archive"
complete -c tar -s u -l update --description "Append new files"
complete -c tar -s x -l extract --description "Extract from archive"
complete -c tar -l get --description "Extract from archive"
complete -c tar -l atime-preserve --description "Keep access time"
complete -c tar -s b -l block-size --description "Block size"
complete -c tar -s B -l read-full-blocks --description "Reblock while reading"
complete -c tar -s C -l directory -r --description "Change directory"
complete -c tar -l checkpoint --description "Print directory names"
complete -c tar -s f -l file -r --description "Archive file"
complete -c tar -l force-local --description "Archive is local"
complete -c tar -s F -l info-script --description "Run script at end of tape"
complete -c tar -s G -l incremental --description "Use old incremental GNU format"
complete -c tar -s g -l listed-incremental --description "Use new incremental GNU format"
complete -c tar -s h -l dereference --description "Dereference symlinks"
complete -c tar -s i -l ignore-zeros --description "Ignore zero block in archive"
complete -c tar -s j -l bzip --description "Filter through bzip2"
complete -c tar -l ignore-failed-read --description "Don't exit on unreadable files"
complete -c tar -s k -l keep-old-files --description "Don't overwrite"
complete -c tar -s K -l starting-file -r --description "Starting file in archive"
complete -c tar -s l -l one-file-system --description "Stay in local filesystem"
complete -c tar -s L -l tape-length -r --description "Tape length"
complete -c tar -s m -l modification-time --description "Don't extract modification time"
complete -c tar -s M -l multi-volume --description "Multi volume archive"
complete -c tar -s N -l after-date -r --description "Only store newer files"
complete -c tar -s o -l old-archive --description "Use V7 format"
complete -c tar -l portability --description "Use V7 format"
complete -c tar -s O -l to-stdout --description "Extract to stdout"
complete -c tar -s p -l same-permissions --description "Extract all permissions"
complete -c tar -l preserve-permissions --description "Extract all permissions"
complete -c tar -s P -l absolute-paths --description "Don't strip leading /"
complete -c tar -l preserve --description "Preserve all permissions and do not sort file arguments"
complete -c tar -s R -l record-number --description "Show record number"
complete -c tar -l remove-files --description "Remove files after adding to archive"
complete -c tar -s s -l same-order --description "Do not sort file arguments"
complete -c tar -l preserve-order --description "Do not sort file arguments"
complete -c tar -l same-owner --description "Preserve file ownership"
complete -c tar -s S -l sparse --description "Handle sparse files"
complete -c tar -s T -l files-from -r --description "Extract file from file"
complete -c tar -l null --description "-T has null-terminated names"
complete -c tar -l totals --description "Print total bytes written"
complete -c tar -s v -l verbose --description "Verbose mode"
complete -c tar -s V -l label -r --description "Set volume name"
complete -c tar -l version --description "Display version and exit"
complete -c tar -s w -l interactive --description "Ask for confirmation"
complete -c tar -l confirmation --description "Ask for confirmation"
complete -c tar -s W -l verify --description "Verify archive"
complete -c tar -l exclude -r --description "Exclude file"
complete -c tar -s X -l exclude-from -r --description "Exclude files listed in specified file"
complete -c tar -s Z -l compress --description "Filter through compress"
complete -c tar -l uncompress --description "Filter through compress"
complete -c tar -s z -l gzip --description "Filter through gzip"
complete -c tar -l gunzip --description "Filter through gzip"
complete -c tar -l use-compress-program -r --description "Filter through specified program"
complete -c tar -s J -l xz --description "Filter through xz"
