complete -c tflint -f
complete -c tflint -s c -l config -r -d "Config file name"
complete -c tflint -s f -l format -fra "default json checkstyle junit compact sarif" -d "Output format"
complete -c tflint -s h -l help -f -d "Show help message"
complete -c tflint -s v -l version -f -d "Print TFLint version"
complete -c tflint -l call-module-type -frka "all local none" -d "Types of module to call"
complete -c tflint -l chdir -r -d "Switch to a different working directory before executing the command"
complete -c tflint -l color -f -d "Enable colorized output"
complete -c tflint -l disable-rule -fr -d "Disable rules from the command line"
complete -c tflint -l enable-plugin -fr -d "Enable plugins from the command line"
complete -c tflint -l enable-rule -fr -d "Enable rules from the command line"
complete -c tflint -l filter -r -d "Filter issues by file names or globs"
complete -c tflint -l fix -f -d "Fix issues automatically"
complete -c tflint -l force -f -d "Return zero exit status even if issues found"
complete -c tflint -l ignore-module -fr -d "Ignore module sources"
complete -c tflint -l init -f -d "Install plugins"
complete -c tflint -l langserver -f -d "Start language server"
complete -c tflint -l max-workers -fr -d "Set maximum number of workers in recursive inspection"
complete -c tflint -l minimum-failure-severity -frka "error warning notice" -d "Sets minimum severity level for exiting with a non-zero error code"
complete -c tflint -l no-color -f -d "Disable colorized output"
complete -c tflint -l no-parallel-runners -f -d "Disable per-runner parallelism"
complete -c tflint -l only -fr -d "Enable only this rule, disabling all other defaults. Can be specified multiple times"
complete -c tflint -l recursive -f -d "Run command in each directory recursively"
complete -c tflint -l var -fr -d "Set a Terraform variable"
complete -c tflint -l var-file -r -d "Terraform variable file name"
