complete -c tmux -d 'Terminal multiplexer' -a 'attach'
complete -c tmux -s 2 -d 'Force tmux to assume the terminal supports 256 colours'
complete -c tmux -s 8 -d 'Like -2, but indicates that the terminal supports 88 colours'
complete -c tmux -s c -r -d 'Execute shell-command using the default shell'
complete -c tmux -s f -r -d 'Specify an alternative configuration file'
complete -c tmux -s L -x -d 'Specify the socket'
complete -c tmux -s l    -d 'Behave as a login shell'
complete -c tmux -s q    -d 'Set the quiet server option'
complete -c tmux -s S -r -d 'Specify a full alternative path to the server socket'
complete -c tmux -s u    -d 'Flag explicitly informs tmux that UTF-8 is supported'
complete -c tmux -s v    -d 'Request verbose logging'
complete -c tmux -s V    -d 'Report the tmux version'
complete -c tmux -d "Complete subcommand" -x -a "(__fish_complete_subcommand -c -f -L -S)"
