complete -c touch -s a -d (_ "Change access time")
complete -c touch -s B -l backward -x -d (_ "Set date back")
complete -c touch -s c -l no-create -d (_ "Do not create file")
complete -c touch -s d -l date -x -d (_ "Set date")
complete -c touch -s f -l forward -x -d (_ "Set date forward")
complete -c touch -s m -d (_ "Change modification time")
complete -c touch -s r -l reference -d (_ "Use this files times")
complete -c touch -s t -d (_ "Set date")
complete -c touch -l time -x -d (_ "Set time")
complete -c touch -l help -d (_ "Display help and exit")
complete -c touch -l version -d (_ "Display version and exit")
