complete -c transmission-remote -s a -l add -d 'Add torrents to transmission'
complete -c transmission-remote -s b -l debug -d 'Enable debugging mode'
complete -c transmission-remote -o as -l alt-speed -d 'Use the alternate Limits'
complete -c transmission-remote -o AS -l no-alt-speed -d 'Don\'t use the alternate Limits'
complete -c transmission-remote -o asd -l alt-speed-downlimit -d 'Limit the alternate download speed'
complete -c transmission-remote -o asu -l alt-speed-uplimit -d 'Limit the alternate upload speed'
complete -c transmission-remote -o asc -l alt-speed-scheduler -d 'Use the scheduled on/off times'
complete -c transmission-remote -o ASC -l no-alt-speed-scheduler -d 'Don\'t use the scheduled on/off times'
complete -c transmission-remote -l alt-speed-time-begin -d 'Time to start using the alt speed limits (in)'
complete -c transmission-remote -l alt-speed-time-end -d 'Time to stop using the alt speed limits (hhmm)'
complete -c transmission-remote -l alt-speed-days -d 'Number of days to enable the speed scheduler'
complete -c transmission-remote -l torrent-done-script -d 'Script to run each time a torrent finishes'
complete -c transmission-remote -l no-torrent-done-script -d 'Don\'t run any script when a torrent finishes'
complete -c transmission-remote -s c -l incomplete-dir -d 'Directory for incomplete downloads'
complete -c transmission-remote -s C -l no-incomplete-dir -d 'Don\'t store incomplete torrents in a different directory'
complete -c transmission-remote -s d -l downlimit -d 'Limit the maximum download speed to limit'
complete -c transmission-remote -s D -l no-downlimit -d 'Disable download speed limits'
complete -c transmission-remote -s e -l cache -d 'Set the session\'s maximum memory cache size (MiB)'
complete -c transmission-remote -o er -l encryption-required -d 'Encrypt all peer connections'
complete -c transmission-remote -o ep -l encryption-preferred -d 'Prefer encrypted peer connections'
complete -c transmission-remote -o et -l encryption-tolerated -d 'Prefer unencrypted peer connections'
complete -c transmission-remote -l exit -d 'Tell the Transmission to initiate a shutdown'
complete -c transmission-remote -s f -l files -d 'Get a file list for the current torrent(s)'
complete -c transmission-remote -s g -l get -d 'Mark file(s) for download'
complete -c transmission-remote -s G -l no-get -d 'Mark file(s) for not downloading'
complete -c transmission-remote -o gsr -l global-seedratio -d 'Ratio All torrents should seed'
complete -c transmission-remote -o GSR -l no-global-seedratio -d 'All torrents should seed regardless of ratio'
complete -c transmission-remote -s h -l help -d 'Print command-line option descriptions'
complete -c transmission-remote -s i -l info -d 'Show details of the current torrent(s)'
complete -c transmission-remote -o si -l session-info -d 'List session information from the server'
complete -c transmission-remote -o st -l session-stats -d 'List statistical information from the server'
complete -c transmission-remote -s l -l list -d 'List all torrents'
complete -c transmission-remote -s m -l portmap -d 'Enable portmapping via NAT-PMP or UPnP'
complete -c transmission-remote -s M -l no-portmap -d 'Disable portmapping'
complete -c transmission-remote -s n -l auth -d 'Set the username:password for authentication'
complete -c transmission-remote -o ne -l authenv -d 'Set the authentication information from $TR_AUTH'
complete -c transmission-remote -s N -l netrc -d 'Set authentication information from a netrc file'
complete -c transmission-remote -s o -l dht -d 'Enable distributed hash table (DHT)'
complete -c transmission-remote -s O -l no-dht -d 'Disable distribued hash table (DHT)'
complete -c transmission-remote -s p -l port -d 'Set the port to use when listening'
complete -c transmission-remote -o Bh -l bandwidth-high -d 'Give this torrent high bandwidth'
complete -c transmission-remote -o Bn -l bandwidth-normal -d 'Give this torrent normal bandwidth'
complete -c transmission-remote -o Bl -l bandwidth-low -d 'Give this torrent low bandwidth'
complete -c transmission-remote -o ph -l priority-high -d 'Try to download the specified files first'
complete -c transmission-remote -o pn -l priority-normal -d 'Try to download the specified files normally'
complete -c transmission-remote -o pl -l priority-low -d 'Try to download the specified files last'
complete -c transmission-remote -o pr -l peers -d 'Set the maximum number of peers'
complete -c transmission-remote -s r -l remove -d 'Remove the current torrents'
complete -c transmission-remote -l remove-and-delete -d 'Remove the current torrents and delete data'
complete -c transmission-remote -l reannounce -d 'Reannounce the current torrents'
complete -c transmission-remote -l move -d 'Move the current torrents\' data to another directory'
complete -c transmission-remote -l find -d 'Where to look for the current torrents\' data'
complete -c transmission-remote -o sr -l seedratio -d 'Current torrents seed until a specific ratio'
complete -c transmission-remote -o SR -l no-seedratio -d 'Current torrents seed regardless of ratio'
complete -c transmission-remote -o srd -l seedratio-default -d 'Current torrents use global seedratio'
complete -c transmission-remote -o td -l tracker-add -d 'Add a tracker to a torrent'
complete -c transmission-remote -o tr -l tracker-remove -d 'Remove a tracker from a torrent'
complete -c transmission-remote -s s -l start -d 'Start the current torrents'
complete -c transmission-remote -s S -l stop -d 'Stop the current torrents'
complete -c transmission-remote -l start-paused -d 'Start added torrents paused'
complete -c transmission-remote -l no-start-paused -d 'Start added torrents unpaused'
complete -c transmission-remote -s t -l torrent -d 'Set torrents as current for subsequent options'
complete -c transmission-remote -l trash-torrent -d 'Delete torrents after adding'
complete -c transmission-remote -l no-trash-torrent -d 'Do not delete torrents after adding'
complete -c transmission-remote -o hl -l honor-session -d 'Current torrents honor session limits'
complete -c transmission-remote -o HL -l no-honor-session -d 'Make the current torrent(s) not honor the session limits'
complete -c transmission-remote -s u -l uplimit -d 'Limit the maximum upload speed (KiB/s)'
complete -c transmission-remote -s U -l no-uplimit -d 'Disable upload speed limits'
complete -c transmission-remote -l utp -d 'Enable uTP for peer connections'
complete -c transmission-remote -l no-utp -d 'Disable uTP for peer connections'
complete -c transmission-remote -s v -l verify -d 'Verify the current torrents'
complete -c transmission-remote -s V -l version -d 'Show version number and exit'
complete -c transmission-remote -s w -l download-dir -d 'Use directory as default for new downloads'
complete -c transmission-remote -s x -l pex -d 'Enable peer exchange (PEX)'
complete -c transmission-remote -s X -l no-pex -d 'Disable peer exchange (PEX)'
complete -c transmission-remote -s y -l lds -d 'Enable local peer discovery (LPD)'
complete -c transmission-remote -s Y -l no-lds -d 'Disable local peer discovery (LPD)'
complete -c transmission-remote -o pi -l peer-info -d 'List the current torrent\'s connected peers'
