
complete -c ulimit -s a -l all -d (_ "Set or get all current limits")
complete -c ulimit -s c -l core-size -d (_ "Maximum size of core files created")
complete -c ulimit -s d -l data-size -d (_ "Maximum size of a process's data segment")
complete -c ulimit -s f -l file-size -d (_ "Maximum size of files created by the shell")
complete -c ulimit -s l -l lock-size -d (_ "Maximum size that may be locked into memory")
complete -c ulimit -s m -l resident-set-size -d (_ "Maximum resident set size")
complete -c ulimit -s n -l file-descriptor-count -d (_ "Maximum number of open file descriptors")
complete -c ulimit -s s -l stack-size -d (_ "Maximum stack size")
complete -c ulimit -s t -l cpu-time -d (_ "Maximum amount of cpu time in seconds")
complete -c ulimit -s u -l process-count -d (_ "Maximum number of processes available to a single user")
complete -c ulimit -s v -l virtual-memory-size -d (_ "Maximum amount of virtual memory available to the shell")
complete -c ulimit -s h -l help -d (_ "Display help and exit")
