complete -c unblob -s e -l extract-dir -x -a "(__fish_complete_directories)" -d "Extract the files to this directory"
complete -c unblob -s f -l force -d "Force extraction even if outputs already exist"
complete -c unblob -s d -l depth -x -d "Recursion depth"
complete -c unblob -s n -l randomness-depth -x -d "Entropy calculation depth"
complete -c unblob -s P -l plugins-path -r -d "Load plugins from the provided path"
complete -c unblob -s S -l skip-magic -x -d "Skip processing files with given magic prefix"
complete -c unblob -l skip-extension -x -d "Skip processing files with given extension"
complete -c unblob -l clear-skip-magics -d "Clear unblob's own skip magic list"
complete -c unblob -s p -l process-num -x -d "Number of worker processes to process files parallelly"
complete -c unblob -l report -r -d "File to store metadata generated during the extraction process"
complete -c unblob -l log -r -d "File to save logs"
complete -c unblob -s s -l skip-extraction -d "Only carve chunks and skip further extraction"
complete -c unblob -l no-sandbox -d "Disable Landlock sandboxing"
complete -c unblob -s k -l keep-extracted-chunks -d "Keep extracted chunks"
complete -c unblob -l delete-extracted-files -x -d "Delete fully extracted intermediate files"
complete -c unblob -l carve-suffix -x -d "Carve directory name is source file + this suffix"
complete -c unblob -l extract-suffix -x -d "Extraction directory name is source file + this suffix"
complete -c unblob -s v -l verbose -d "Verbosity level (-v, -vv, -vvv)"
complete -c unblob -l show-external-dependencies -x -d "Shows commands needs to be available for unblob to work properly"
complete -c unblob -l build-handlers-doc -r -d "Build handlers markdown documentation"
complete -c unblob -l version -x -d "Show the version"
complete -c unblob -s h -l help -x -d "Show this message"
