complete -c VBoxSDL -l startvm -x -d "Set virtual machine to start" -a "(__fish_print_VBox_vms)"

complete -c VBoxSDL -l separate -d "Run separate VM process or attach to a running VM"
complete -c VBoxSDL -l hda -f -d "Set temporary first hard disk"
complete -c VBoxSDL -l fda -f -d "Set temporary first floppy disk"
complete -c VBoxSDL -l cdrom -r -d "Set temporary CDROM/DVD" -a "none\tunmount"
complete -c VBoxSDL -l boot -x -d "Set temporary boot device" -a "a\tFloppy c\tFirst\ HD d\tDVD n\tNetwork"
complete -c VBoxSDL -l memory -x -d "Set temporary memory size in MB"
complete -c VBoxSDL -l vram -x -d "Set temporary video memory size in MB"
complete -c VBoxSDL -l fullscreen -d "Start VM in fullscreen mode"
complete -c VBoxSDL -l fullscreenresize -d "Resize guest on fullscreen"
complete -c VBoxSDL -l fixedmode -r -d "Use fixed SDL video mode with given width height and bit/pixel"
complete -c VBoxSDL -l nofstoggle -d "Forbid switching to/from fullscreen mode"
complete -c VBoxSDL -l noresize -d "Make SDL frame non resizable"
complete -c VBoxSDL -l nohostkey -d "Disable all hoskey combinations"
complete -c VBoxSDL -l nohostkeys -d "Disable specific hostkey combinations"
complete -c VBoxSDL -l nograbonclick -d "Disable mouse/keyboard grabbing on mouse click w/o additions"
complete -c VBoxSDL -l detecthostkey -d "Get hostkey identifier and modifier state"
complete -c VBoxSDL -l hostkey -r -d "Set host key to values obtained using --detecthostkey"
complete -c VBoxSDL -l termacpi -d "Send APCI power button when closing window"
complete -c VBoxSDL -l vrdp -d "Listen for VRDP connexions on if one of specified"
complete -c VBoxSDL -l discardstate -d "Discard saved state (if present) and revert to last snapshot (if present)"
complete -c VBoxSDL -l settingspw -x -d "Specify settings password"
complete -c VBoxSDL -l settingspwfile -f -d "Specify file containing setting password"
complete -c VBoxSDL -l rowr0 -d "Enable raw ring 3"
complete -c VBoxSDL -l rowr3 -d "Enable raw ring 0"
complete -c VBoxSDL -l patm -d "Enable PATM"
complete -c VBoxSDL -l csam -d "Enable CSAM"
complete -c VBoxSDL -l hwvirtex -d "Permit usage of VT-x/AMD-V"
complete -c VBoxSDL -l norowr0 -d "Disable raw ring 3"
complete -c VBoxSDL -l norowr3 -d "Disable raw ring 0"
complete -c VBoxSDL -l nopatm -d "Disable PATM"
complete -c VBoxSDL -l nocsam -d "Disable CSAM"
complete -c VBoxSDL -l nohwvirtex -d "Deny usage of VT-x/AMD-V"
