complete -c w -s h -d (_ "Dont print header")
complete -c w -s u -d (_ "Ignore username for time calculations")
complete -c w -s s -d (_ "Short format")
complete -c w -s f -d (_ "Toggle printing of remote hostname")
complete -c w -s V -d (_ "Display version and exit")
complete -c w -x -a "(__fish_complete_users)" -d (_ "Username")
