complete -c wc -s c -l bytes -d (_ "Print byte counts")
complete -c wc -s m -l chars -d (_ "Print character counts")
complete -c wc -s l -l lines -d (_ "Print newline counts")
complete -c wc -s L -l max-line-length -d (_ "Print length of longest line")
complete -c wc -s w -l words -d (_ "Print word counts")
complete -c wc -l help -d (_ "Display help and exit")
complete -c wc -l version -d (_ "Display version and exit")
