complete -c wc -s c -l bytes -d (N_ "Print byte counts")
complete -c wc -s m -l chars -d (N_ "Print character counts")
complete -c wc -s l -l lines -d (N_ "Print newline counts")
complete -c wc -s L -l max-line-length -d (N_ "Print length of longest line")
complete -c wc -s w -l words -d (N_ "Print word counts")
complete -c wc -l help -d (N_ "Display help and exit")
complete -c wc -l version -d (N_ "Display version and exit")
