complete -c wicd-gtk -s t -l tray -d 'Run the wicd tray icon only.'
complete -c wicd-gtk -s n -l no-tray -d 'Run wicd without the tray icon.'
complete -c wicd-gtk -s h -l help -d 'Print this help information.'
complete -c wicd-gtk -s a -l no-animate -d 'Run the tray without network traffic tray animations.'
complete -c wicd-gtk -s o -l only-notifications -d 'Don\'t display anything except notifications.'
