complete -c winemaker -l nobanner -d 'No banner'
complete -c winemaker -l backup -d 'Perform backup'
complete -c winemaker -l nobackup -d 'No backup'
complete -c winemaker -l nosource-fix -d 'Perform source fixing'
complete -c winemaker -l lower-all -d 'Transform everything to lowercase'
complete -c winemaker -l lower-uppercase -d 'Transform uppercase to lowercase'
complete -c winemaker -l lower-none -d 'No case changing'
complete -c winemaker -l lower-include -d 'Transform when no referenced file found'
complete -c winemaker -l nolower-include -d 'No case changing when no referenced file found'
complete -c winemaker -l guiexe -d 'Treat unknown app as GUI app'
complete -c winemaker -l windows -d 'Treat unknown app as GUI app'
complete -c winemaker -l cuiexe -d 'Treat unknown app as console app'
complete -c winemaker -l console -d 'Treat unknown app as console app'
complete -c winemaker -l dll -d 'Treat unknown app as library'
complete -c winemaker -l nodlls -d 'No stadard libraries usage'
