complete -c wineboot -s h -l help -d 'Show help and exit'
complete -c wineboot -s e -l end-session -d 'End the current session cleanly'
complete -c wineboot -s f -l force -d 'Force exit for processes that don\'t exit cleanly'
complete -c wineboot -s i -l init -d 'Perform initialization for first Wine instance'
complete -c wineboot -s k -l kill -d 'Kill running processes without any cleanup'
complete -c wineboot -s r -l restart -d 'Restart only, don\'t do normal startup operations'
complete -c wineboot -s s -l shutdown -d 'Shutdown only, don\'t reboot'
complete -c wineboot -s u -l update -d 'Update the wineprefix directory'
