#completions for wpa_cli
complete -x -c wpa_cli -a status -d 'get current WPA/EAPOL/EAP status'
complete -x -c wpa_cli -a mib -d 'get MIB variables (dot1x, dot11)'
complete -x -c wpa_cli -a help -d 'show this usage help'
complete -x -c wpa_cli -a interface -d 'show interfaces/select interface'
complete -x -c wpa_cli -a level -d 'change debug level'
complete -x -c wpa_cli -a license -d 'show full wpa_cli license'
complete -x -c wpa_cli -a logoff -d 'IEEE 802.1X EAPOL state machine logoff'
complete -x -c wpa_cli -a logon -d 'IEEE 802.1X EAPOL state machine logon'
complete -x -c wpa_cli -a set -d 'set/list variables'
complete -x -c wpa_cli -a pmksa -d 'show PMKSA cache'
complete -x -c wpa_cli -a reassociate -d 'force reassociation'
complete -x -c wpa_cli -a reconfigure -d 'force wpa_supplicant to re-read its config file'
complete -x -c wpa_cli -a preauthenticate -d 'force preauthentication'
complete -x -c wpa_cli -a identity -d 'configure identity for an SSID'
complete -x -c wpa_cli -a password -d 'configure password for an SSID'
complete -x -c wpa_cli -a new_password -d 'change password for an SSID'
complete -x -c wpa_cli -a pin -d 'configure pin for an SSID'
complete -x -c wpa_cli -a otp -d 'configure one-time-password for an SSID'
complete -x -c wpa_cli -a passphrase -d 'configure private key passphrase for an SSID'
complete -x -c wpa_cli -a bssid -d 'set preferred BSSID for an SSID'
complete -x -c wpa_cli -a list_networks -d 'list configured networks'
complete -x -c wpa_cli -a select_network -d 'select a network (disable others)'
complete -x -c wpa_cli -a enable_network -d 'enable a network'
complete -x -c wpa_cli -a disable_network -d 'disable a network'
complete -x -c wpa_cli -a add_network -d 'add a network'
complete -x -c wpa_cli -a remove_network -d 'remove a network'
complete -x -c wpa_cli -a set_network -d 'set/list network variables'
complete -x -c wpa_cli -a get_network -d 'get network variables'
complete -x -c wpa_cli -a save_config -d 'save the current configuration'
complete -x -c wpa_cli -a disconnect -d 'disconnect and wait for reassociate command before connecting'
complete -x -c wpa_cli -a scan -d 'request new BSS scan'
complete -x -c wpa_cli -a scan_results -d 'get latest scan results'
complete -x -c wpa_cli -a get_capability -d 'get capabilies'
complete -x -c wpa_cli -a stakey-request -d 'request STAKey negotiation with <addr>'
complete -x -c wpa_cli -a ap_scan -d 'set ap_scan parameter'
complete -x -c wpa_cli -a stkstart -d 'request STK negotiation with <addr>'
complete -x -c wpa_cli -a terminate -d 'terminate wpa_supplicant'
