complete -c xsel -s a -l append -d (_ "Append input to selection")
complete -c xsel -s f -l follow -d (_ "Append to selection as input grows")
complete -c xsel -s i -l input -d (_ "Read into selection")
complete -c xsel -s o -l output -d (_ "Write selection")
complete -c xsel -s c -l clear -d (_ "Clear selection")
complete -c xsel -s d -l delete -d (_ "Delete selection")
complete -c xsel -s p -l primary -d (_ "Use primary selection")
complete -c xsel -s s -l secondary -d (_ "Use secondary selection")
complete -c xsel -s b -l clipboard -d (_ "Use clipboard selection")
complete -c xsel -s k -l keep -d (_ "Make current selections persistent after program exit")
complete -c xsel -s x -l exchange -d (_ "Exchange primary and secondary selections")
complete -c xsel -l display -x -d (_ "X server display")
complete -c xsel -s t -l selectionTimeout -d (_ "Timeout for retrieving selection")
complete -c xsel -s l -l logfile -f -d (_ "Error log")
complete -c xsel -s n -l nodetach -d (_ "Do not detach from the controlling terminal")
complete -c xsel -s h -l help -d (_ "Display help and exit")
complete -c xsel -s v -l verbose -d (_ "Print informative messages")
complete -c xsel -l version -d (_ "Display version and exit")
