complete --command xsp --long-option help --description 'Show help'
complete --command xsp --long-option version --description 'Show version'

complete --command xsp --long-option address --require-parameter --no-files --description 'Use the IP address to listen on'
complete --command xsp --long-option port --require-parameter --no-files --description 'Use the port where the XSP server will listen to requests'
complete --command xsp --long-option backlog --require-parameter --no-files --description 'Use the backlog of connections to set on the listener socket'
complete --command xsp --long-option minThreads --require-parameter --no-files --description 'Specify minimum number of threads the threadpool allocates'
complete --command xsp --long-option filename --require-parameter --description 'Use unix socket file name to listen on'
complete --command xsp --long-option root --require-parameter --description 'Use root directory for XSP'
complete --command xsp --long-option appconfigfile --require-parameter --description 'Add application definitions from the XML configuration file'
complete --command xsp --long-option appconfigdir --require-parameter --description 'Add application definitions from all XML files found in the specified directory'
complete --command xsp --long-option applications --no-files --arguments '(__complete_xsp_applications_directories)' --require-parameter --description 'Use a comma separated list of virtual directory and real directory for all the applications'
complete --command xsp --long-option master --no-files --require-parameter --description 'Use this instance by mod_mono to create ASP.NET applications on demand'
complete --command xsp --long-option no-hidden --description 'Do not protect hidden files/directories from being accessed by clients'
complete --command xsp --long-option https --description 'Enable HTTPS support on the server'
complete --command xsp --long-option https-client-accept --description 'Like --https enable HTTPS support on the server'
complete --command xsp --long-option https-client-require --description 'Like --https enable HTTPS support on the server'
complete --command xsp --long-option p12file --require-parameter --description 'Use to specify the PKCS#12 file to use'
complete --command xsp --long-option cert --require-parameter --description 'Use to specify the server X.509 certificate file'
complete --command xsp --long-option pkpwd --require-parameter --description 'Use password to decote the private key'

complete --command xsp --long-option protocol --arguments 'Default\t"Auto-detect the client protocol and adjust the server protocol accordingly" Tls\t"Tls protocol" Ssl3\t"Ssl3 protocol"' --no-files --require-parameter --description 'Use protocols available for encrypting the communications'

complete --command xsp --long-option terminate --description 'Gracefully terminates a running mod-mono-server instance'
complete --command xsp --long-option verbose --description 'Show more messages'
complete --command xsp --long-option pidfile --require-parameter --description 'Redirect xsp4 PID output in stdout to file'
