complete -c xxh64sum -s V -l version -d "Display version"
complete -c xxh64sum -l little-endian -d "Display hashes in little endian"
complete -c xxh64sum -s h -l help -d "Display help"
complete -c xxh64sum -s c -l check -d "Check xxHash sums"
complete -c xxh64sum -s q -l quiet -d "Don't print OK when the checksum match"
complete -c xxh64sum -l strict -d "Exit non-zero if any line is invalid"
complete -c xxh64sum -l status -d "Don't output anything"
complete -c xxh64sum -s w -l warn -d "Warn about invalid lines"
complete -c xxh64sum -s b -d "Run a benchmark"
complete -c xxh64sum -s B -d "Test data block size of benchmark"
complete -c xxh64sum -s i -d "Number of benchmark iterations"
