# General
complete -c zabbix_sender -F -s c -l config -d "Zabbix Agent configuration file."
complete -c zabbix_sender -f -s z -l zabbix-server -d "Hostname or IP address of Zabbix server."
complete -c zabbix_sender -f -s p -l port -d "Specify port number of agent running on the host."
complete -c zabbix_sender -f -s I -l source-address -d "Source IP address."
complete -c zabbix_sender -f -s t -l timeout -d "Specify timeout."
complete -c zabbix_sender -f -s s -l host -d "Specify host name the item belongs to."
complete -c zabbix_sender -f -s k -l key -d "Specify item key to send value to."
complete -c zabbix_sender -f -s o -l value -d "Specify item value."
complete -c zabbix_sender -s i -l input-file -d "Load values from input file."
complete -c zabbix_sender -f -s h -l help -d "Display this help and exit."
complete -c zabbix_sender -f -s V -l version -d "Output version information and exit."
complete -c zabbix_sender -s T -l with-timestamps -d "Input file contains timestamps"
complete -c zabbix_sender -s N -l with-ns -d "Timestamps have nanosecond portion."
complete -c zabbix_sender -s r -l real-time -d "Send values as soon as they are received."
complete -c zabbix_sender -s v -l verbose -d "Verbose mode, -vv for more details."

# TLS
complete -c zabbix_sender -f -r -l tls-connect -a "unencrypted psk cert" -d "How to connect to agent."
complete -c zabbix_sender -l tls-ca-file -F -d "Full path of a with the top-level CA(s)."
complete -c zabbix_sender -l tls-crl-file -F -d "Full path of a file with revoked certificates."
complete -c zabbix_sender -f -l tls-server-cert-issuer -d "Allowed server certificate issuer."
complete -c zabbix_sender -f -l tls-server-cert-subject -d "Allowed server certificate subject."
complete -c zabbix_sender -l tls-cert-file -d "Full path of the certificate or certificate chain."
complete -c zabbix_sender -l tls-key-file -d "Full path of  the private key."
complete -c zabbix_sender -f -l tls-psk-identity -d "PSK-identity string."
complete -c zabbix_sender -l tls-psk-file -d "Full path of a file with the pre-shared key."
complete -c zabbix_sender -f -l tls-cipher13 -d "Cipher string for OpenSSL."
complete -c zabbix_sender -f -l tls-cipher -d "GnuTLS priority string."
