# General
complete -c zabbix_sender -F -s c -l config -d "Zabbix sender reads server details from the agentd configuration file."
complete -c zabbix_sender -f -s z -l zabbix-server -d "Hostname or IP address of Zabbix server."
complete -c zabbix_sender -f -s p -l port -d "Specify port number of agent running on the host. Default is 10050."
complete -c zabbix_sender -f -s I -l source-address -d "Specify source IP address."
complete -c zabbix_sender -f -s t -l timeout -d "Specify timeout. Valid range: 1-30 seconds (default: 30)"
complete -c zabbix_sender -f -s s -l host -d "Specify host name the item belongs to (as registered in Zabbix frontend)."
complete -c zabbix_sender -f -s k -l key -d "Specify item key to send value to."
complete -c zabbix_sender -f -s o -l value -d "Specify item value."
complete -c zabbix_sender -s i -l input-file -d "Load values from input file."
complete -c zabbix_sender -f -s h -l help -d "Display this help and exit."
complete -c zabbix_sender -f -s V -l version -d "Output version information and exit."
complete -c zabbix_sender -s T -l with-timestamps -d "This option can be only used with --input-file option."
complete -c zabbix_sender -s N -l with-ns -d "This option can be only used with --with-timestamps option."
complete -c zabbix_sender -s r -l real-time -d "Send values one by one as soon as they are received. This can be used when reading from standard input."
complete -c zabbix_sender -s v -l verbose -d "Verbose mode, -vv for more details."


# TLS
complete -c zabbix_sender -f -r -l tls-connect -a "unencrypted psk cert" -d "How to connect to agent."
complete -c zabbix_sender -l tls-ca-file -F -d "Full pathname of a file containing the top-level CA(s) certificates for peer certificate verification."
complete -c zabbix_sender -l tls-crl-file -F -d " Full pathname of a file containing revoked certificates."
complete -c zabbix_sender -f -l tls-server-cert-issuer -d "Allowed server certificate issuer."
complete -c zabbix_sender -f -l tls-server-cert-subject -d "Allowed server certificate subject."
complete -c zabbix_sender -l tls-cert-file -d "Full pathname of a file containing the certificate or certificate chain."
complete -c zabbix_sender -l tls-key-file -d "Full pathname of a file containing the private key."
complete -c zabbix_sender -f -l tls-psk-identity -d "PSK-identity string."
complete -c zabbix_sender -l tls-psk-file -d "Full pathname of a file containing the pre-shared key."
complete -c zabbix_sender -f -l tls-cipher13 -d "Cipher string for OpenSSL 1.1.1 or newer for TLS 1.3. Override the default ciphersuite selection criteria. This option is not available if OpenSSL version is less than 1.1.1."
complete -c zabbix_sender -f -l tls-cipher -d "GnuTLS priority string (for TLS 1.2 and up) or OpenSSL cipher string (only for TLS 1.2). Override the default ciphersuite selection criteria."

