#!/bin/sh -x

logger -s -t "${INSTALL_PKG_SESSION_ID}" "Removing any previous installation"
pkgutil --pkg-info ${INSTALL_PKG_SESSION_ID} && pkgutil pkgutil --only-files --files ${INSTALL_PKG_SESSION_ID} | while read installed
     do rm -v ${DSTVOLUME}${installed}
done | logger -s -t "${INSTALL_PKG_SESSION_ID}"
logger -s -t "${INSTALL_PKG_SESSION_ID}" "... removed"
