name: Build Docker test images

on:
  push:
    paths:
      - 'docker/**'
  workflow_dispatch:

concurrency:
  group: docker-builds

jobs:
  docker-build:
    if: github.repository_owner == 'fish-shell'
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: alpine
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2, build_tools/update-dependencies.sh
      - run: |
          printf %s "${{ secrets.GITHUB_TOKEN }}" |
            docker login ghcr.io --username=${{ github.actor }} --password-stdin
          docker/push.sh docker/${{ matrix.target }}.Dockerfile
