# GitHub CI to automatically add labels to certain PRs, per the configuration
# set out in .github/labeler.yaml
#
# See reference at https://github.com/actions/labeler

name: "Auto-label PRs"
on: pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: '.github/labeler.yml' # this is the default
          sync-labels: true
