name: Lint Dependencies
on:
  push:
    paths:
      - '.github/workflows/lint-dependencies.yml'
      - 'Cargo.lock'
      - '**/Cargo.toml'
      - 'deny.toml'
  pull_request:
    paths:
      - '.github/workflows/lint-dependencies.yml'
      - 'Cargo.lock'
      - '**/Cargo.toml'
      - 'deny.toml'
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1, build_tools/update-dependencies.sh
    - uses: EmbarkStudios/cargo-deny-action@c3bbe7e4e3f7baeee1a3dd9aec0a3b2aded580fb # v2.1.1, build_tools/update-dependencies.sh
      with:
        command: check licenses
        arguments: --all-features --locked --exclude-dev
        rust-version: 1.98 # updatecli.d/rust.yml
