name: Rust checks

on: [push, pull_request]

permissions:
  contents: read

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/rust-toolchain@stable
      with:
        components: rustfmt
    - name: cargo fmt
      run: cargo xtask cargo fmt --check

  clippy-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/rust-toolchain@stable
      with:
        components: clippy
    - name: Install deps
      run: |
        sudo apt install gettext
    - name: cargo clippy
      run: cargo xtask cargo clippy --workspace --all-targets -- --deny=warnings

  clippy-msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/rust-toolchain@oldest-supported
      with:
        components: clippy
    - name: Install deps
      run: |
        sudo apt install gettext
    - name: cargo clippy
      run: cargo xtask cargo clippy --workspace --all-targets -- --deny=warnings

  rustdoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/rust-toolchain@stable
    - name: cargo doc
      run: |
        RUSTDOCFLAGS='-D warnings' cargo xtask cargo doc --workspace
    - name: cargo doctest
      run: |
        cargo xtask cargo test --doc --workspace
