name: Install sphinx

permissions:
  contents: read

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -x
        sudo pip install uv --break-system-packages
        command -v uv
        command -v uvx
        # Check that pyproject.toml and the lock file are in sync.
        # TODO Use "uv" to install Python as well.
        : 'Note that --no-managed-python below would be implied but be explicit'
        uv='env UV_PYTHON=python uv --no-managed-python'
        $uv lock --check
        # Install globally.
        sudo $uv pip install --group=dev --system --break-system-packages
        # Smoke test.
        python -c 'import sphinx; import sphinx_markdown_builder'
